bcgov/common-hosted-form-service

app/src/forms/common/models/models.js
app/src/forms/rbac/controller.js
app/src/forms/rbac/service.js
app/src/forms/rbac/transformer.js

Add query params for /rbac/current, /rbac/users, rbac/forms.  Allow caller to filter on permissions and roles (and other 
Note, this is only for GET calls, PUT to /rbac/users and /rbac/forms will only evaluate userId and formId.
When querying by permissions and roles, these are OR.  if 2 permissions and 1 role, then results will be if any of the 3 items is true, the record will be included in the results.
ex /rbac/users?permissions=submissionDelete&permissions=designDelete&roles=Owner
Results will include users and their forms where they have one of the permissions OR the role.
**IMPORTANT** the permissions/role filtering is done server-side, but not on the query.  After we've fetched the data (according to the other query params), we filter those results if permissions/roles are …

RBAC query enhancements.

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/public/index.html
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/router/index.js
app/frontend/src/services/formService.js
app/frontend/src/utils/constants.js
app/frontend/src/views/Editor.vue
app/frontend/src/views/designer/Root.vue
app/src/forms/form/service.js

This PR adds formio editor component support. FormDesigner component and Root route takes in formId and formVersionId as props. This has been mounted in the vue router as a parameterized child. At this time, the component can only save to an existing version (U in CRUD).
Assuming you are using the temporary seed script... route has following path: `/editor/:formId/versions/:formVersionId`
"Start a new form": http://localhost:8081/app/editor (no path params, submit button does not work in this case)
"Update an existing form": http://localhost:8081/app/editor/b1cff682-1412-442a-ac6a-cd70baa35022/versions/544cb861-a435-4f34-8994-49a0723de0b7 (has path params for both formId and formVersionId).
TODO: figure out the C in CRUD flow.

Add minimally functional form editor

---

app/src/db/migrations/20200807133615_000-init.js
app/src/db/migrations/20200825155537_001-views.js
app/src/db/migrations/20200825155537_002-idp_role_permission_data.js
app/src/db/seeds/999-dev-seed-data.js
app/src/docs/CHEFS_API_Documentation.postman_collection.json
app/src/docs/v1.api-spec.yaml
app/src/forms/common/models/models.js
app/src/forms/permission/controller.js
app/src/forms/permission/routes.js
app/src/forms/permission/service.js
app/src/forms/rbac/service.js
app/src/forms/role/controller.js
app/src/forms/role/routes.js
app/src/forms/role/service.js

Add migration script to populate Roles, Permissions and Identity Providers.
Update Roles/Permissions to use code as PK, not UUID.  Easier to deal with.
Add a seed file to load dev related data.
```sh
./node_modules/.bin/knex seed:run
```

Roles and Permission Init

---

Jenkinsfile
Jenkinsfile.cicd
README.md
app/README.md
app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
app/frontend/tests/unit/router/index.spec.js
app/package.json
app/tests/unit/routes/v1.spec.js
openshift/README.md
openshift/app.bc.yaml
openshift/app.dc.yaml
openshift/commonPipeline.groovy
openshift/patroni-ephemeral.dc.yaml
openshift/patroni.dc.yaml
openshift/patroni.secret.yaml
sonar-project.properties

This PR implements our standard Jenkins and SonarQube pipeline.
[SHOWCASE-1513](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1513)
Example sample form: https://chefs-dev.pathfinder.gov.bc.ca/pr-13/editor/edcc449d-3544-4fd3-acef-bd641109a392/versions/4d43d009-cfcd-412a-8396-a6920209691c

Implement Jenkins Pipeline & SonarQube

---

app/frontend/package-lock.json
app/package.json
app/src/db/migrations/20200825155537_001-views.js
app/src/db/seeds/999-dev-seed-data.js
app/src/forms/admin/controller.js
app/src/forms/admin/index.js
app/src/forms/admin/routes.js
app/src/forms/admin/service.js
app/src/forms/auth/middleware/userAccess.js
app/src/forms/auth/service.js
app/src/forms/common/models/models.js
app/src/forms/form/controller.js
app/src/forms/form/routes.js
app/src/forms/form/service.js
app/src/forms/permission/controller.js
app/src/forms/permission/service.js
app/src/forms/rbac/controller.js
app/src/forms/rbac/routes.js
app/src/forms/rbac/service.js
app/src/forms/role/controller.js
app/src/forms/role/routes.js
app/src/forms/role/service.js
app/src/routes/v1.js

Update the currentUser middleware to check and validate token first - reject if token is bad.
All /rbac, /roles, /permissions require keycloak authentication.
/admin requires chefs:admin role in token.
Add createdBy/updatedBy userstamps for creates and updates from the currentUser.

Add /admin api for simple (temporary) form/user/role management.

---

app/src/db/migrations/20200807133615_000-init.js
app/src/forms/common/constants.js
app/src/forms/common/models/models.js
app/src/forms/form/service.js

Add in proper schema level validation (so we get 422 not 500 on invalid models).
Add in a business rule check that validates if an identity provider submitted on create form, that it is valid and active.
**Important** I also removed the unique constraint on form.name field.  Either drop your constraint, or reset your database.

Basic schema level validation on models.

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/filters/index.js
app/frontend/src/main.js
app/frontend/src/services/formService.js
app/frontend/src/views/form/FormManage.vue
app/frontend/src/views/form/FormSubmissionView.vue

- Add settings for user type/idps on form build
- Other formatting stuff
- Navigate away from pages on form creation
Still needs some more proper error handling and success messaging.
An issue where if the non-creating user fills out the form it fails to populate on the readonly success screen.
Will address these in next PR but should get this structure reviewed and merged in soon.

Permission selection on form build, other UI updates

---

Jenkinsfile

This PR enables the Test stage of the Jenkins pipeline.
[SHOWCASE-1545](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1545)

Enable TEST stage in pipeline

---

app/frontend/src/components/designer/FormDesigner.vue

Form.io was not happy in the onChangeMethod when we were storing and managing the formSchema as a Vue data object. This PR resolves this by making formSchema be a plain old javascript variable instead.

Bugfix comp is null bug when using top-level Layout options

---

app/frontend/src/components/designer/FormViewer.vue

Use formio events as it expects them for form submit.
Override some of the default behaviour when you add your own submit or reset button (it posts to /submit or /reset), need to remove the 'action' value.
Hooks into formio form errors on a submission error (unsure if that's what we will continue with).
Calls router.push when submit is marked as successfully completed (no more spinning icon on submit button).
[SHOWCASE-1568](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1568?)

Use formio events to manage submit and reset requests.

---

app/frontend/public/index.html
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/TeamManagement.vue
app/frontend/src/services/rbacService.js
app/frontend/src/utils/constants.js
app/frontend/src/views/form/FormTeams.vue
app/src/forms/rbac/service.js

This PR implements a Team Management component which has the following capabilities:
* List all users with access to form
* List all roles each user has assigned to them
* Ability to check/uncheck each role/user in the matrix as desired
* Rollback button to revert to last known DB state
* Update button to submit role/user changes
* Responsive mobile table view support
This PR also does the following:
* Add in missing transactions on some RBAC service calls
* Invert FormTable button order based on probability of access
[SHOWCASE-1450](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1450)
Currently the TeamManagement component is mounted on a potentially temporary route and …

Team Management Component

---

app/frontend/src/components/forms/TeamManagement.vue

Add a fixed width (percentage) for the role columns in Team Management; makes for consistency with the whitespace between checkboxes.  
If we allow teams to create their own roles, we will have to change the UI.

Add simple class styling to the Role columns in Team Management.

---

app/config/default.json

This PR changes the default serverUrl authentication endpoint to new gov oidc url. In deployment, only the config maps need to be updated.
[SHOWCASE-1569](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1569)

Change default serverUrl authentication endpoint to new gov oidc url

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/router/index.js

Typical browser warning when a user closes an in-progress page
Designer
Turn on when they go to step 2
Turn off when it succeeds
Viewer
Turn on when loaded
Turn off when succeeds

Add leave page protection

---

app/src/db/migrations/20201007113516_004-alter-form-view.js

Alter distinct clause so forms view will return forms with same name.
Tested migration up, down, rollback, all.

Fix for view not returning forms with same name

---

app/package-lock.json
app/package.json
app/src/db/migrations/20201007112921_005-submissions-data-vw.js
app/src/forms/common/models/models.js
app/src/forms/form/controller.js
app/src/forms/form/exportService.js
app/src/forms/form/routes.js

Currently only support exporting submissions in csv or json.
Can be filtered by minDate/maxDate.
Can specify the columns to return from the db query.
Will return only the data object of the full submission json
User must have 'form_read' to get to the API call, and when exporting submissions, must have 'submission_read'.
`/form/:formId/export?format=[csv or json]&type=submissions&minDate=2020-10-07T18:52:45.669Z&maxDate=2020-10-07T18:56:08.442Z&columns=formName&columns=createdAt&columns=email&columns=submission`
All query params are optional.
**type** defaults to 'submissions'
**format** defaults to 'csv'
**minDate** and **maxDate** are full timestamps (ex. 2020-10-07T18:52:45.669Z)
**columns** can be used to customize the data set.  These will need to be columns in the view (fields in …

Add export API for forms.

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/services/formService.js
app/frontend/src/store/modules/form.js
app/src/forms/form/exportService.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1617
Export submissions popup on the View Submissions page. Calls new api endpoint asking for CSV and downloads.
Some minor style tweaks upcoming but will wait until bootstrap stuff isn't overriding.
Tested on Chrome, FF, and iPad safari.

Export submissions UI

---

app/frontend/package-lock.json
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/services/formService.js
app/frontend/src/store/modules/form.js
app/src/forms/form/routes.js

Permissions were added to allow a user to view/read their submission, enforced in a simpler endpoint, FE just needed to be updated to use it.

Submission Read - update FE api call.

---

app/src/forms/form/routes.js
app/src/forms/rbac/routes.js

For first PROD release, we want to lock down some functions to only Keycloak CHEFS Admin users.
[SHOWCASE-1645](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1645)

Protect routes by CHEFS Admin role

---

app/frontend/README.md
app/frontend/package-lock.json
app/frontend/package.json
app/frontend/public/index.html
app/frontend/src/assets/scss/style.scss
app/frontend/src/components/designer/FormCreator.vue
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue

supports [work on styling the form ](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1608)
We need the form builder and the forms it creates to have the look and feel of the bcgov style guidelines.
not yet sure if there is a reasonable way to modify html markup produced by the form builder. 
so we can apply css/scss rules (similar to those in vuetify) to the formio markup.
The SASS @extend directive can be useful here.
long term approach could be:
- modify the html markeup produced by the formio form builder, so that each component has html elements (tags) and class names that can be styled using vuetify and our base stylesheet.
example:
bcgov prefers the 'description' text for a text input to appear above the field, but formio show it under the field.
formio use 'text-muted' to make …

Style form builder and rendered forms to match bc gov look/feel

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/assets/scss/style.scss
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue

inport bootstrap (Bootstrap-SCSS) 'globally' into our main stylesheet.
we can try and scope it later.

Load bootstrap-scss globally to fix style inconsistencies

---

app/src/docs/v1.api-spec.yaml
app/src/forms/auth/middleware/userAccess.js
app/src/forms/auth/service.js
app/src/forms/common/models/models.js
app/src/forms/form/routes.js

Will respect url param formId or query param formId.

Add formId filtering to currentUser middleware and /rbac/currentUser.

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/router/index.js
app/frontend/src/views/form/Preview.vue
app/frontend/src/views/form/Success.vue
app/frontend/src/views/form/View.vue

This PR does the following:
* Updates the submission success view to not show the navbar anymore.
* Add version to bottom of FormViewer
* Implement slot-based alert section for success notification
* Implement preview route functionality
[SHOWCASE-1637](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1637)
[SHOWCASE-1638](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1638)

Update submission success view

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/base/BaseNotificationBar.vue
app/frontend/src/components/base/BaseNotificationContainer.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/components/forms/ShareForm.vue
app/frontend/src/services/rbacService.js
app/frontend/src/store/modules/auth.js
app/frontend/src/store/modules/form.js
app/frontend/src/views/form/Manage.vue
app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
app/src/forms/common/models/models.js
app/src/forms/form/exportService.js
app/src/forms/form/service.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1640
Also 
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1641
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1642
New management UI and feature flag restrictions (must be CHEFS admin for some stuff).
Delete button not functional yet (hidden anyways).
Will add version history table at bottom at a later time with design changes.

Management UI update

---

app/frontend/src/components/designer/FormsTable.vue

This PR removes the version query from the link as it is no longer required.
[SHOWCASE-1630](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1630)

Drop version query parameter from launch button on My Forms page

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/main.js
app/src/forms/common/models/models.js

This is a meta-PR which will merge in #63 #65 and #66 .
[https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1630](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1630)

Bugfixes: Round 1

---

app/frontend/src/main.js

Prevent keycloak from breaking on the non-chromium version of Edge (see comment in code)
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1634
Can someone try Safari on this to be sure?

Old Edge fix

---

app/frontend/src/assets/scss/style.scss

fixes the color of the form builder submit buttons

style form designer and rendered form submit buttons

---

app/frontend/package-lock.json
app/frontend/src/assets/scss/style.scss
app/frontend/src/components/bcgov/BCGovHeader.vue
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/src/forms/form/exportService.js

Export Submissions Ordering on backend, proper mime type on frontend download.
[SHOWCASE-1657](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1657)
Some styling on Submissions dialog - Date Range outline, Radio button line height.
[SHOWCASE-1661](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1661)
Fix Header text alignment
[SHOWCASE-1667](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1667)
Add Timestamp to Submissions table
[SHOWCASE-1668](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1668)
Rebrand Basic Mode to Simple Mode for form designer
[SHOWCASE-1669](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1669)
Update Vuetify Checkbox and Radio Button label styles to correct vertical alignment
[SHOWCASE-1656](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-165 …

Export Submissions - ordering, UX changes

---

app/frontend/package-lock.json
app/frontend/src/assets/scss/style.scss
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/ShareForm.vue

- makes form share dialog close button , and heading more like other dialog boxes
- makes formio button component match other buttons on app
- make all disabled form fields in submission review mode have the same grey background
the 'manage', 'view submissions', 'launch' etc links on my forms table have a strange underline on hover.
can't for life of me fix that. might have to put in a different ticket
i've also found that my npm build times (triggered by hot-reloading) were getting quite slow. Not sure if it's because of my inefficient or greedy css rules. it seems the @extend rule slowed things down especially.
however, after rebooting my pc and now it doesnt seem slow.

Style fixes

---

app/frontend/src/components/designer/FormDesigner.vue

Update Form Designer Import logic.

---

README.md
app/frontend/src/assets/scss/style.scss

- show red borders on invalid input fields (previously overridden by mistake)
- remove red alert icon on invalid fields

more style fixes

---

app/frontend/src/views/form/Success.vue

For the COVID desk form (until we give the designer the ability to choose whether the confirmation message shows), make the wording to the user not seem mandatory.

Wording to make form confirmation ID optional for now

---

README.md
app/frontend/src/views/user/Root.vue
app/frontend/tests/unit/components/base/BaseCopyToClipboard.spec.js
app/frontend/tests/unit/components/base/BaseImagePopout.spec.js
app/frontend/tests/unit/components/base/BaseNotificationBar.spec.js
app/frontend/tests/unit/components/base/BaseNotificationContainer.spec.js
app/frontend/tests/unit/views/Form.spec.js
app/frontend/tests/unit/views/NotFound.spec.js
app/frontend/tests/unit/views/User.spec.js
app/frontend/tests/unit/views/form/Design.spec.js
app/frontend/tests/unit/views/form/Preview.spec.js
app/frontend/tests/unit/views/form/Submissions.spec.js
app/frontend/tests/unit/views/form/Submit.spec.js
app/frontend/tests/unit/views/form/Success.spec.js
app/frontend/tests/unit/views/form/Teams.spec.js
app/frontend/tests/unit/views/form/View.spec.js
app/frontend/tests/unit/views/user/Forms.spec.js
app/frontend/tests/unit/views/user/History.spec.js
app/frontend/tests/unit/views/user/Root.spec.js
app/jest.config.js
components/README.md
load-test/README.md
openshift/patroni.dc.yaml

This PR adds some frontend component/view unit tests to improve code coverage.
* Raises memory limits of persistent patroni
* Ignore coverage from db migrations and seeds folders
[SHOWCASE-1650](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1650)

Frontend Unit Test Additions

---

app/src/forms/auth/middleware/userAccess.js
app/src/forms/auth/service.js
app/src/forms/common/models/models.js
app/src/forms/common/utils.js
app/src/forms/form/controller.js
app/src/forms/form/routes.js
app/src/forms/form/service.js
app/src/forms/rbac/controller.js
app/src/forms/rbac/service.js
app/tests/unit/forms/common/utils.spec.js

Use DELETE /forms/:formId for delete, allows no confusion between update and delete.  
After discussions with the team, by default, we do not return deleted/inactive forms - treat as 404 if queried by id, do not return in lists.  The caller must be explicit in getting deleted forms.
Examples:
GET /forms:/formId?active=false is valid to retrieve an inactive form 
GET /forms:/formId/version?active=false is valid to retrieve an inactive form and current version
GET /forms?active=false is valid to return a list of invalid forms
GET /rbac/currentUser?active=false
We will leave the resurrection and management of deleted forms to CHEFS Admin users under the /admin API (TBD).
See [SHOWCASE-1724](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1724)
New feature (non-breaking change which adds …

API for form delete (soft).

---

app/src/forms/common/models/models.js
app/src/forms/user/service.js

Find user by a portion of name fields.
/api/v1/users?search=VALUE
Will search (OR) across email, fullName, and username fields.
Case insensitive, any portion of email/fullName/username fields.

Add new field (search) to user api

---

app/config/default.json
openshift/README.md

[SHOWCASE-1684](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1684)

Update default values and endpoints to OIDC

---

app/frontend/src/components/forms/AddTeamMember.vue
app/frontend/src/components/forms/TeamManagement.vue
app/frontend/src/services/index.js
app/frontend/src/services/userService.js
app/frontend/src/utils/constants.js
app/frontend/src/views/form/Teams.vue
app/frontend/tests/unit/utils/constants.spec.js
app/frontend/tests/unit/views/form/Teams.spec.js

Add Team Member component
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1729
..click 'Add a New Member' button on 'Team Management' page.
lets you search all users (that have ever logged in to the CHEFS) and insert one into the team table.
The new user wont persist to database until they have a role selected.
It's a start.. not perfect. 
- I wasn't sure of the best way to filter out the user with username: 'service-account-chefs'.
- Also, the concept (https://app.zeplin.io/project/5e7a37e64af623857819675b/screen/5fa1ead5d574658d5f591181) also shows a 'remove' member button. but it seems just deselecting all the roles does that.

Add Team Member component

---

app/frontend/src/components/bcgov/BCGovHeader.vue
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/AddTeamMember.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/ShareForm.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/TeamManagement.vue
app/frontend/src/views/form/Manage.vue
app/frontend/src/views/form/Submissions.vue
app/frontend/src/views/user/Forms.vue
app/frontend/tests/unit/views/form/Submissions.spec.js
app/frontend/tests/unit/views/user/Forms.spec.js

This PR implements the ability for Team Management panel to remove users.
* Add form owner protection logic
* Button style consistency pass
* Page Title/Action button consistency pass
* Add missing tooltips
* Disable submitter column when not in team mode
[SHOWCASE-1728](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1728)
[SHOWCASE-1749](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1749)

Remove Team Member Functionality and UX Consistency Pass

---

app/frontend/src/components/bcgov/BCGovHeader.vue

Get rid of BETA chip

---

app/frontend/src/components/base/BaseSecure.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/TeamManagement.vue
app/frontend/src/services/rbacService.js
app/frontend/src/views/form/Manage.vue
app/frontend/tests/unit/components/base/BaseSecure.spec.js
app/src/forms/auth/middleware/userAccess.js
app/src/forms/form/routes.js
app/src/forms/rbac/routes.js
app/src/forms/role/routes.js
app/src/forms/user/routes.js
app/tests/unit/routes/v1/rbac.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1708
Remove ADMIN blocks for form actions
Also:
Fix an issue where the checkbox-disabling logic was flipped on the Submitter column on Team Management (should be disabled for **non**-TEAM forms.
Removed Admin checks from BaseSecure. So you can still URL into a page where you can't do anything if you don't have the appropriate rights (like can go to Manage page), but this is fine for now since you can't read any data or do any action that you don't have rights for anyways (buttons are controlled by access rights, and of course the API is as well).
Could look into a more complex BaseSecure control later if we really want to present …

Allow non-admin form creation and management

---

app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/views/About.vue

supports: [https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1766](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1766)
add link to help (wiki)

add help link to navbar

---

.github/workflows/unit-tests.yaml
app/frontend/src/components/forms/TeamManagement.vue
app/frontend/src/store/modules/form.js
app/frontend/src/views/Form.vue
app/frontend/tests/unit/store/modules/auth.getters.spec.js
app/frontend/tests/unit/store/modules/notifications.mutations.spec.js

This PR adds more unit tests and implements github actions for unit tests
* Hides submitter column when form is not in team mode
[SHOWCASE-1764](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1764)

Add Github Actions, FE Unit Tests and conditional Submitter column hiding

---

app/frontend/src/components/bcgov/BCGovHeader.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue

included in [https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1766](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1766)
make header and navbar match design system.
- hide app title in header instead of small logo on mobile view
- just use one logo
- use padding either side of header and navbar (doesnt align with main content)
Mina has approved the ui for this PR.
This might not be an ideal solution but it does make layout of the header simpler on mobile. 🤷‍♂️ 

align navbar with main content

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/services/formService.js
app/src/forms/form/exportService.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1779
Show columned form data. For repeating grid sections/etc, this library prints 1 row per repeating item with other non-repeating fields duplicated (like a JOIN in SQL)
Also add a TBD `@customEvent` handler to the form viewer so we can leverage it in the future.

CSV export format change

---

openshift/app.bc.yaml

Switch BC to pull from docker.io with our account (secret in tools namespace) to avoid the limits.

Use docker.io

---

app/frontend/src/components/forms/manage/ManageVersions.vue

Removing export design column from version table.

Remove export

---

app/README.md
app/frontend/src/components/designer/FormDesigner.vue
openshift/README.md

supports [https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1803](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1803)
- hide file upload component from list of available components in form builder.. for public forms.
if a form already contains an uploader and switches to become public, the component remains in the form but wont work because file upload requires an authenticated user's oidc bearer token with upload request. 
- the file upload component was developed by Jason in PR https://github.com/bcgov/common-hosted-form-service/pull/95

hide file upload component on public forms

---

README.md
app/src/docs/v1.api-spec.yaml
app/src/forms/form/routes.js
app/src/forms/rbac/routes.js
app/tests/unit/routes/v1.spec.js
app/tests/unit/routes/v1/form.spec.js

spec for backend API
- should now have all the paths except the new ones for /admin and /files
- may want to change the way the endpoints are grouped in the left nav using 'tags' (having an endpoint in multiple groups seems to cause jumping around between sections)
- there's a couple more endpoints that we aren't using, because we're now doing things differently (deprecated for our purposes) or they aren't yet required (like PUT /submission/id)
- we could look at maybe re-ordering and adding a few more comments to routes in each route file and puting deprecated routes at the bottom 🤷‍♂️ 

V1.0.0 API spec

---

Jenkinsfile
Jenkinsfile.cicd
README.md
app/package-lock.json
openshift/commonPipeline.groovy

This PR implements OCP4 specific changes in preparation for migration.
- Change post-success comment to point at deployed PR location
- Add project lifecycle badge (#114)
[SHOWCASE-1822](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1822)
This PR will be the last deployment on OCP3.

Prepare for OCP4 Migration

---

openshift/app.dc.yaml
openshift/patroni-ephemeral.dc.yaml
openshift/patroni.dc.yaml
openshift/patroni.secret.yaml

This PR implements OCP4 specific NSP manifests. This is needed in order to deploy on OCP4. OCP4 Topology labels and annotations were also added.
[SHOWCASE-1823](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1823)
This PR will not deploy to any cluster.

Implement OCP4 Changes

---

app/frontend/src/components/base/BaseInfoCard.vue

To match mockups per UX request.
<New feature (non-breaking change which adds functionality)

Info card style

---

app/frontend/src/components/forms/manage/TeamManagement.vue

[https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1853](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1853)
not sure if this is the best solution in terms of UX but sounds like it's been approved.
I'll send Mina/Chris a link to review.
This template code/logic is getting quite complicated.
also i can remove the comments if you want.

Team management show roles on hover

---

app/frontend/src/components/base/BaseDialog.vue
app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/manage/ManageForm.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/components/base/BaseDialog.spec.js
app/src/db/migrations/20210100113516_010-alter-form-view.js
app/src/forms/auth/service.js
openshift/app.dc.yaml

ticket [https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1854?](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1854?)
concept: https://app.zeplin.io/project/5e7a37e64af623857819675b/dashboard?sid=5ff76e14a0ef746d5e8007f9
notes:
- deleted app and db from openshift and redeployed, db migration was failing with error: 'cannot drop columns from view'. turns out i wasnt 'altering' the latest version of the view.. and that additional columns need to be added to the end of the list of selected columns. 🤦 
- I've kept left the form title and chat icon as primary, we can update all link colors to match Mina's concepts in another ticket
- updated the base dialog component with an 'X' close button
- On the Manage Form page, when the settings accordion is collapsed it could probably do with …

Form Organization tweaks - ticket 1854

---

app/src/docs/v1.api-spec.yaml
app/src/forms/admin/controller.js
app/src/forms/admin/routes.js
app/src/forms/admin/service.js
app/tests/unit/routes/v1/admin.spec.js

Docs for admin and file upload endpoints. Will leave this PR here and move it forward since these are existing endpoints. New docs for status endpoints will come with those PRs.
Also remove an unused endpoint.
Removed the PUT on `/admin/formusers`. Not called and too broad (can set all forms all users). If ever needed from admin portal should make a more targeted one to a specific form/user.

Admin and file endpoint api specs

---

Jenkinsfile
Jenkinsfile.cicd

Jenkins stage replays failed to work because the common pipeline was only being loaded in initialize stage. This PR fixes that.

Update pipeline to support stage replays

---

app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/store/modules/form.js
app/frontend/src/views/form/Manage.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1915
Settings was not displaying the IDP correctly, always showing TEAM.
Found this was because the form fetch condition was not actually being called in this component, and was not needed since the form is in state already from the parent. Refactored a little to fix this.

Unused form fetch in settings

---

app/frontend/src/views/About.vue

video is stored in CHEFS wiki/videos directory.
powerpoint media 'reduced' to 720p.
powerpoint exported to video
video didnt play well on VLC (the slide transitions were all messed up)
added to a new video project in the windows 'photos' app and re-exported as MP4.
.. seems to play ok
(i did try compressing further using VLC's convert feature but it made the video crackly and choppy on some browsers).
it's not the greatest video but it's better than the one we have..
video exported from powerpoint

new video on about page

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/components/designer/FormViewer.vue
app/package-lock.json
app/package.json
app/src/routes/v1.js

This PR ensures that forward building from package.json on frontend yields an aligned package-lock.json.
- Explicitly pin formiojs to version 4.11.3 on frontend
- Routine npm security package updates
- Update js-yaml api call signatures
[SHOWCASE-1741](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1741)

Realign frontend package.json dependencies

---

app/src/forms/email/emailService.js

supports: [https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1902](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1902)

Use a unique and valid sender address for notifications

---

app/frontend/jest.config.js
app/frontend/package.json
app/frontend/src/store/index.js
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/store/index.spec.js
app/frontend/tests/unit/store/modules/admin.getters.spec.js
app/frontend/tests/unit/store/modules/admin.mutations.spec.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/frontend/tests/unit/store/modules/form.getters.spec.js
app/frontend/tests/unit/store/modules/form.mutations.spec.js
app/frontend/tests/unit/store/modules/notifications.actions.spec.js
app/frontend/tests/unit/store/modules/notifications.mutations.spec.js
app/frontend/tests/unit/utils/permissionUtils.spec.js
app/frontend/tests/unit/views/Admin.spec.js
app/frontend/tests/unit/views/form/Submit.spec.js
app/package.json

This PR improves frontend coverage. Specifically the following areas:
- permissionUtils
- Submit
- vuex getters
- vuex mutations
- partial vue actions
[SHOWCASE-1650](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1650)

Improve Frontend Test Coverage

---

app/frontend/src/components/forms/manage/ManageVersions.vue
app/frontend/tests/unit/store/modules/form.actions.spec.js

supports ticket: [https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1942](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1942)
- show 'Created Date' and 'Created By' columns in the versions table
updated date wasnt helpful because publishing one version updates all version updatedAt timestamps.
because we dont have a proper history of actions decided best to just show created dates for now.

show created date and by on versions table

---

Jenkinsfile
Jenkinsfile.cicd
app/config/default.json
app/package-lock.json
components/package-lock.json
load-test/README.md
load-test/config/default.json
load-test/submissions/kitchen_sink_advanced_submission.json
load-test/submissions/kitchen_sink_no_sig_submission.json
openshift/README.md

- Update all pathfinder references to apps.silver.devops
[SHOWCASE-1966](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1966)

Update CHES endpoint URL to OCP4

---

app/src/db/migrations/20210129120337_012-submission-status.js

Migration was unable to run against dev with lots of submission records, this works against a backup of that db locally.

raw query so migration will run

---

app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/components/forms/submission/StatusPanel.vue
app/src/forms/auth/middleware/userAccess.js
app/tests/unit/forms/auth/authService.spec.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

Unit tests for permission middleware.
Help text on status

Unit tests for middleware and text change

---

app/app.js
app/frontend/src/components/bcgov/BCGovHeader.vue
app/src/forms/auth/middleware/userAccess.js
app/src/forms/auth/service.js
app/src/forms/form/service.js
app/src/forms/submission/routes.js
app/src/forms/submission/service.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js
app/tests/unit/routes/v1/submission.spec.js

New middleware to check SUBMISSION permissions on route. This is to prep for all our submission edit workflow work and fixes the bug in https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1986.
Include logging (kube probe) change too.
Bug fix (non-breaking change which fixes an issue) 

New submission permission middleware

---

app/frontend/src/store/index.js
app/src/forms/form/service.js

- Bugfix: Ensure public forms do not record logged in username data
- Add Vuex logger to non-production environments
[SHOWCASE-1945](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1945)

Ensure public forms do not record logged in username data

---

app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/manage/ManageFormActions.vue
app/frontend/src/utils/constants.js
app/frontend/src/utils/permissionUtils.js
app/package-lock.json
app/src/forms/form/service.js
components/package-lock.json

supports ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1629
- added 'view all submissions' link on individual submission view page
- added 'manage form' link on 'submissions table' page
- added 'view all submissions' link on 'manage form' page
- tried a different icon for 'submissions'
- removed default SUBMISSION_DELETE permission for submitter
this feels a bit half-baked. not sure i'm checking permissions the best way.
there's a bit of code duplication. did consider having a 'navigation' component. that could be used something like this:
<FormNavigation links="['manage_form', 'manage_team', export_submissions'] />
depends how much we want to restructure stuff.

Add extra local navigation links on the UI for a form

---

app/app.js
app/frontend/src/components/forms/manage/AddTeamMember.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/package-lock.json
components/package-lock.json

- Only reset DB connections if it is a 5xx class error
- Ensure that only users with team_update can view and edit TeamManagement page
[SHOWCASE-2043](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2043)

DB and Team Management bugfixes

---

app/src/db/migrations/20210519170000_015-alter-submission-data-vw.js
app/src/docs/v1.api-spec.yaml
app/src/forms/form/exportService.js

ticket: [Add status and other meta info to submissions export](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2037)
- db migration 015 does: 
- adds extra columns 'status', 'assignee' and 'assigneeEmail' to the 'submissions_data_vw' view.
- adds these columns to the underlying 'submissions_vw' view , also select 'submission status created at' 
- pull status related fields from submissions_data_vw if status feature is enabled on form
- restructure export data so headers are like `form.confirmationId`, ..., `formFieldA`

add extra meta columns to submissions export

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/components/forms/submission/UserSubmission.vue
app/frontend/src/router/index.js
app/frontend/src/services/rbacService.js
app/frontend/src/store/modules/form.js
app/frontend/src/utils/permissionUtils.js
app/frontend/src/views/About.vue
app/frontend/src/views/admin/Root.vue
app/frontend/src/views/form/Submissions.vue
app/frontend/src/views/form/Submit.vue
app/frontend/src/views/form/Success.vue
app/frontend/src/views/user/SubmissionView.vue
app/frontend/src/views/user/Submissions.vue
app/frontend/tests/unit/services/rbacService.spec.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/frontend/tests/unit/utils/permissionUtils.spec.js
app/src/db/migrations/20210528134214_016-submission-submitters-vw copy.js
app/src/forms/common/models/models.js
app/src/forms/email/emailService.js
app/src/forms/rbac/controller.js
app/src/forms/rbac/routes.js
app/src/forms/rbac/service.js
app/tests/unit/routes/v1/rbac.spec.js

Submission history for particular form.
As a **submitter** on the form page, and the success page you will have a view submissions icon in the top right. This will show you **your** submissions to that form.
- status columns show for forms with status enabled
- public forms do not have this ability
- email has a link back to the form history view

user submission view

---

app/src/forms/email/assets/bodies/send-status-assigned-email-body.html
app/src/forms/email/assets/bodies/submission-confirmation.html
app/src/forms/email/assets/bodies/submission-received-confirmation.html
app/src/forms/email/assets/triggered-notification-email-template.html
app/src/forms/email/emailService.js
app/src/forms/submission/controller.js
app/tests/unit/forms/email/emailService.spec.js
app/tests/unit/forms/submission/controller.spec.js

Consolidating all of the different reasons for sending an email from CHEFS into a single function. Also changed the Title for status changed emails to include the form name.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2007
Refactored code introduces more efficient ways of handling emails being sent out from CHEFS. It also allows for developers to more simply add their own email types by having an interchangeable body content section in their emails while retaining the same wrapper template for the emails.

Email Service Refactor

---

app/frontend/component-update.js
components/src/components/SimpleContent/Component.ts

Edit the Custom Content Component in FormIO Making <a> tags open links in new tab instead of trying to redirect the current page.
Added the "target='_blank'" attribute to all <a> tags.

Making Links Open in new Tab

---

components/src/components/SimpleContent/Component.ts

This reverts commit bef8a999bb00100f694b0136efd6c144493f0176, reversing
changes made to 1ee0e430543e4cf331f87386be8a9f75b86f8eeb.
One of the forms in production stopped working with the introduction of this PR. Rolling back changes for now.

Revert "Merge pull request #187 from MichaelChung123/dev-1765"

---

app/frontend/src/components/base/BaseCopyToClipboard.vue
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/manage/AddTeamMember.vue
app/frontend/src/components/forms/manage/ManageFormActions.vue
app/frontend/src/components/forms/manage/ShareForm.vue
app/frontend/src/components/forms/submission/AuditHistory.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/components/forms/submission/StatusPanel.vue
app/frontend/vue.config.js

- Enable gzip compression for webpack dev server
- Ensure share link warning appears when no forms are published
- Make v-alert styles more consistent across the app (transitions, primary/info color)
- Add help text alert while editing submission (staff side)
- Update user search drop down value text when no data available
- Change submission list icon to list_alt
- Fix copy to clipboard button and snackbar consistency
- Add missing tooltips to view action button
- Change export/download icon to match other export buttons
- Update assignment label text to be more precise
- Disable Status and Notes panel when editing submission (staff side)
[SHOWCASE-2106](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2106)

General Usability Bugfixes

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue

Allows the embeded links from video sites such as YouTube to be seen in the Component Details Preview View, Builder View, Preview View and Submitter View.
Added to the options objects in the FormDesigner and FormViewer components to allow iframe tags to be visible on load from FormIO.

adding options to display embeded video iframes

---

app/frontend/src/App.vue
app/frontend/src/assets/scss/style.scss
app/frontend/src/components/base/BaseAuthButton.vue
app/frontend/src/components/base/BasePrintButton.vue
app/frontend/src/components/bcgov/BCGovFooter.vue
app/frontend/src/components/bcgov/BCGovHeader.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/views/Admin.vue
app/frontend/src/views/Form.vue
app/frontend/src/views/User.vue
app/frontend/src/views/form/Success.vue
app/frontend/src/views/form/View.vue
app/frontend/tests/unit/components/base/BasePrintButton.spec.js
app/frontend/tests/unit/views/Form.spec.js
app/frontend/tests/unit/views/form/Success.spec.js

This PR adds a QoL Print button and some minor code cleanup and consolidation.
[SHOWCASE-1991](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1991)

Add Print Button

---

app/frontend/component-update.js
app/frontend/src/components/designer/FormViewer.vue
components/src/components/SimpleContent/Component.ts

Fixing issue with PR #187. Issue caused with conditional rendering of Static Content.
Moved the previous logic for the SimpleContent into a constructor block instead of the built in attach method.
Will be doing a QA screen in Test env to confirm it is safe before merging.

Static Text Fix (Redux)

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/views/form/Manage.vue

Letting the Form's Title header span the  entire width of it's container.
Adding Vuetify bootstrap grid changes.

Form Header Title Width Fix

---

app/frontend/src/components/forms/FormSubmission.vue

Fixing Header alignment issues on Submission View page. Also fixed Header Icons showing up in Print View.

Submissions

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/services/formService.js
app/frontend/tests/unit/services/formService.spec.js
app/src/forms/form/exportService.js

[ticket 2113](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2113)

exclude 'deleted' and 'draft' submissions from export

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/utils/transformUtils.js

Making links open in a new tab for Submission Draft View.
Re-structured the function to attach attributes, and moved functionality into lifecycle method in the Component.

Draft link refactor

---

app/frontend/src/components/base/BaseNotificationContainer.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/designer/FormViewerActions.vue
app/frontend/src/components/forms/submission/ManageSubmissionUsers.vue
app/frontend/src/components/forms/submission/NotesPanel.vue
app/frontend/src/services/rbacService.js
app/src/docs/v1.api-spec.yaml
app/src/forms/common/models/models.js
app/src/forms/rbac/controller.js
app/src/forms/rbac/routes.js
app/src/forms/rbac/service.js
app/tests/unit/forms/rbac/controller.spec.js
app/tests/unit/routes/v1/rbac.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1987
Manage users on a submission.
Form must be login-type, and enable the draft setting on form settings.
When form is a draft, you can add/remove other users to the specific draft. When it's submitted you can view it.
2 new submission-based RBAC endpoints

Manage Submission Users

---

app/frontend/src/components/designer/FormsTable.vue

Fixing the squishing of the Action Button on the My Forms Table.
Made a vuetify table header change on FormsTable.vue

changing column width for form table

---

openshift/README.md
openshift/app.dc.yaml
openshift/fluent-bit.cm.yaml

Supports [ticket 2123](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2123) and the overall goal of pushing our app logs to 1Team's ElasticSearch/Kibana stack.
update fluent-bit version

Make http logs match ECS compatible in Fluent-bit

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/components/forms/submission/DeleteSubmission.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/views/form/Manage.vue
app/src/db/migrations/20210716000000_018-alter-submission-submitters-add-updatedAt.js

Made a few QOL changes to the Draft Submissions.
Making the following Draft Submission Fixes:
- Added Warnings when leaving the Draft Submissions Pages
- Fixed header action button placement to be consistent with other pages with Header Action Buttons
- Added the Draft Last Edited column to the Draft Submissions Table
- Removed the Completed Date column from the Draft Submissions Table
- Spacing fix for the Delete Action Button for the Draft Submission Table Action Icons
JIRA Ref:
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2130

Draft Submissions Changes

---

components/src/components/OrgBook/Component.ts

Point the new V3 Orgbook to our FormIO Orgbook component.
- Changed the url to point to Orgbook v3.
- Pointing the new response structure to the title values

Directing Orgbook calls to V3

---

app/frontend/src/components/base/BasePanel.vue
app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/views/form/Create.vue

Re-style settings area
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2161
Added a BasePanel to match the bootstrap style panels as v-cards.

Settings UI

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/base/BaseCopyToClipboard.vue
app/frontend/src/components/base/BaseNotificationBar.vue
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/RequestReceipt.vue
app/frontend/src/components/forms/manage/ManageForm.vue
app/frontend/src/components/forms/manage/ShareForm.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/components/forms/submission/DeleteSubmission.vue
app/frontend/src/components/forms/submission/ManageSubmissionUsers.vue
app/frontend/src/components/forms/submission/NotesPanel.vue
app/frontend/src/store/modules/admin.js
app/frontend/src/store/modules/form.js
app/frontend/src/store/modules/notifications.js
app/frontend/src/utils/constants.js
app/frontend/tests/unit/components/base/BaseCopyToClipboard.spec.js
app/frontend/tests/unit/components/base/BaseNotificationBar.spec.js
app/frontend/tests/unit/store/modules/notifications.actions.spec.js
app/frontend/tests/unit/utils/constants.spec.js

In order to line up with the BCGov Standards, we are changing the global styles for all of the Notifications (v-alert calls in the Vue Components) and Alerts (Call to get a v-alert notification that appears at the top of the screen) to be consistent with their styles.
BCGov Styling:
https://developer.gov.bc.ca/Design-System/Alert-Banners
JIRA Ticket:
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2126
- Changes to global style.scss file for Vuetify v-alert components
- Changed constants.js file to contain all the different notification type properties (warning, error, success, info)
- Changes to BaseNotificationBar.vue to accept the constant values for the new styles

Changing global styling for Notifications & Alerts

---

app/frontend/src/components/forms/manage/ApiKey.vue
app/frontend/src/components/forms/manage/ManageForm.vue
app/frontend/src/store/modules/form.js
app/package-lock.json
app/package.json
app/src/docs/docs.js
app/src/docs/v1.api-spec.yaml
app/src/forms/auth/middleware/apiAccess.js
app/src/forms/auth/middleware/userAccess.js
app/src/forms/form/routes.js
app/src/forms/form/service.js
app/src/forms/submission/routes.js
app/tests/unit/forms/auth/middleware/apiAccess.spec.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js
app/tests/unit/routes/v1.spec.js
components/package-lock.json

This PR introduces support for handling API level access using the Basic Auth security pathway. It also does some minor cleanup with the existing authentication middleware to prevent some potential error cascade situations.
- Enables the API panel on Form Mange page
- Backfill OpenAPI docs with missing API documentation
[SHOWCASE-2163](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2163)
This PR will complete the round trip capability of allowing third party users to generate and manage their API keys for their form an access the CHEFS API for their own needs.
Check …

Implement Dual-Auth stack to support Basic API Auth on certain /forms endpoints

---

app/frontend/src/components/forms/ColumnPreferences.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/services/formService.js
app/frontend/src/services/userService.js
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/services/userService.spec.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/frontend/tests/unit/store/modules/form.getters.spec.js
app/frontend/tests/unit/store/modules/form.mutations.spec.js

**Don't merge after review**
Staff submissions table column preference saving.
Will `v-if` hide this after review and another PR will adjust fetching query.

Column prefs

---

app/frontend/src/components/base/BaseCopyToClipboard.vue
app/frontend/src/components/forms/manage/ShareForm.vue

Add a link to pop the share URL open in another screen

Share modal - open form link

---

app/src/components/log.js
openshift/README.md
openshift/app.dc.yaml
openshift/fluent-bit.cm.yaml

Supports tickets:
- [2123 - Fluentbit to Elkstack](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2123) 
- [2190 - configure access to AWS OpenSearch](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2190)
and the overall goal of pushing our app logs to 1Team's ElasticSearch/Kibana stack.
As requested by Clecio, we should add some fields to match the [Elastic Common Schema](https://www.elastic.co/guide/en/ecs/current/ecs-getting-started.html#_translating_data_sources) format.
So we now have records (tagged with 'app.http') outputting to AWS 
A further parser for our logs was added to a node app running on an AWS Lambda service here:
[our 'Node CSS Parser' willl exist here](https://github.com/BCDevOps/nr-elasticsearch-stack/tree/master/event-stream-processing/src)
the AWS …

format logs for AWS OpenSearch

---

app/frontend/src/components/forms/ColumnPreferences.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/store/modules/form.js
app/src/db/migrations/20210830170000_021-alter-submissions-vw.js
app/src/forms/form/service.js

Fetch and filter submission data to selected columns stored in prefs.

Column selection on submissions

---

app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/PrintOptions.vue
app/frontend/src/components/forms/RequestReceipt.vue
app/frontend/src/components/forms/submission/StatusPanel.vue
app/frontend/src/components/forms/submission/StatusTable.vue
app/frontend/src/services/formService.js
app/frontend/tests/unit/services/formService.spec.js
app/src/docs/v1.api-spec.yaml
app/src/forms/submission/controller.js
app/src/forms/submission/routes.js
app/tests/unit/forms/submission/controller.spec.js

https://apps.nrs.gov.bc.ca/int/jira/secure/RapidBoard.jspa?rapidView=2025&projectKey=SHOWCASE&view=detail&selectedIssue=SHOWCASE-2191
- Added a new modal in the FormViewer Component when clicking on the Print button which allows users to upload a template and download it to a PDF.
- Changed the API to call the cdogsService to perform the template merge.
New feature (non-breaking change which adds functionality) 
1. Added new modal when clicking the print button. This modal allows you to print normally or upload a template.
2. Changed the API to accept the templates being uploaded.

Add export pdf to Submissions

---

app/frontend/src/components/designer/FormViewer.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2213
Fix a couple bugs related to validation and submission
1. Forms were POSTing to the API even though validation was failing
2. On draft forms trying to submit, then going back in and hitting cancel on the modal submitted the form
Reordered at what point the api post occurs in the formio event stack, added our own error notification.
https://help.form.io/developers/form-renderer#form-events

Reorg event flow to handle validation

---

app/frontend/src/components/admin/AdminFormsTable.vue

Fixed the logic of the v-data-table for the Admin Form Table. The table is now able to sort by date properly when you click the arrow beside the column's header. The same logic has also been applied to the "Deleted" column for this table.
This change was made to allow for consistency for all the tables in our application and to allow the user to sort by date when viewing the table.
Made changes to the v-data-table component to allow for it to sort it's date values.

Admin Form Table Sort

---

app/src/forms/form/service.js

When deleting a form, remove the API key if there is one
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2242
Tested 
- Deleting forms with API keys (check if gone)
- Deleting forms without API keys
- Restoring forms for both after delete

Remove an api key if it exists

---

app/frontend/src/components/admin/AdministerForm.vue
app/frontend/src/components/admin/Developer.vue
app/frontend/src/services/adminService.js
app/frontend/src/store/modules/admin.js
app/src/docs/v1.api-spec.yaml
app/src/forms/admin/routes.js

Adding user information to the form/admin page.
Attached the backend to make a call to the admin/service layer to display user data on the frontend.

Admin Form Users

---

app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/StatusPanel.vue
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/src/db/migrations/20211027000000_024-add-revising.js
app/src/docs/v1.api-spec.yaml
app/src/forms/common/constants.js
app/src/forms/email/assets/bodies/send-status-revising-email-body.html
app/src/forms/email/emailService.js
app/src/forms/form/service.js
app/src/forms/permission/service.js
app/src/forms/submission/controller.js
app/src/forms/submission/service.js
app/tests/unit/forms/email/emailService.spec.js
app/tests/unit/forms/submission/controller.spec.js
app/tests/unit/forms/submission/service.spec.js
app/tests/unit/routes/v1/submission.spec.js

Creating the return to user feature on the submission page. You should be able to set a "Revising" status to the submission and assign a user's email to send a request to revise the submission with an optional comment.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2122
This is a new feature to allow users to send a notification through email to other users to revise the submission.
- Frontend changes to add the revising status option with the appropriate form changes.
- Refactored the emailService to add this new revising option but also improve efficiency
- Added tests accordingly and fixed tests to the refactor

Return to User

---

app/src/forms/permission/service.js
app/src/forms/rbac/service.js

Guard against attempting to insert blank arrays in Objection (in places where this is possible).
This used to be an ok thing to do but library update now throws an exception if you insert [].

Prevent insert attempts on blank arrays

---

app/frontend/src/components/admin/AdministerForm.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2302
Version table on admin page wasn't displaying anything.
Was setting object reference for local form details object to the form from the store, then deleting a field on that (for intended display purpose), but needed to assign to new object instead.
Test form here https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-262/admin/form?f=c5a0971b-6f33-4d66-90b5-16e2d63e515a 
Bug fix (non-breaking change which fixes an issue) 
```
this.formDetails = this.form;
delete this.formDetails.versions;
```
Will delete `versions` from the original `this.form` object as it's a reference assignment
Need to do a (copy/clone/whatever you want to call it) object assignment.
```
this.formDetails = { ...this.form };
delete this.formDetails.versions;
```
Also …

Admin Versions table object assign fix

---

app/src/forms/form/service.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2312
422 due to formId not being provided to UPDATE call.

API key regen fails (Missing formId in UPDATE)

---

app/frontend/src/components/forms/submission/ManageSubmissionUsers.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2241
Pass the submission form IDP to the user search endpoint to restrict the search when adding team members to a submission.

Submission team search should just be allowed IDPs

---

app/frontend/src/components/bcgov/BCGovNavBar.vue

Adds a link to our Fider instance in the CHEFS NavBar

feat: Add Feedback Tab in Navbar

---

app/frontend/src/components/forms/submission/MySubmissionsActions.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/components/forms/submission/StatusPanel.vue
app/frontend/src/store/modules/form.js

When selecting Revising option, the Recipient Email textbox now populates with the Submitter's email address.
Ref: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2297?
Made changes to the StatusPanel Component on the Front End to make a call to the rbacService to filter the response and grab the submission owner's email.

Populating Recipient Email

---

app/frontend/src/components/forms/PrintOptions.vue

Link to help about browser printing.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2281
Link goes to here https://github.com/bcgov/common-hosted-form-service/wiki/Browser-Print

Print help link

---

app/frontend/src/components/forms/ColumnPreferences.vue
app/frontend/src/components/forms/SubmissionsTable.vue

Removes submission list headers if their name was changed in a newer form version.
[https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2377](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2377)
This will also remove the invalid column from the stored preferences the next time the user updates their prefs.

Remove submission list headers if their name was changed

---

.github/workflows/codeql-analysis.yaml
README.md
SECURITY.md
app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/components/forms/PrintOptions.vue
app/frontend/src/views/About.vue
app/frontend/tests/unit/views/About.spec.js

ticket : https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2427
new content: https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=109189105
..tidy up the CHEFS about page.
- remove those two smaller videos that were out of date
- provide more informative wording at top of page
- updated a couple of broken links to the wiki

About page content update

---

app/frontend/src/components/forms/submission/StatusPanel.vue
app/src/docs/v1.api-spec.yaml
app/src/forms/common/utils.js
app/src/forms/email/assets/bodies/submission-completed.html
app/src/forms/email/emailService.js
app/src/forms/submission/controller.js
app/tests/unit/forms/email/emailService.spec.js
app/tests/unit/forms/submission/controller.spec.js

When an admin sets a submission to Completed, it sends a confirmation email to the submission user.
Made changes to the StatusPanel and emailService to detect when an admin is trying to set the status for a submission to Completed.

Completed Status Email Notification

---

app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/views/Login.vue
openshift/app.bc.yaml
openshift/app.dc.yaml
openshift/fluent-bit.cm.yaml
openshift/patroni-ephemeral.dc.yaml
openshift/patroni.dc.yaml
openshift/patroni.secret.yaml

Enables BCeID Business logins.

Enable BCeID Business login

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/components/admin/AddOwner.vue
app/frontend/src/components/admin/AdministerForm.vue
app/frontend/src/services/adminService.js
app/frontend/src/store/modules/admin.js
app/frontend/src/utils/constants.js
app/frontend/tests/unit/components/admin/AddOwner.spec.js
app/frontend/tests/unit/services/adminService.spec.js
app/frontend/tests/unit/store/modules/admin.actions.spec.js
app/frontend/tests/unit/utils/constants.spec.js
app/src/docs/v1.api-spec.yaml
app/src/forms/admin/controller.js
app/src/forms/admin/routes.js
app/tests/unit/routes/v1/admin.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2616
Add a section in the [CHEFS Admin portal](https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-286/admin/) (for operational admins, needs the showcase team KC group to access) to add additional owners to a form.
Should only be used in the case where a form team person contacts us needing to add someone else to manage their forms when the original owner is no longer reachable. Otherwise they should use self-serve team management features if possible.
**Frontend**
From admin go into the form and at the bottom there's this form
Could be a user search but to keep it light just having the admin enter the direct user primary key. This feature is just being used by common service team admins and they can easily find the user id on the USER …

Administrative section to add an owner

---

app/frontend/src/views/About.vue

Updates the video on the About page to use a YouTube embeded version. Also includes a new blurb and link to the quickstart training videos,

Update About video and add link to training videos

---

.dockerignore
.github/actions/build-push-container/action.yaml
.github/actions/deploy-to-environment/action.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/on_pr_closed.yaml
.github/workflows/on_pr_opened.yaml
.github/workflows/on_push.yaml
.github/workflows/unit-tests.yaml
Dockerfile
openshift/app.dc.yaml

This PR implements a completely refactored CI/CD pipeline based on Github Actions. Key behaviors:
- Builds and publishes container images to ghcr.io
- Fully leverages github environments for oc cli deployments
- Change deployment preHook to retry until timeout instead of hard failing
- Extract dockerfile from app.bc.yaml manifest
- Disables fluent-bit sidecar container
[SHOWCASE-2750](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2750)

Implement Github Actions CI/CD Pipeline

---

.github/workflows/on_pr_closed.yaml
.github/workflows/on_pr_opened.yaml
.github/workflows/on_push.yaml

[SHOWCASE-2754](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2754)

Prevent workflows from running in parallel

---

openshift/caddy-reverse-proxy.dc.yaml

This manifest is manually implemented in order to facilitate domain
transitions and redirections.
[SHOWCASE-2721](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2721)

Add Caddy Redirect template manifest

---

SECURITY.md
app/frontend/src/components/base/BaseSecure.vue
app/src/docs/CHEFS_API_Documentation.postman_collection.json
app/src/docs/v1.api-spec.yaml
components/package.json

This PR formally marks the transfer of ownership from the CSS team to the Forminators team. Contact emails and names are updated in this PR.
[SHOWCASE-2774](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2774)

Transfer project ownership from CSS to Forminators

---

COMPLIANCE.yaml

Forms 384 pia status update

---

.gitignore
app/frontend/src/views/About.vue

- Changed the URL for the "Take a tour of CHEFS" video on the landing page
- Changed the URL for the "CHEFS How-to Videos" on the landing page
Bug fix (non-breaking change which fixes an issue) 
- [X ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [X ] I have checked that unit tests pass locally with my changes
- [X ] I have run the npm script lint on the frontend and backend
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] I have added necessary documentation (if appropriate)

Ayobami forms 45 update landing page video

---

app/frontend/.env
app/frontend/.env.development
app/frontend/.env.test
app/frontend/src/components/base/BaseSecure.vue

Better way to import contact info

update .env files to create a configurable contact variable

---

app/README.md
app/frontend/.env
app/frontend/.env.development
app/frontend/.env.test
app/frontend/README.md
app/frontend/src/components/base/BaseSecure.vue

Introduces a new environment variable for the team's contact email and update's the frontend README.md
Introduces a Vue environment variable VUE_APP_CONTACT which is displayed on an Error 401 Unauthorized Access page.
It enhances how the contact information is rendered within the app.

Configurable contact info variable using Vue .env files and README update

---

.github/actions/deploy-to-environment/action.yaml
app/config/custom-environment-variables.json
app/frontend/.env
app/frontend/.env.development
app/frontend/.env.test
app/frontend/README.md
app/frontend/src/main.js
app/frontend/vue.config.js
openshift/README.md
openshift/app.bc.yaml
openshift/app.dc.yaml

When checking the actual PR deployment, we can see in the console an Unexpected token '<' error in the file app.e898c519.js . When trying to open that js file we find that inside contains some HTML instead of JS.
In the network tab, the requested URL is from https://chefs-dev.apps.silver.devops.gov.bc.ca/app/js/app.e898c519.js it should be https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-308/app/js/app.e898c519.js. It’s trying to load a file that does not exist.
The issue stopping us from using the path submit.digital.gov.bc.ca/pr-308 instead of submit.digital.gov.bc.ca/app is because we can't get that base/public path since it's happening before the config file is loaded. The best alternative I could find was to use an environment variable for this instance.
Bug fix (non-breaking change …

Fix pr deployments

---

.github/actions/build-push-container/action.yaml

Switch to use the environment variables

Fix pipeline build error on line 42

---

.github/actions/build-push-container/action.yaml
app/frontend/src/views/About.vue

Fix landing video URLs not working in PR environment
Switch over to environment variables instead of config

Fix PR environment error

---

.github/actions/build-push-container/action.yaml
app/frontend/.env
app/frontend/.env.development
app/frontend/.env.test
app/frontend/src/views/About.vue

switch over to environment variables instead of config

remove spaces around environment variables

---

.github/actions/build-push-container/action.yaml

Switch over to environment variables instead of config

fix input values for landing page videos urls

---

app/frontend/.env
app/frontend/.env.development
app/frontend/.env.test

Stopped tracking .env File

---

app/frontend/src/views/About.vue

switch over to environment variables instead of config

Ayobami forms 45 update landing page video 

---

.github/pull_request_template.md
app/frontend/src/components/base/BaseDialog.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/forms/manage/ManageVersions.vue
app/frontend/src/main.js
app/frontend/src/store/modules/auth.js
app/frontend/src/store/modules/form.js
app/frontend/src/views/form/Create.vue
app/frontend/src/views/form/Design.vue
app/frontend/tests/unit/components/designer/FormDesigner.spec.js
app/frontend/tests/unit/store/modules/auth.actions.spec.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/frontend/tests/unit/store/modules/form.getters.spec.js
app/frontend/tests/unit/store/modules/form.mutations.spec.js
app/frontend/tests/unit/views/form/Create.spec.js
app/frontend/tests/unit/views/form/Design.spec.js
app/package-lock.json
app/package.json
app/src/forms/form/service.js
tests/functional/cypress/cypress.json
tests/functional/cypress/package-lock.json
tests/functional/cypress/package.json
tests/functional/cypress/specs/designer-undo.spec.js

Form Autosave Feature
- The feature enables form autosave. The autosave triggers when:
A) Add a component to the form builder
B) Remove a component from the form builder
C) Click on the Undo Button
D) Click on Redo Button
E) Move component in the builder
- If form designers try to log out or switch to a new page before clicking on the save button, A warning dialog box will be displayed asking the designers if they want to keep or delete the form.
- [*] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [*] I have checked that unit tests pass locally with my changes
- [*] I have run the npm script lint on the frontend and backend
- [*] I have added tests that prove my fix is effective or that my feature works
- [*] I have added …

Ayobami form autosave

---

app/frontend/src/components/forms/submission/ManageSubmissionUsers.vue
app/frontend/tests/unit/components/forms/submission/ManageSubmissionUsers.spec.js
app/src/forms/admin/routes.js
app/src/forms/common/constants.js
app/src/forms/common/models/tables/user.js
app/src/forms/user/service.js
app/tests/unit/forms/user/service.spec.js
app/tests/unit/routes/v1/admin.spec.js

Removes bceid from showing up when getting list of users

Remove bceid from get req

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/views/form/Design.vue
tests/functional/cypress/specs/designer-undo.spec.js

Form Designers can now decide if they want the form to autosave by turning off or on the toggle switch.

add autosave toggle switch

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/store/modules/form.js
app/frontend/src/views/form/Design.vue

fix autosave v-switch not resetting to default state on page reload

fix autosave v-switch not resetting to default state on page reload

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/store/modules/form.js
app/frontend/src/views/form/Design.vue

fix autosave not keeping state on page reload

fix autosave v-switch not keeping state on page reload

---

app/frontend/src/components/designer/FormDesigner.vue

remove unused lines of codes

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/store/modules/auth.js
app/frontend/src/store/modules/form.js
app/frontend/src/views/form/Create.vue
app/frontend/src/views/form/Design.vue
app/frontend/tests/unit/store/modules/auth.actions.spec.js
app/frontend/tests/unit/views/form/Design.spec.js
tests/functional/cypress/specs/designer-undo.spec.js

temporary disabled autosave feature from user view

temporary disabled autosave feature from user view

---

app/frontend/src/components/designer/FloatButton.vue
app/frontend/src/components/designer/FormDesigner.vue

fixed design issues raise of jira-form-501

fixed design issues raise of jira-form-501

---

app/frontend/src/components/designer/FloatButton.vue

fix Bottom and Top action button in FloatButton.vue

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/forms/manage/ManageVersions.vue
app/frontend/src/views/form/Design.vue

When creating new version from a form. The save button should be enabled by default.

save button should not be disabled creating new form version

---

app/frontend/src/components/designer/FormDisclaimer.vue
app/frontend/src/components/designer/FormSettings.vue

Adds a new information box for users that create public-facing forms.
The pull request only changes one file. If the Form Access is public, an information box is presented with the following text: "If you will be using this form to gather information from the general public on topics that are of general interest to the public, you are required to contact the GCPE so that your engagement can be listed on govTogetherBC."
We are required to include this disclaimer for our users who are creating public-facing forms.

Disclaimer update public forms

---

.github/actions/build-push-container/action.yaml

change environment secret for bc address api key

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/src/forms/common/models/tables/formSubmission.js
app/src/forms/form/controller.js
app/src/forms/form/service.js

User can view specifically their own submissions
Resolves: #462

Added filter for self submissions

---

app/src/components/geoAddressService.js

remove logging from geoAddressService

---

app/src/components/geoAddressService.js

fix Server-side request forgery error

---

app/src/components/geoAddressService.js
components/src/components/BCAddress/Component.ts

fix server side forgery error and remove unused code

---

app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/store/modules/form.js

Tagging you here, but going to merge this through since it was approved and we're just creating another PR to put it through our pipeline! @jonathan-longe
For reference: https://github.com/bcgov/common-hosted-form-service/pull/409#pullrequestreview-1201661656

disable link to unpublished form

---

app/frontend/src/components/designer/FormsTable.vue

The tooltip for unpublished forms is now removed from the My Forms page.

Removed the tooltip

---

app/src/components/geoAddressService.js
components/src/components/BCAddress/Component.ts

update PR with master branch

---

app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/store/modules/form.js

update branch with master latest push

---

app/frontend/src/main.js

remove font awesome from main.js

---

app/src/db/migrations/20221205215308_025-add-idp-guids.js
app/src/forms/auth/service.js
app/src/forms/common/models/tables/user.js

Adds a column to the user table containing the identity provider guid. Necessary initial step towards transitioning to the gold realm.

Add idp guids

---

app/src/db/migrations/20221205215308_025-add-idp-guids.js
app/src/forms/auth/service.js
app/src/forms/common/models/tables/user.js
app/src/forms/form/exportService.js
app/tests/unit/forms/form/exportService.spec.js

fix unable to export error

---

.github/actions/build-push-container/action.yaml
app/src/components/geoAddressService.js
components/src/components/BCAddress/Component.ts

change bc geo api url to point to production

---

app/config/default.json
app/frontend/src/components/forms/submission/NotesPanel.vue
app/frontend/src/components/forms/submission/StatusPanel.vue
app/frontend/src/store/modules/auth.js
app/frontend/tests/unit/store/modules/auth.getters.spec.js
app/myfiles/submissions/7a148efc-d433-442e-a533-70e13fe83369/cd8a8871-5c24-4069-a933-6d074532e872
app/src/db/migrations/20221208001614_026-remove-keycloak-id.js
app/src/docs/CHEFS_API_Documentation.postman_collection.json
app/src/docs/v1.api-spec.yaml
app/src/forms/admin/service.js
app/src/forms/auth/service.js
app/src/forms/common/models/views/userFormAccess.js
app/src/forms/file/middleware/filePermissions.js
app/src/forms/rbac/service.js
app/src/forms/user/service.js
app/tests/unit/forms/auth/authService.spec.js
app/tests/unit/forms/file/middleware/filePermissions.spec.js
app/tests/unit/forms/user/service.spec.js
tests/functional/cypress/fixtures/forms/current-forms.json

Replaced instances of keycloakId with idpUserId which is more reliable

Replace keycloakId with idpUserId

---

app/config/default.json
app/frontend/src/components/forms/submission/NotesPanel.vue
app/frontend/src/components/forms/submission/StatusPanel.vue
app/frontend/src/store/modules/auth.js
app/frontend/tests/unit/store/modules/auth.getters.spec.js
app/myfiles/submissions/7a148efc-d433-442e-a533-70e13fe83369/cd8a8871-5c24-4069-a933-6d074532e872
app/src/db/migrations/20221208001614_026-remove-keycloak-id.js
app/src/docs/CHEFS_API_Documentation.postman_collection.json
app/src/docs/v1.api-spec.yaml
app/src/forms/admin/service.js
app/src/forms/auth/service.js
app/src/forms/common/models/views/userFormAccess.js
app/src/forms/file/middleware/filePermissions.js
app/src/forms/rbac/service.js
app/src/forms/user/service.js
app/tests/unit/forms/auth/authService.spec.js
app/tests/unit/forms/file/middleware/filePermissions.spec.js
app/tests/unit/forms/user/service.spec.js
tests/functional/cypress/fixtures/forms/current-forms.json

Removes dependency on keycloakId as the unique identifier for users. Adds idpUserId.

Gold migration

---

app/config/custom-environment-variables.json
app/config/default.json
app/frontend/package-lock.json
app/src/components/cdogsService.js
app/src/components/chesService.js
app/src/components/clientConnection.js
openshift/README.md
openshift/app.dc.yaml

updated chefs to use the new ches and cdogs api gateway

Update ches cdogs

---

.github/actions/build-push-container/action.yaml
.github/actions/deploy-to-environment/action.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/unit-tests.yaml
app/config/custom-environment-variables.json
app/config/default.json
app/frontend/package-lock.json
app/package-lock.json
app/package.json
app/src/components/cdogsService.js
app/src/components/chesService.js
app/src/components/clientConnection.js
openshift/README.md
openshift/app.dc.yaml

fix json to csv submission export bug

---

openshift/app.cronjob.yaml

We solve the issue with cronjob yaml
- [x ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x ] I have checked that unit tests pass locally with my changes
- [ x] I have run the npm script lint on the frontend and backend
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added necessary documentation (if appropriate)
- [ x] I have approval from the product owner for the contribution in this pull request

Period and Mail feat with devops cronjob 

---

openshift/app.cronjob.yaml

Period and Mail feat With Cronjob 

---

app/frontend/src/components/forms/ColumnPreferences.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/store/modules/form.js
app/src/forms/form/exportService.js
app/tests/unit/forms/user/service.spec.js

When users select in the ColumnPreferences dialog box, the selected field or fields will be top of the stack of all the form fields

fix selected fields to be top stacked

---

app/frontend/src/components/forms/ColumnPreferences.vue

fixing styling issue in ColumnPreferences.vue

---

app/frontend/src/components/forms/ColumnPreferences.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/src/forms/form/exportService.js

- the search input in ColumnPreferences.vue to hide on input focus
- fix export submission not to export submit for both CSV and JSON
- fix buttons styling in both ColumnPreferences.vue and ExportSubmissions.vue

 fix search input placeholder to hide on focus

---

app/frontend/src/components/forms/ColumnPreferences.vue
app/frontend/src/components/forms/ExportSubmissions.vue

fix styling issues

---

app/src/forms/form/exportService.js

fixed empty rows submission export

---

app/frontend/src/components/forms/ColumnPreferences.vue
app/frontend/src/components/forms/ExportSubmissions.vue

update export functionality

---

app/frontend/src/components/forms/ColumnPreferences.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/package-lock.json
app/package.json

- update @bc_gov_forminators/json_to_csv_export version number
- 
- changed "Select Date range" to "Select date range"
- changed "Select Data/fields" to "Select data/fields"

update @bc_gov_forminators/json_to_csv_export version number

---

app/frontend/src/components/infolinks/InformationLinkDialog.vue

fix submit button in InformationLinkDialog not working

---

app/src/forms/form/exportService.js

fix parameter undefined bug

---

app/package.json

revert to old version, still breaking but not breaking for existing users

revert to old version

---

app/frontend/src/components/infolinks/InformationLinkDialog.vue
app/frontend/src/services/adminService.js
app/frontend/src/store/modules/admin.js
app/src/forms/admin/controller.js
app/src/forms/admin/routes.js
app/src/forms/admin/service.js
app/src/forms/common/models/tables/formComponentsProactiveHelp.js

- change Restore logic -fix learn more link should not be visible if we don't add URL.
- change Restore logic.
- fix learn more link should not be visible if we don't add URL.
-

fix learn more link should not be visible if we don't add URL.

---

app/package-lock.json
app/package.json
app/src/forms/common/utils.js
app/src/forms/form/exportService.js
app/tests/unit/forms/form/exportService.spec.js

An issue was reported by the BC Fish & Wildlife Branch about needing help to export submissions for their large form to CSV. The issue was investigated, and we realized we needed to update the chefs' algorithm that it uses fetch form fields. The algorithm known as findFields has been replaced with form.io flattenComponent algorithm

fix submission export to both csv and json bug 

---

app/frontend/src/components/infolinks/InformationLinkPreviewDialog.vue

remove padding InformationLinkPreviewDialog

remove padding InformationLinkPreviewDialog

---

app/frontend/src/components/forms/ColumnPreferences.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/package-lock.json
app/package.json
app/src/forms/common/utils.js
app/src/forms/form/exportService.js
app/tests/unit/forms/form/exportService.spec.js

Fix submission export not exporting some fields

Fix submission export not exporting some fields

---

app/src/forms/admin/service.js
app/src/forms/common/models/tables/formComponentsProactiveHelp.js
app/src/forms/form/service.js

improve memory caching for form components proactive help

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/services/formService.js
app/frontend/src/store/modules/form.js
app/src/forms/form/controller.js
app/src/forms/form/routes.js
app/src/forms/form/service.js

fix convert undefined or null to object error message

---

app/frontend/src/components/forms/manage/TeamManagement.vue

fix issue to with users able to delete all team owners

---

app/src/forms/email/reminderService.js

Draft - Period and mail notification final

---

app/frontend/src/main.js
app/src/forms/form/exportService.js

remove line of codes that should not be merge

---

app/frontend/src/components/forms/manage/TeamManagement.vue

fix issues with deleting users with owner permission

---

app/frontend/src/components/forms/manage/TeamManagement.vue

fix issue of deleting all users with owner permission

---

app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/services/rbacService.js
app/src/forms/rbac/controller.js
app/src/forms/rbac/routes.js
app/src/forms/rbac/service.js

…ed-form-service into ayobami_forms-76_admin_control_manage_publish_merger_form75

update branch with master branch

---

app/src/forms/file/storage/objectStorageService.js

Remove signatureVersion

---

app/src/forms/file/storage/objectStorageService.js

Fix object storage

---

app/frontend/src/components/forms/ExportSubmissions.vue

Submission to CSV templates design update

---

app/frontend/src/services/formService.js
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/src/forms/admin/service.js
app/src/forms/file/storage/objectStorageService.js
app/src/forms/file/storage/storageService.js
app/src/forms/form/controller.js
app/src/forms/form/routes.js
app/src/forms/form/service.js

Fix "An error occurred while fetching form builder component"

Fix bug message

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/services/formService.js
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/services/formService.spec.js
app/src/forms/form/controller.js
app/src/forms/form/routes.js
app/src/forms/form/service.js
app/tests/unit/routes/v1/form.spec.js

remove getting form versions from the backend

---

app/frontend/src/components/base/BaseDialog.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/manage/AddTeamMember.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/components/forms/submission/ManageSubmissionUsers.vue
app/frontend/src/services/userService.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/src/forms/auth/middleware/userAccess.js
app/src/forms/common/constants.js
app/src/forms/common/models/tables/formRoleUser.js
app/src/forms/common/models/tables/user.js
app/src/forms/rbac/controller.js
app/src/forms/rbac/routes.js
app/src/forms/rbac/service.js
app/src/forms/user/controller.js
app/src/forms/user/routes.js
app/src/forms/user/service.js
app/tests/common/dbHelper.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js
app/tests/unit/forms/user/service.spec.js
app/tests/unit/routes/v1/admin.spec.js
app/tests/unit/routes/v1/rbac.spec.js
app/tests/unit/routes/v1/user.spec.js

Merge of the features:
584
586
587
588
589

Moh features

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/services/formService.js
app/frontend/src/worker.js
app/src/forms/form/exportService.js
app/src/forms/form/routes.js

Test PR remove console.log

---

app/src/forms/form/routes.js

fix missing rate limiting reported by CodeQL

---

app/src/forms/common/escape-delimiters.js
app/src/forms/common/utils.js
app/src/forms/file/controller.js

The user reported this bug when downloading files with a comma in the file name.
User reported this bug when downloading files with a comma in the file name.

fix response_headers_multiple_content_disposition error

---

app/src/forms/common/utils.js
app/src/forms/file/controller.js

changes  escapeSpecialCharacters to encodeURI in utils.js

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/main.js
app/frontend/src/services/formService.js
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/services/formService.spec.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/frontend/tests/unit/store/modules/form.getters.spec.js
app/frontend/tests/unit/store/modules/form.mutations.spec.js
app/src/forms/submission/controller.js
app/src/forms/submission/routes.js
app/src/forms/submission/service.js
app/tests/common/dbHelper.js
app/tests/unit/forms/submission/controller.spec.js
app/tests/unit/forms/submission/service.spec.js
app/tests/unit/routes/v1/submission.spec.js
tests/functional/cypress/package-lock.json

This feature allows users to select multiple existing submissions and delete them while avoiding errors or corrupting the data

Multi submissions delete

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/src/docs/v1.api-spec.yaml
app/src/forms/common/constants.js
app/src/forms/common/models/index.js
app/src/forms/common/models/views/submissionData.js
app/src/forms/form/exportService.js

current issue:
when exporting json, it will only allow you to export version 1 of your form
some submission headers will break exports because of missing data
fix:
allow selection of version and option for All which will export all versions for json
included a submission headers check to only perform operation if the data exists 

Fix json versioning

---

app/frontend/src/components/forms/SubmissionsTable.vue

change v-switch color in SubmissionTable

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/services/formService.js
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/services/formService.spec.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/frontend/tests/unit/store/modules/form.getters.spec.js
app/frontend/tests/unit/store/modules/form.mutations.spec.js
app/src/forms/submission/controller.js
app/src/forms/submission/routes.js
app/src/forms/submission/service.js
app/tests/unit/forms/submission/controller.spec.js
app/tests/unit/forms/submission/service.spec.js
app/tests/unit/routes/v1/submission.spec.js

ability_for_user_to_restore_multiple_deleted_submissions

---

app/frontend/src/components/forms/SubmissionsTable.vue

separate view action into a different row

---

.github/workflows/owasp-zap-scan.yaml

This one is `hotfix` for https://github.com/bcgov/common-hosted-form-service/pull/596 to change gcloud image version so we can successfully pull the image

Ref #FORMS-638 - Add OWASP ZAP scan of the app into pipeline

---

.github/workflows/owasp-zap-scan.yaml

Changes to original PR https://github.com/bcgov/common-hosted-form-service/pull/587
Make it triggered by PR creation and scan pr deployments

fix: make it triggered by PR creation and scan pr deployment

---

app/frontend/src/components/forms/manage/ManageForm.vue

missing api management

---

.github/workflows/owasp-zap-scan.yaml

Change OWASP ZAP scan type from `base` to `full`

FORMS-638 - Make full OWASP scan

---

.github/workflows/owasp-zap-scan.yaml

Change OWASP ZAP scan type from `base` to `full`

feature: make full owasp scan

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/services/formService.js
app/src/forms/common/models/tables/formVersion.js
app/src/forms/common/models/views/submissionData.js
app/src/forms/form/exportService.js

- Users can select submissions columns they want to export to CSV
- added an additional template to submissions to CSV templates. Users can use this template if they want all the fields in each submission to be extracted to a single row. 

Users can select submissions columns they want to export to csv

---

.gitignore
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/RequestReceipt.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsActions.vue
app/frontend/src/utils/transformUtils.js
app/frontend/tests/unit/utils/transformUtils.spec.js
app/src/forms/common/utils.js
app/src/forms/email/reminderService.js
app/src/forms/form/exportService.js
app/src/forms/public/routes.js
openshift/patroni.dc.yaml

Update changes purposed by Jason through PR review

Changes purpose from PR 519 Review

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/src/forms/common/models/views/submissionData.js
app/src/forms/form/exportService.js

quickfix for bug in select column in submissionTable.vue

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/src/forms/common/models/views/submissionData.js
app/src/forms/form/exportService.js

added event to fields to ignore in SubmissionsTable.vue

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/src/forms/common/models/views/submissionData.js
app/src/forms/form/exportService.js

quick fix for a bug in the select column in SubmissionsTable.vue

---

app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/store/modules/form.js
app/src/docs/v1.api-spec.yaml
app/tests/unit/forms/email/reminderService.spec.js
package.json

**Reminder Feature:**  [Wiki](https://bcdevex.atlassian.net/wiki/spaces/CCP/pages/1133838349/Reminder+feature)
This feature allows a form designer to be able to enable automated submission reminders at the form level for a given submission period. Once the submission period is set, the option to enable automated notifications will be enabled for users to choose to use it or not.
If checked on, the system will send 3 notifications:
1 at the start of the submission period
1 halfway through the submission period
1 a day prior to the submission period
Reminders would only be sent to the identified “Submitters“ who haven’t submitted the data for the given period.
A generic template will be used for the notifications. The content should always include the link to the form. Future possible …

PROD-Added features Reminder, Schedule Setting and Copy an existing feature

---

app/frontend/src/components/designer/FormViewer.vue
app/src/forms/email/reminderService.js

fix typos and formatting

---

app/package-lock.json
app/package.json
app/src/forms/file/service.js
app/src/forms/form/controller.js
app/src/forms/form/routes.js
app/src/forms/form/service.js

Users can use this endpoint to extract or download all files from the form submissions at a go instead of going into each submission and downloading the file submitted with the submission.

users can extract files from the form submissions

---

app/src/forms/form/routes.js

fix rate-limit message thrown by github

---

app/frontend/src/components/designer/FormViewer.vue

expire does not always exist in this form schedule which is preventing some users from saving.. added simple check to see if it even exists.

fix form schedule status expire

---

app/frontend/src/components/designer/FormViewer.vue

fix checking for the schedule reminder expire object

fix schedule expire

---

app/src/forms/form/exportService.js
app/src/forms/form/routes.js

- fix type confusion through parameter tampering issue
- fix missing rate limiting issue

fix type confusion through parameter tampering issue

---

app/src/forms/form/exportService.js

fix type confusion through parameter tampering

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue

remove checkbox from header in the Submissions Fields table in ExportSubmissions.vue

remove checkbox from header in the Submissions Fields table

---

app/src/forms/form/service.js

createdAt wasn't being checked if it existed before accessing it's indices

createdAt check

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue

- remove sorting from submissions fields table
- added fields selection count
- 

remove sorting from submissions fields table

---

app/frontend/src/store/modules/form.js

puts a default value for the reminder and copy existing submission form functionality setting.

default value for reminder and copy

---

app/frontend/src/components/forms/submission/MySubmissionsTable.vue

added "Draft Updated By" to the Previous Submissions Table

add "Draft Updated By" to Previous Submissions Table

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/router/index.js
app/frontend/src/services/formService.js
app/frontend/src/store/modules/form.js
app/frontend/src/views/form/Export.vue
app/frontend/tests/unit/services/formService.spec.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/src/forms/common/models/tables/formVersion.js
app/src/forms/form/controller.js
app/src/forms/form/exportService.js
app/src/forms/form/routes.js
app/tests/fixtures/submission/kitchen_sink_submission_extract_field_csv_export.json
app/tests/unit/forms/form/controller.spec.js
app/tests/unit/forms/form/exportService.spec.js
app/tests/unit/routes/v1/form.spec.js

This feature allows users to select the submission fields they want to export to CSV

Ability to select submission fields to export to csv

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/router/index.js

- remove select all custom logic in ExportSubmission.vue
- change requiresAuth from idir to true

remove select all custom logic in ExportSubmission.vue

---

app/frontend/src/components/forms/ExportSubmissions.vue

- remove the right margin from the export button

remove right margin from export button

---

app/frontend/src/components/forms/ExportSubmissions.vue

fix export button right margin

fix export button right margin

---

app/frontend/src/components/forms/ExportSubmissions.vue

work on select version to display published version first

work on select version to display published version first

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/router/index.js

- submissions fields table will be hidden if no version is selected
- fix review suggestions

submissions fields table will be hidden if no version selected

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/utils/permissionUtils.js
app/frontend/tests/unit/utils/permissionUtils.spec.js

The current error messages don't provide enough detail to tell if CHEFS as a whole is down, or if there are problems specific to a single form. Improve the error messages for the scenarios:
1. the form exists but there is no published version
1. the form ID is incorrect or the form has been deleted

feat: FORMS-655 improve error messages for unavailable forms

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/src/forms/form/exportService.js

rename CSV format options

---

app/frontend/src/components/forms/submission/MySubmissionsTable.vue

Reviewer can see who made the last edits on the form

Ability to know who last edited draft

---

app/frontend/src/components/forms/SubmissionsTable.vue

Adds the status column into the filter

Fix filter

---

app/frontend/src/components/forms/ExportSubmissions.vue

Ability to select submission fields to export to csv 

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/services/formService.js
app/src/forms/form/exportService.js

fix suggested issues in PR reviews

---

app/frontend/src/components/base/BaseNotificationBar.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/views/file/Download.vue
app/src/forms/email/assets/bodies/file-download-ready.html
app/src/forms/email/emailService.js

Further UI enhancing the large export flow also include FORMS-698

FORMS-697: new UI improvements for export email flow 

---

app/config/custom-environment-variables.json
app/frontend/src/components/admin/AdminPage.vue
app/frontend/src/components/admin/Dashboard.vue
openshift/redash/README.md
openshift/redash/patroni.networkpolicy.yaml
openshift/redash/postgresql.deploy.yaml
openshift/redash/redash.route.yaml
openshift/redash/redis.deploy.yaml
openshift/redash/secrets.yaml

Metabase doesn't provide user or query auditing in it's free version. Rebase does offer these, but lacks other features. This PR is for investigating the differences so that the two can be evaluated side-by-side.
Requirements from FORMS-583:
- Create a process for auditing when a user logs into [Redash], and what queries they make.
- Handle permissions for what data users can access based on groups.
- Embed [Redash] into admin panel of CHEFS.
> NOTE: As a PoC the testing was not written, and this is not intended to go to production in its current state.

feat: FORMS-583 redash proof of concept

---

app/src/docs/v1.api-spec.yaml

added export with fields endpoint documentation

---

app/frontend/src/views/form/Success.vue

translated Sucess.vue page 

---

app/frontend/src/components/designer/FormSettings.vue

Solve issue with multi draft upload checkbox 
- [x ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ x] I have checked that unit tests pass locally with my changes
- [ x] I have run the npm script lint on the frontend and backend
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation (if appropriate)
- [ x] I have approval from the product owner for the contribution in this pull request

solve issue disable multi draft upload

---

app/frontend/src/components/admin/AdminVersions.vue
app/frontend/src/components/admin/Developer.vue
app/frontend/src/components/base/BaseInternationalization.vue
app/frontend/src/components/designer/FormViewerMultiUpload.vue

remove error message variables added by health team

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewerMultiUpload.vue
app/frontend/src/internationalization/trans/chefs/ar/ar.json
app/frontend/src/internationalization/trans/chefs/de/de.json
app/frontend/src/internationalization/trans/chefs/en/en.json
app/frontend/src/internationalization/trans/chefs/es/es.json
app/frontend/src/internationalization/trans/chefs/fa/fa.json
app/frontend/src/internationalization/trans/chefs/fr/fr.json
app/frontend/src/internationalization/trans/chefs/hi/hi.json
app/frontend/src/internationalization/trans/chefs/it/it.json
app/frontend/src/internationalization/trans/chefs/ja/ja.json
app/frontend/src/internationalization/trans/chefs/ko/ko.json
app/frontend/src/internationalization/trans/chefs/pa/pa.json
app/frontend/src/internationalization/trans/chefs/pt/pt.json
app/frontend/src/internationalization/trans/chefs/ru/ru.json
app/frontend/src/internationalization/trans/chefs/tl/tl.json
app/frontend/src/internationalization/trans/chefs/uk/uk.json
app/frontend/src/internationalization/trans/chefs/vi/vi.json
app/frontend/src/internationalization/trans/chefs/zh/zh.json
app/frontend/src/internationalization/trans/chefs/zhTW/zh-TW.json

fixed download translation in FormViewerMultiUpload.vue

---

app/frontend/src/components/designer/FloatButton.vue
app/frontend/src/components/designer/FormDesigner.vue

rename save1 to savedMsg in FloatButton.vue

---

app/frontend/src/components/designer/FormDesigner.vue

Forms 699 multi language and internationalization strategy 

---

app/frontend/src/components/designer/FormDesigner.vue

set default locale for Form.io FormBuilder

---

app/src/docs/v1.api-spec.yaml

The endpoint /forms/{formId}/versions was removed but it is still listed in the documentation. This is causing confusion for the API users who are trying to call the endpoint.

docs: FORMS-734 remove docs for removed endpoint

---

app/src/db/migrations/20230517012755_32-add-update-col-alter-submissions-vw.js
app/src/docs/v1.api-spec.yaml
app/src/forms/common/models/views/submissionData.js
app/src/forms/form/exportService.js

Enhance Export API in CHEFS to support filtering based on status and updates, Added new column query parameter to accept new columns to fetch like updatedAt, deleted or draft. Added new migration file to modify view to add new updatedAt column. change documentation.

Test:Enhance Export API for ETL

---

tests/load/load-test/index.js
tests/load/load-test/package-lock.json
tests/load/load-test/package.json

The load tests were using the `unirest.js` library, which is dependent on `request.js`. Since `request.js` was deprecated four years ago and has security vulnerabilities, it would be best if we could remove this dependency. Switched from `unirest` to the libraries `http` and `https` that are built into node. (since this code is rarely used, I thought it best to use the packages built into node rather than something like Axios, which we would have a lot of toil with updating to latest all the time).
Vulnerability fix (non-breaking change which fixes security vulnerabilities)

chore: FORMS-733 remove unirest from load test dependencies

---

app/frontend/src/components/admin/AdminVersions.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/internationalization/trans/chefs/en/en.json

Fixed some very minor translation bugs:
- The admin forms page was using the wrong component name for translations
- There was one English translation that was French
- The team management page had a couple of minor fields that weren't translating.

bug: FORMS-739 fix some translation bugs

---

openshift/app.cronjob.yaml

Red Hat Advanced Cluster Security (ACS) reported problems with the version of the container that is used for the cron jobs. Although this pod runs internally and cannot be accessed from outside the cluster, it is still a good idea to keep it up to date.
Chore (non-breaking change which fixes an issue)

chore: FORMS-740 update cronjob container version

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/src/forms/auth/service.js
app/src/forms/common/utils.js

We got a lot of internal SQL errors in the pods logs when app trying to create current logged user record which already exist
Also this PR includes API pagination fixes like: Reset page number when you do search and get all submissions by default (if itemPerPage not specified)

FORMS-743: Insert into users table fails - possibly only on first login / duplication

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/src/forms/auth/service.js
app/src/forms/common/constants.js
app/src/forms/common/models/views/submissionMetadata.js
app/src/forms/common/models/views/userSubmissions.js
app/src/forms/common/utils.js
app/src/forms/form/service.js
app/src/forms/rbac/service.js

Rollback API Pagination to make it then properly via versioning (v2)

Rollback API Pagination

---

app/frontend/src/components/forms/SubmissionsTable.vue

Previous commit broke the submissions table "user preferences" (column display selection) by limiting the columns to those on the form. This meant that anytime the user set preferences, the Submission Date, Submitter, and Status columns were lost.
This PR will fix the bug but any users who set permissions and "lost" Submission Date, Submitter, and Status will need to reset their permissions to include those fields.
Note: I did not add tests for this as there are currently no tests for this component. Will wait for the Vue 3 upgrade and then we need to look at getting better test coverage.

bug: FORMS-742 fix submissions user preferences

---

app/frontend/src/internationalization/trans/chefs/de/de.json
app/frontend/src/internationalization/trans/chefs/en/en.json
app/frontend/src/internationalization/trans/chefs/es/es.json
app/frontend/src/internationalization/trans/chefs/fa/fa.json
app/frontend/src/internationalization/trans/chefs/fr/fr.json
app/frontend/src/internationalization/trans/chefs/hi/hi.json
app/frontend/src/internationalization/trans/chefs/it/it.json
app/frontend/src/internationalization/trans/chefs/ja/ja.json
app/frontend/src/internationalization/trans/chefs/ko/ko.json
app/frontend/src/internationalization/trans/chefs/pa/pa.json
app/frontend/src/internationalization/trans/chefs/pt/pt.json
app/frontend/src/internationalization/trans/chefs/ru/ru.json
app/frontend/src/internationalization/trans/chefs/tl/tl.json
app/frontend/src/internationalization/trans/chefs/uk/uk.json
app/frontend/src/internationalization/trans/chefs/vi/vi.json
app/frontend/src/internationalization/trans/chefs/zh/zh.json
app/frontend/src/internationalization/trans/chefs/zhTW/zh-TW.json

When viewing a submission, the version number is not displaying.

bug: FORMS-753 fix missing version number for submission views

---

.codeclimate.yml

We switched from Jenkins to GitHub Actions a long time ago, but the repo cleanup was never done.
- Remove Jenkins files
- Update the Code of Conduct to the latest version
- Update the openshift/README.md with massive cleanup

chore: FORMS-755 remove jenkins, docs updates

---

openshift/README.md

Fixed broken and stale links in the /openshift readme.

chore: FORMS-755 fix broken documentation links

---

app/frontend/src/components/forms/submission/MySubmissionsTable.vue

fix selected column not showing in your column table

fix selected column not showing in your column table

---

CONTRIBUTING.md
README.md
SECURITY.md
openshift/README.md

- Fixed broken and stale links in the /openshift readme.
- Updated version of CHEFS in the security document. When we get versioning working we may want to remove this so that it isn't always out of date.
- Did a small expansion of the contributing document. This is a first step but there is a lot of work we could do here.

docs: FORMS-755 fix broken links, do minor updates

---

app/frontend/src/views/About.vue

add RTL to about.vue

---

app/src/forms/admin/index.js
app/src/forms/admin/routes.js
app/src/forms/file/routes.js
app/src/forms/form/routes.js
app/src/forms/permission/routes.js
app/src/forms/rbac/routes.js
app/src/forms/role/routes.js
app/src/forms/submission/routes.js
app/src/forms/user/routes.js
app/src/swagger/swagger_api_doc.yaml

Fix pr review suggested changes.
Documentation (non-breaking change with enhancements to documentation) -->

fix pr review suggested changes

---

app/src/forms/admin/routes.js
app/src/forms/file/routes.js
app/src/forms/form/routes.js
app/src/forms/rbac/routes.js
app/src/forms/role/routes.js
app/src/forms/submission/routes.js
app/src/forms/user/routes.js
app/src/swagger/swagger_api_doc.yaml

Fix PR review recommended changes

fix PR review recommended changes

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/designer/FormsTable.vue

Two reports from Medis and Teams channel about copying of previous form submissions was not working. The problems were:
1. The code was handling layout components like panels, but not layout components like columns
2. The code was incorrectly checking the `isUseForCopy` property and assuming that undefined was the same as false
3. The code wasn't handling undefined return values from a function, and producing an error
4. Fixed a console error message that wasn't providing the template parameters
Also added in [FORMS-783](https://bcdevex.atlassian.net/browse/FORMS-783?atlOrigin=eyJpIjoiN2NiNTJmNGQxNTY2NGRjMjg2YTczODYzOThlNTQ0YmUiLCJwIjoiaiJ9) since it's a small quick change so that the search field on the forms list says "Search", not "Create a New Form".
Bug fix (non-breaking change which …

bug: FORMS-789 fix previous submission copying and search text

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/src/forms/form/exportService.js

Added “All” option to drop-down menu in submission export page

 unable to select all versions for export

---

app/src/forms/admin/routes.js

Added active parameter to get forms endpoint in admin route.

add active parameter to get forms endpoint in admin route

---

app/frontend/src/components/designer/FormViewer.vue

Fix a problem where a datagrid on a form: if components have "Allow value propagation" unset, only the first item in the datagrid was being unset. The code needs to handle arrays of components.
We have no tests for this code - once the Vue 3 upgrade is done we need to add tests and refactor all this code (and move the code out of the component). I think I have covered the immediate use case that is having problems, but I don't know if nested datagrids will work or not.

bug: FORMS-793 fix datagrid submission copying

---

app/frontend/src/components/base/BaseFilter.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

Fix bug in select columns in SubmissionTable.vue, MySubmissionTable.vue and TeamManagement.vue. I removed pagination in the select columns table and added sort on selection.

Forms 754 select columns in my submission table

---

app/frontend/src/components/forms/submission/MySubmissionsTable.vue

add custom fields to select columns in my submissions page

add custom fields to select columns in my submissions page

---

app/frontend/src/components/forms/submission/MySubmissionsTable.vue

Added missing confirmationId and action in MySubmissionsTable

add missing confirmationId and action in MySubmissionsTable

---

app/src/db/migrations/20230705190020_change_file_storage_constrains.js
app/src/forms/common/constants.js

fix rremoved files during commit

---

app/frontend/src/components/base/BaseFilter.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

Fix bug in select columns in SubmissionTable.vue, MySubmissionTable.vue and TeamManagement.vue. I removed pagination in the select columns table and added sort on selection.

Forms-754_select_columns_in_my_submission_table

---

.github/actions/build-push-container/action.yaml

relative path test

---

.github/actions/build-push-container/action.yaml

change url path to relative path

---

.github/actions/build-push-container/action.yaml

test relative path

---

.github/actions/build-push-container/action.yaml

test url relative path

---

.github/actions/build-push-container/action.yaml

test relative url

---

.vscode/launch.json
app/src/forms/auth/middleware/apiAccess.js
app/src/forms/auth/middleware/userAccess.js
app/src/forms/form/routes.js

Some of the API endpoints throw errors which are not been caught and sent back to the calling platform.

Forms-801_improving_api_error_messaging

---

.vscode/launch.json
app/src/forms/form/routes.js

revert code that should not have been committed

---

.vscode/launch.json
app/frontend/src/components/designer/FormViewerMultiUpload.vue
app/src/forms/form/routes.js

update branch with upstream master

---

components/src/components/BCAddress/Component.ts
components/src/components/SimpleBCAddress/Component.ts

Removed the Address 1, Address 2, City, Country, Province and Postal textfields from both BC Address Component and Simple BC Address Component

remove unused textfields

---

components/src/components/BCAddress/editForm/Address.edit.provider.ts
components/src/components/SimpleBCAddress/editForm/Address.edit.provider.ts

Removed disabled property from both BC Address and Simple BC Address response property and display value property

removed disabled property

---

app/frontend/src/components/designer/FormViewerMultiUpload.vue
app/src/docs/v1.api-spec.yaml
app/src/forms/common/models/views/submissionData.js

Improvements in FE validation UI where the percentage got stuck to 99% when there is a validation issue (FIXED).
Covered Include draft and deleted records in export API where the False value to those flags does not return expected results. 
Added needed documentation in API spec

Draft:Quick fixes in FE Validation & Export API

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/admin/AdminPage.vue
app/frontend/src/internationalization/trans/chefs/ar/ar.json
app/frontend/src/internationalization/trans/chefs/de/de.json
app/frontend/src/internationalization/trans/chefs/en/en.json
app/frontend/src/internationalization/trans/chefs/es/es.json
app/frontend/src/internationalization/trans/chefs/fa/fa.json
app/frontend/src/internationalization/trans/chefs/fr/fr.json
app/frontend/src/internationalization/trans/chefs/hi/hi.json
app/frontend/src/internationalization/trans/chefs/it/it.json
app/frontend/src/internationalization/trans/chefs/ja/ja.json
app/frontend/src/internationalization/trans/chefs/ko/ko.json
app/frontend/src/internationalization/trans/chefs/pa/pa.json
app/frontend/src/internationalization/trans/chefs/pt/pt.json
app/frontend/src/internationalization/trans/chefs/pu/pu.json
app/frontend/src/internationalization/trans/chefs/ru/ru.json
app/frontend/src/internationalization/trans/chefs/tl/tl.json
app/frontend/src/internationalization/trans/chefs/uk/uk.json
app/frontend/src/internationalization/trans/chefs/vi/vi.json
app/frontend/src/internationalization/trans/chefs/zh/zh.json
app/frontend/src/internationalization/trans/chefs/zhTW/zh-TW.json

remove delCurrformErrMsg translations from all the translation files

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/admin/AdminPage.vue

remove slider css

---

app/frontend/src/components/admin/AdminPage.vue

remove multiLanguage from computed

---

app/frontend/src/components/admin/AdminFormsTable.vue
app/frontend/src/components/admin/AdminPage.vue
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/manage/ManageLayout.vue
app/frontend/src/components/forms/manage/ManageVersions.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/views/form/Create.vue

fix alignment issues

---

app/frontend/src/components/admin/AdminFormsTable.vue
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/views/About.vue
app/frontend/src/views/form/Create.vue

more alignment fixed for rtl support

---

app/frontend/src/components/admin/AdminPage.vue

remove multiLanguage from AdminPage

---

app/frontend/src/views/form/Create.vue

fix wrong error message in create.vue

---

app/frontend/src/components/designer/FormDisclaimer.vue
app/frontend/src/components/forms/manage/AddTeamMember.vue

remove span from ul li tags in FormDisclaimer

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/forms/manage/ManageVersions.vue
app/frontend/src/components/infolinks/GeneralLayout.vue
app/frontend/src/store/modules/form.js

- remove rtl support for vuetify v-switch
- remove pu language code

remove rtl support for vuetify v-switch

---

app/frontend/src/components/designer/FormSettings.vue

Fixed login required mixed labelling in FormSettings.vue

---

.github/actions/deploy-to-environment/action.yaml
.github/workflows/on_pr_closed.yaml
.github/workflows/on_pr_opened.yaml
.github/workflows/on_push.yaml

These changes are in support of pulling some hardcoded values out of github actions code to github repository level variables. This is required to make github actions code generic so other contributors can use the code unchanged and still be able to run CI/CD pipeline and deploy to their own set of OpenShift projects.
The following changes are implemented:
Introduced three new github repository variables. Note that these variables need to be created PRIOR these changes get merged into master branch or PR to master is created.
APP_NAME
NAMESPACE_PREFIX
ROUTE_PREFIX
Replaced hardcoded env variables values with references to APP_NAME and NAMESPACE_PREFIX github repo variables
Introduced new env variable route_prefix that is set to Github repo variable ROUTE_PREFIX. This new variable is used …

GitHub act params

---

app/frontend/src/components/base/BaseFilter.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/DeleteSubmission.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

Default columns (Submission Date, Submitter, Status) are no longer available for selection if they are de-selected, and user click on one of the other form columns.

fix missing deselected default columns in Select Columns

---

app/frontend/src/components/base/BaseFilter.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

- removed custom sort logic in BaseFilter.vue
- added sorting to TeamManagement.vue, MySubmissionsTable.vue and SubmissionTable.vue

remove custom sort logic in BaseFilter.vue

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

fix table header reordering

---

app/frontend/src/components/base/BaseFilter.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

optimize code and update branch with master branch

---

app/src/forms/auth/service.js

Fix for duplicate IDIR users are being created with lowercase and uppercase user ids, coming back when we used  idp user id instead of keycloak 

FORMS-806: Duplicate IDIR users are being created with lowercase and uppercase user ids

---

app/frontend/src/components/designer/FormViewer.vue

When a form has a multiselect and the user is allowed to copy from an existing submission, a select field with multiple values is not copying correctly.
Expected Behaviour:
Current Behaviour:
It was also noticed during troubleshooting that all multiselects are being copied, even when they shouldn’t be - will also fix.
Expected Behaviour:
Current Behaviour:

bug: FORMS-831 fix multiselect submission copying

---

app/frontend/src/internationalization/trans/chefs/hi/hi.json
app/src/forms/form/service.js

I missed a comma when doing a big conflict merge. Also fixed a typo in `susbscriptionEvent`.

bug: fix bungled conflict merge in subscription event

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/package-lock.json

Fixed actions column right alignment issue in SubmissiontionTable.vue and MySubmissionsTable.vue

fix actions column right alignment issue

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

remove headers length check

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

remove package-lock.json

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

Bug: Fix actions column right alignment issue in SubmissionsTable.vue and MySubmissionsTable.vue

Bug: Fix actions column right alignment issue

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

Bug: Fix actions column right alignment issue in SubmissionsTable.vue and MySubmissionsTable.vue

Bug: Fix actions column right alignment issue in SubmissionsTable.vue and MySubmissionsTable.vue

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/store/modules/form.js
app/src/forms/common/models/views/submissionMetadata.js
app/src/forms/common/models/views/userSubmissions.js
app/src/forms/form/service.js
app/src/forms/rbac/service.js

fix: data table sorting with pagination

---

app/frontend/src/components/forms/SubmissionsTable.vue

fix: remove unused paginate method

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/src/forms/common/models/views/submissionMetadata.js
app/src/forms/common/models/views/userSubmissions.js

fix: fix issue with sorting by submission date

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

fix: fix 500 error when sorting submissions with status on epmty table

---

app/frontend/src/components/forms/SubmissionsTable.vue

This is a dummy PR to test fetch/rebase vs pull

trying to create a merge conflict for testing

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/src/forms/common/utils.js
app/src/forms/form/service.js
app/src/forms/rbac/service.js

Forms 764 api pagination ehancement

---

app/src/forms/form/service.js
app/tests/unit/forms/form/service.spec.js

Fix a bug on the Submissions table where some fields from the form are missing.
Scenario:
- create a form with a Table layout
- add input field(s) into the Table layout
Before:
After:

bug: FORMS-854 missing submission table fields

---

app/src/forms/form/service.js
app/src/forms/rbac/service.js

Filtered out submissionId from the submissions data when searching

filtered out submissionId from the submissions data when searching

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/src/forms/form/service.js
app/src/forms/rbac/service.js

fix search functionality in submissions pages to be case-insensitive

fix: change case-sensitive to case-insensitive search in submission pages

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

fix: fix submissions not showing in MySubmissionsTable

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/src/forms/form/service.js

fix: fix search field not working in MySubmissionTable

---

app/frontend/src/components/designer/FormSettings.vue

Tooltip timing problems occur when the user transitions away from the tooltip content, but the tooltip itself remains visible for an additional 4 seconds

fix: experimental tooltips timing delays

---

app/frontend/src/components/forms/SubmissionsTable.vue

fix: selected column in submissionTable.vue not saving to database

fix: selected column in submissionTable.vue not saving to database

---

app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/utils/permissionUtils.js
app/frontend/tests/unit/utils/permissionUtils.spec.js

update branch with upstream master branch

---

COMPLIANCE.yaml

The repo-mountie requested that we update the COMPLIANCE.yaml file. We were out of date with the PIA and STRA dates, and the status of the STRA.

chore: FORMS-842 PIA and STRA updates

---

app/src/forms/form/service.js
app/tests/unit/forms/form/service.spec.js

The PR is a fix for the draft submissions showing in the submissions list when searching in the submission page.

fix: filter out draft submissions on the submission page search

---

app/frontend/src/components/forms/manage/ApiKey.vue
app/frontend/src/internationalization/trans/chefs/ar/ar.json
app/frontend/src/internationalization/trans/chefs/de/de.json
app/frontend/src/internationalization/trans/chefs/en/en.json
app/frontend/src/internationalization/trans/chefs/es/es.json
app/frontend/src/internationalization/trans/chefs/fa/fa.json
app/frontend/src/internationalization/trans/chefs/fr/fr.json
app/frontend/src/internationalization/trans/chefs/hi/hi.json
app/frontend/src/internationalization/trans/chefs/it/it.json
app/frontend/src/internationalization/trans/chefs/ja/ja.json
app/frontend/src/internationalization/trans/chefs/ko/ko.json
app/frontend/src/internationalization/trans/chefs/pa/pa.json
app/frontend/src/internationalization/trans/chefs/pt/pt.json
app/frontend/src/internationalization/trans/chefs/ru/ru.json
app/frontend/src/internationalization/trans/chefs/tl/tl.json
app/frontend/src/internationalization/trans/chefs/uk/uk.json
app/frontend/src/internationalization/trans/chefs/vi/vi.json
app/frontend/src/internationalization/trans/chefs/zh/zh.json
app/frontend/src/internationalization/trans/chefs/zhTW/zh-TW.json

When using languages other than English and Tagalog, the show / hide functionality for the API Key is broken. The API Key is always visible and there is no way to hide it:
The Vue component shows and hides the key by switching the v-text-field type between "text" and "password". However, this value is set up for translation so, for example in Spanish instead of "password" it's contraseña. Since v-text-field doesn't know this type, it defaults to "text". Note that it works for Tagalog because the translations for text and password are "text" and "password".
Fix: don't use translations here.
Also fixed the layout spacing for the buttons:

fix: show/hide api key when not using english

---

app/frontend/src/components/forms/manage/ShareForm.vue
app/frontend/src/components/forms/manage/TeamManagement.vue

1. Fix the spacing between the buttons when sharing the form. Before:
After:
***
2. Fix the Team Management table, it was showing nothing after the Select Columns was used (even if no change, just a save). Before:
After:

fix: miscellaneous changes

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/App.vue
app/frontend/src/components/base/BaseWarningDialog.vue
app/frontend/src/plugins/keycloak.js
app/frontend/src/router/index.js
app/frontend/src/store/modules/auth.js

There has been a reported issue of users suddenly being logged out due to token expiration. This feature will notify the users that their token is about to expire. They can log out or continue using the app and renew their token.

feat: implement timeout warning for SSO token timeout

---

app/frontend/src/components/base/BaseInternationalization.vue
app/frontend/src/internationalization/trans/vuetify/locale/README.md

Vuetify contains translations for Traditional Chinese but these translations are not being used due to a bug in checking the language code.
Also added a little readme file to explain why only some translation files exist for Vuetify.

fix: FORMS-891 vuetify traditional chinese support (#1071)

---

app/src/forms/common/models/views/submissionMetadata.js

In the Submissions page, sorting by the individual fields was not working. This fix ensures the user is able to sort again!

Fixed submission table sort - Vue3

---

app/src/forms/form/service.js

This PR is a fix to the reported bug. Draft submissions are being fetched with the submitted submissions when searching the submissions on the submission page. This PR filtered the draft submissions from the submission list at the backend.

fix: filter draft submissions from the submission list during the submission search

---

app/src/forms/form/service.js

update: update branch with upstream master branch

---

app/src/forms/form/service.js

fix: remove boolean check for filterformSubmissionStatusCode props

---

app/frontend/src/services/interceptors.js

Increase frontend timeout to try to bring CHEFS back online.

fix: urgent timeout increase to fix outage

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/base/BaseImagePopout.vue
app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/submission/MySubmissionsActions.vue
app/frontend/src/components/forms/submission/NotesPanel.vue
app/frontend/src/router.js

Fixed a couple of visual differences in Vue3.
1) The default behaviour of navigating to a new route or page doesn't automatically scroll to the top in Vue Router. This change fixes the problem when the user clicks on the "Create a Form" button at the bottom of the About Page it would redirect to the bottom of the "Create a Form" page. Now it automatically scrolls to the top of the page.
2) The alert below was always visible. Fixed it so it is only visible in edit mode. Also added some margin bottom.
3) Fixed the form.io submit button from having no margin top. 
4) Fixed the Notes Component as it was not responsive on smaller screens.
From:
To:
5) Increased the size of the light-box image in the About Page
6)  Fixed the styling for the buttons below in the actions column. The buttons were …

Fix: Visual changes - Vue3

---

app/frontend/src/components/forms/ExportSubmissions.vue

This pull request aims to fix the CSV exporting functionality. The user was unable to choose specific fields (columns) to display in the export file in Vue3. This change was required due to the new changes in the Vuetify framework. The images below explain the need for this fix:

Fix: CSV field selection - Vue3

---

app/frontend/src/components/base/BaseDialog.vue
app/frontend/src/components/base/BaseTime.vue
app/frontend/src/components/base/BaseWarningDialog.vue
app/frontend/src/internationalization/trans/chefs/ar/ar.json
app/frontend/src/internationalization/trans/chefs/de/de.json
app/frontend/src/internationalization/trans/chefs/en/en.json
app/frontend/src/internationalization/trans/chefs/es/es.json
app/frontend/src/internationalization/trans/chefs/fa/fa.json
app/frontend/src/internationalization/trans/chefs/fr/fr.json
app/frontend/src/internationalization/trans/chefs/hi/hi.json
app/frontend/src/internationalization/trans/chefs/it/it.json
app/frontend/src/internationalization/trans/chefs/ja/ja.json
app/frontend/src/internationalization/trans/chefs/ko/ko.json
app/frontend/src/internationalization/trans/chefs/pa/pa.json
app/frontend/src/internationalization/trans/chefs/pt/pt.json
app/frontend/src/internationalization/trans/chefs/ru/ru.json
app/frontend/src/internationalization/trans/chefs/tl/tl.json
app/frontend/src/internationalization/trans/chefs/uk/uk.json
app/frontend/src/internationalization/trans/chefs/vi/vi.json
app/frontend/src/internationalization/trans/chefs/zh/zh.json
app/frontend/src/internationalization/trans/chefs/zhTW/zh-TW.json
app/frontend/src/store/modules/auth.js
app/frontend/tests/unit/components/base/BaseTime.spec.js
app/frontend/tests/unit/store/modules/auth.actions.spec.js
app/frontend/tests/unit/store/modules/auth.getters.spec.js
app/frontend/tests/unit/store/modules/auth.mutations.spec.js

- add a countdown timer to the token expiration warning dialog
- wrote unit tests for the frontend changes
- added multilang to the new components created

update: add countdown timer to token expiration warning dialog

---

app/frontend/src/assets/scss/style.scss

This fix is to address the scrolling issue in Vue3 introduced by the new Bootstrap. The latest version of Bootstrap contain several changes, one of which is the default setting of the smooth scrolling behaviour. To fix this issue, the particular CSS variable responsible for this behaviour was set to "false" before importing the file. This change was required as the smooth scrolling feature introduced a few inconveniences in the application.  For example, when clicking an image in the About Page and closing the modal there-after, it would unintentionally return the page to the top and scroll back to the image's original location.

Fix: Jumping/Smooth Scroll of Application - Vue3

---

app/frontend/src/components/designer/FormViewer.vue

This changes tries to rectify an issue within Vue3, where, when a user makes an edit to an existing submission, it generates three API calls for an update. The change is necessary to prevent flooding/duplicate data in the submission history as well as the database. The solution triggers a re-computation of the viewerOptions after the component mounts, fixing the 3 duplicate API calls. 

Fix: Editing submission resulting in three API put requests - Vue3

---

app/frontend/src/assets/scss/style.scss

There’s a bug with the Select component that if the default Widget Type of ChoicesJS is used, then the items in the list are not visible when used in components like Data Grids:
The workaround has been to switch the Widget Type to HTML 5. There is a different bug with that widget though: https://github.com/formio/formio.js/issues/5390
Implement the fix described in: https://github.com/formio/formio.js/issues/5216#issuecomment-1591282850 
and leave a comment that it should be re-evaluated when formio.js is updated.
After:

fix: FORMS-903 choicesjs select visibility

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/base/BaseStepper.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/plugins/vuetify.js

Fixed tooltip background colour
BaseStepper fixed header and content box-shadow
Fixed BCGovNavBar elevation
added surface-variant colour

some styling changes

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/admin/AdminFormsTable.vue
app/frontend/src/components/admin/AdminUsersTable.vue
app/frontend/src/components/admin/AdminVersions.vue
app/frontend/src/components/base/BasePanel.vue
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/manage/ManageVersions.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/components/forms/submission/StatusTable.vue

This change aims to fix the visual differences between the Vue2 and Vue3 data tables. For example, in Vue3, the tables were not displaying the striped table layout ( alternating colors between rows ) & did not contain the hover property. This is due to the differences between Vuetify 2 and Vuetify 3. Also changed the card outline (border) to match the old Vue2 color. Images are attached for the visual differences:
**From:** 
**To:**
**From:**
**To:**

Fix:  v-data-table background/hover & other visual changes - Vue3

---

app/src/forms/auth/service.js

Users are reporting that they are occasionally receiving errors with the app. I think it would be best to fix existing errors in the application so that we can rule them out as being the cause of the problem.
When a user (IDIR or BCeID) logs in for the first time, the app is trying to create the “User” object twice. The second create will fail with a database exception, and this seems to have a cascading effect on the connection pool that causes other requests to fail (?).
```
ERROR: duplicate key value violates unique constraint "user_keycloakid_unique"
DETAIL: Key ("keycloakId")=(aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa) already exists.
UniqueViolationError: insert into "user" ("createdAt", "email", "firstName", "fullName", "id", "idpCode", "idpUserId", "keycloakId", "username") values ($1, …
```

fix: FORMS-904 user insert race condition

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/designer/FormViewerActions.vue
app/frontend/src/components/forms/submission/MySubmissionsActions.vue
app/frontend/src/components/infolinks/GeneralLayout.vue
app/frontend/src/components/infolinks/ProactiveHelpDialog.vue
app/frontend/src/views/form/Create.vue
app/frontend/src/views/form/Design.vue
app/frontend/tests/unit/components/infolinks/GeneralLayout.spec.js
app/frontend/tests/unit/components/infolinks/ProactiveHelpDialog.spec.js

removed print visibility from form viewer actions
form viewer actions edit button was too big
mysubmissionactions column spacing added
proactivehelp in admin view is working now
TODO: proactive help isn't being displayed.. the icon isn't being added into the form.io builder

Some fixes

---

app/src/forms/form/routes.js

We have a runaway form that is taking down CHEFS. Implement rate limiting on the endpoint it is abusing.

fix: FORMS-906 rate limit forms/ID/submissions

---

app/tests/unit/routes/v1.spec.js
app/tests/unit/routes/v1/admin.spec.js
app/tests/unit/routes/v1/form.spec.js
app/tests/unit/routes/v1/permission.spec.js
app/tests/unit/routes/v1/rbac.spec.js
app/tests/unit/routes/v1/role.spec.js
app/tests/unit/routes/v1/submission.spec.js
app/tests/unit/routes/v1/user.spec.js

When putting in the changes to the API to do rate limiting, the tests were written using hardcoded fake authorization tokens ‘abc123’. The static code analysis is complaining about these tokens as it would be a security incident if real tokens were committed to the repository.
- Try a workaround for the static code analysis complaints by using a (non-existant) environment variable
- Re-organize the route unit tests to group them by endpoint
- Alphabetize the route unit tests by endpoint and then by HTTP verb
- Provide missing code coverage of the route for the existing unit tests (there are other routes that have no tests at all but leave those for now)
- Increase consistency for the route tests
This is a huge bunch of changes, but it's …

fix: FORMS-913 route unit tests cleanup

---

.vscode/launch.json
app/config/custom-environment-variables.json
app/frontend/README.md
app/frontend/package.json
app/package.json

some updates to the documentation related to vue 3

some updates

---

app/frontend/src/services/interceptors.js

Multiple users are reporting that they are receiving errors when doing various functions. This is really serious because if the user is idle for more than five minutes, as when filling out a long form, then they can’t save the form.
The keycloak token has a lifespan of five minutes. Every ten seconds it is checked to see if it is less than 60 seconds from expiry, and if so it is then refreshed. In other words, the token refreshes every four minutes.
In the Vue 3 code, for some reason the Axios interception is not getting the refreshed token. Perhaps it doesn’t know about Pinia reactivity (I don’t know about Pinia reactivity!).
_This is a temporary fix so that our users are not impacted. We will need to figure out what the proper fix is._

fix: FORMS-918 axios refreshed keycloak token

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/store/form.js
app/src/db/migrations/20231123172822_send-team-notification-email.js
app/src/forms/common/models/tables/form.js
app/src/forms/form/service.js

This pull request aims to fix the "Send my team a notification" functionality. The problem with this feature was that if this setting gets turned on and the associated field is populated with an email address, and later the option gets unticked, emails would still get sent. This is due to the fact that the field associated with the entered email does not get cleared after unticking the checkbox. 
This fix involves adding a new column into the "Form" table to keep track of whether the form owner wants to receive emails to their team members after submissions or not. 

fix: Forms-924 'send my team a notification' still sending a notification even if unselected

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

the check for whether a variable is a string or number wasn't working, it should be working now

removes double quotes

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

vuetify can't seem to render anything that isn't a string or number so it throws an error and breaks functionality of the entire submissionstable and mysubmissionstable. this converts the data being placed in the table with a stringified version.
use the following link to create a submission and then view your previous submissions. select all the columns and it should not break.
https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-1165/form/submit?f=6c1652b1-97b2-4ded-ab47-a2a53a42fcbd
Fixes: https://bcdevex.atlassian.net/browse/FORMS-929

fixes the select columns breaking things

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/settings/FormSubmissionSettings.vue
app/frontend/src/store/form.js
app/frontend/tests/unit/components/designer/settings/FormSubmissionSettings.spec.js
app/src/db/migrations/20231123172822_send-team-notification-email.js
app/src/docs/v1.api-spec.yaml
app/src/forms/common/models/tables/form.js
app/src/forms/email/emailService.js
app/src/forms/form/service.js
app/tests/unit/forms/email/emailService.spec.js

Forms 924 send my team a notification still sending a notification even if unselected changes

---

app/package-lock.json
app/package.json
app/src/forms/form/controller.js
app/src/forms/submission/controller.js
app/tests/unit/forms/form/controller.spec.js
app/tests/unit/forms/submission/controller.spec.js
app/tests/unit/routes/v1/form.spec.js
app/tests/unit/routes/v1/submission.spec.js

In the API we occasionally get IDs from buggy forms or systems that are invalid UUID values such as “undefined”, or “{{sumissionId}}” (sic) or a UUID with a trailing `.`. Due to how the API Is set up, these values is used in a query against the database and then database errors are used to produce HTTP 401 responses.
By doing UUID validation in the controller, we:
- Take load off the database
- Have fewer errors in the database logs. This is important because we want the database logs to contain errors about the database, not errors about the mistakes being made by our users. Once we prevent the user mistakes from hitting the database we can begin to alert on database errors - the errors we actually need to action.
- The 401 response is not correct - this should be a 400 response
Do the …

Fix/932 UUID validation

---

app/frontend/package-lock.json
app/frontend/package.json

Formio upgrade

---

app/frontend/package-lock.json
app/frontend/package.json

upgrading formio to version 5

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/admin/AdminFormsTable.vue
app/frontend/src/components/base/BaseNotificationBar.vue
app/frontend/src/components/bcgov/BCGovAlertBanner.vue
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/internationalization/trans/chefs/ar/ar.json
app/frontend/src/views/Error.vue
app/frontend/src/views/form/Success.vue
app/frontend/tests/unit/components/admin/AdministerFormsTable.spec.js

The following PR aims to fix issues introduced in the Vue3 migration.
1) Fixed few translation issues
- few alerts/error notifications not translating
- form table headers not properly translating on language change
2) Fixed the logic in the active forms in the Admin Page - it would display the "deleted" header for active forms, but would not for the deleted forms. 
More info can be found here: https://bcdevex.atlassian.net/browse/FORMS-925

fix: Forms-925 translations and other minor vue 3 frontend problems

---

app/src/docs/v1.api-spec.yaml

Removed empty parameter in spec docs.

fix: removed parameter from API spec docs

---

app/package-lock.json
app/package.json
app/src/docs/v1.api-spec.yaml
app/src/forms/form/controller.js
app/tests/unit/forms/form/controller.spec.js
app/tests/unit/routes/v1/form.spec.js

The API is currently set up so that bad data from API Key callers is typically caught in the database queries. This add a small amount of load to the database, but more importantly it causes errors in the database logs. We cannot alert on errors in the database logs until the errors due to API Key users are prevented.
In other words, errors in the database logs should be for _database_ errors, not _user_ errors. We can’t control the _user_ errors and they add noise to the database logs. Since we must investigate and correct the _database_ errors, we want the logs as clean as possible.
> NOTE: this is sort of a proof-of-concept for the two endpoints where we commonly see strange UUIDs. If it works well then it should eventually be done for …

fix: FORMS-940 Validate UUIDs in the controller

---

app/frontend/src/assets/scss/style.scss

Words in [form.io](http://form.io/) tables are set up to be “break-all”, which means that any time the text is broken across multiple lines it is being broken in the middle of words. This makes things very unreadable, especially on small screens.
Browser:
Mobile:
Browser:
Mobile:

fix: FORMS-947 form.io - only break words when necessary

---

app/frontend/src/components/designer/FormViewer.vue

The JEDI folks reported that file attachments are causing 403 errors. This was reproduced in dev using a new form containing a Data Grid containing a File Upload component. The form was saved and previewed, and a couple of dozen of attachments were added, and it worked fine. Waited 15 minutes and tried again and it failed with a 403. Probably has nothing to do with the Data Grid either, just the amount of time since the form was opened, and probably something about the SSO token timeout.
Later confirmed that all is needed to do to reproduce is:
1. Create a new form
2. Add a File Upload component
3. Save the form
4. Preview the form
5. Attach a file
6. Delete the file
7. Wait five minutes
8. Attach a file
This should be viewed as a …

fix: FORMS-951 file upload workaround for auth store reactivity problem

---

app/src/components/log.js

Some extra fields in the HTTP logs would greatly help us diagnose problems using the logs.
We see API calls like `GET /app/api/v1/files/{fileId}` with an invalid `fileId`. Since there is no `formId` or other value in the call, we cannot get an idea of who is making it. When API calls are made with a Form ID and API Key, it would be very useful if we would log the Form ID. We could update `app/src/components/log.js` in the `dynamicMeta` info to include:
```javascript
formId: (req.auth && req.auth.user) || undefined,
```
We see errors in the logs but it’s sometimes difficult to track down how the error occurred. One of the difficulties is that when there are multiple simultaneous users, it’s tricky to tell who is making which API call. This would be made easier if the username of the logged …

feat: FORMS-945 add diagnostic info to the http logs

---

app/frontend/src/components/forms/FormSubmission.vue

User is reporting that the “Notes” is not updating on the submission view page after they assign the submission. A refresh of the page fixes this. There is an error notification being produced.
Steps to reproduce:
1. Create a new form
2. In the Manage Form section enable “Reviewers can Update the Status of this form”
3. Create a submission
4. View the submission
5. Assign the submission, click “Attach Comment to Email”, and enter a comment
An error notification appears.
The “Notes” is not updated. Refresh the page and it will be updated with the assignment note. The error is probably preventing the automatic page update. Email is working as expected, though.

fix: FORMS-953 submission assignment with email notes error

---

.github/workflows/codeql-analysis.yaml
.github/workflows/on_pr_closed.yaml
.github/workflows/on_pr_opened.yaml
.github/workflows/on_push.yaml
.github/workflows/owasp-zap-scan.yaml

The best practice for GitHub repositories is to use “main” as the name of the default branch. The CHEFS repository was created before this best practice existed, so we need to rename our default branch to “main”.
We also have to update the GitHub Actions to use the correct branch when pulling the code.
All users clones will need to:
```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
Chore (work unrelated to the running application)
I think that this needs to be merged before the default branch is renamed. Then the next PR will have everything in place to run (???).

chore: FORMS-955 rename repo default branch to main

---

app/app.js

The new custom Rate Limiter middleware for Express is causing the following error message on the first basic auth call to the API:
> ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
This could indicate that we are rate limiting based on a proxy IP address rather than the original IP address of the requester. Need to double-check that this is not the case.
Also look at the IP address being logged - these do not seem to be IP addresses of the requesters, but rather something in between. The problem is probably that we’re …

fix: FORMS-954 express update to handle proxied ip addresses

---

app/app.js

The new custom Rate Limiter middleware for Express is causing the following error message on the first basic auth call to the API:
> ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
This could indicate that we are rate limiting based on a proxy IP address rather than the original IP address of the requester. Need to double-check that this is not the case.
Also look at the IP address being logged - these do not seem to be IP addresses of the requesters, but rather something in between. The problem is probably that we’re …

fix: FORMS-954 express proxy configuration

---

app/app.js

Revert this to break the rate limiting. It looks like it's not strict enough when it's working correctly.

URGENT: Revert the proxy fix

---

app/frontend/src/services/interceptors.js

urgent - increase frontend timeout

---

app/src/forms/auth/middleware/userAccess.js

Temporary commit to troubleshoot why frontend calls are taking so long.

temp: check timing in submission permissions

---

app/src/forms/auth/middleware/userAccess.js

undo: check timing in submission permissions

---

app/app.js

This was removed when we were having performance issues. Putting it back in so that misbehaving users don't affect others using the same proxy.

fix: FORMS-954 express handle proxied ip addresses

---

app/src/forms/rbac/routes.js
app/src/forms/rbac/service.js

The API is set up to load the active forms and deleted forms for all API calls. For example, to get a form the API will get the permissions for all active forms and all deleted forms, and then it will pull the one form out of active or deleted to check permissions. We cannot afford these expensive database queries on every API call.
Change the API so that it only fetches the one form that is required to check permissions. Only do the active if the deleted fail.
Since this is a big scary change, only do one set of endpoints at a time. There will need to be a lot of manual testing to check this out.
Next: the last of the routes using currentUser.forms: the /rbac routes.
Didn't add a test for this, and we're missing most tests for the rbac …

fix: FORMS-959 optimize the /rbac routes

---

app/src/forms/rbac/service.js

fix: FORMS-959 emergency fix for /rbac routes

---

app/src/forms/auth/middleware/userAccess.js
app/src/forms/auth/service.js
app/src/forms/form/routes.js
app/src/forms/rbac/routes.js
app/src/forms/submission/routes.js
app/tests/unit/forms/auth/authService.spec.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

The API is set up to load the active forms and deleted forms for all API calls. For example, to get a form the API will get the permissions for all active forms and all deleted forms, and then it will pull the one form out of active or deleted to check permissions. We cannot afford these expensive database queries on every API call.
Change the API so that it only fetches the one form that is required to check permissions. Only do the active if the deleted fail.
Since this is a big scary change, only do one set of endpoints at a time. There will need to be a lot of manual testing to check this out.
This is the final chunk of work: get rid of the "temp" function and then do cleanup. This change will then cover all routes.

fix: FORMS-959 optimize all routes and do cleanup

---

app/src/forms/auth/middleware/userAccess.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

Emergency fix for errors in logs due to FORMS-959 changes.

fix: FORMS-959 form roles methods failing

---

app/src/forms/auth/middleware/userAccess.js

A less-hasty fix of the problem, now with no errors _and_ functioning correctly.

fix: FORMS-959 form roles methods incorrect

---

app/frontend/src/views/File.vue
app/frontend/src/views/file/Download.vue

we had to ignore the conditional for if there was any data in the download.. no submissions means no data. export needs to be fixed again though because the base headers should exist

fixed file download

---

.github/workflows/on_pr_opened_collaborator.yaml

Currently, we have a system in place that prevents anyone except specific required reviewers from promoting changes up to production after it’s been merged. This is a manual workflow trigger which uses the github environment settings.
Ideally, we’d like it so that collaborators and the owner can simply automatically deploy to the PR environment without intervention from other collaborators once they create a pull request into main from anywhere. We’d also like anyone else to be able to create a pull request from anywhere but require collaborator or owner intervention to manually deploy it to the pull request environment.
This requires us to create to separate Github environments, one for the pr environment which our internal team uses which bypasses collaborator intervention and one for …

improved pr workflow

---

.github/workflows/on_pr_opened.yaml
.github/workflows/on_pr_opened_collaborator.yaml

prevents non collaborator workflow from running when a pull request is created by a collaborator. adds the environment to the collaborator workflow, this might fix the build issue.

minor changes to workflow

---

.github/workflows/.close-pr.yaml
.github/workflows/.deploy.yaml

removed id from job and fixed close pull request name

removed id from job

---

.github/workflows/.deploy.yaml

adds the environment to the deployment

fix deployment

---

.github/workflows/on-push.yaml

Temporarily restoring the "On Push" workflow so that a change for AF can be deployed.

ci: FORMS-848 temporarily restore on-push workflow

---

app/config/default.json

A team making API Key calls is doing their UAT and they are hitting the rate limit. Performance improvements to our API have dropped our response times to 10-20% of what they were pre-November. It should be fine to double the rate limit.

feat: FORMS-1002 increase api key rate limit

---

.github/workflows/.deploy.yaml

pr number was not injected because the syntax was not correct

pr number was not injected

---

app/src/forms/auth/middleware/userAccess.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

Refactor the currentUser middleware:
- use a try/catch for middleware so that we never leave the request hanging
- always call next() just to make things simpler to understand and test
- use optional chaining for req items rather than try/catch or a bunch of tests
Refactor (improve code readability and consistency)
Tests (improve automated testing)

refactor: FORMS-965 update the userAccess.currentUser middleware and tests

---

.github/workflows/.deploy.yaml
.github/workflows/on_push.yaml

restores the old workflow for promoting builds up to production.

restores the old workflow for deploying to dev/test/prod

---

.github/workflows/.deploy.yaml

Updating the message displayed when running the workflow.
Continuous Integration (non-breaking change to pipeline)

ci/update .deploy.yaml input arg message

---

.github/workflows/.deploy.yaml

Update the deploy workflow to use v4 of the checkout action. The v3 version is based on Node 16 and GitHub is complaining about it being deprecated.
Continuous Integration (non-breaking change to pipeline)

ci/update .deploy.yaml checkout version

---

app/src/docs/v1.api-spec.yaml

The SSO work is a big change that requires us to communicate the changes to all our clients. Since we are doing this communication it would be a good time to fix a longstanding bug: authentication failures are returning HTTP status 403 (Forbidden) when they should be returning 401 (Unauthorized).
PR1258 will make the 403->401 change, but the API documentation also needs to be updated. Putting the docs into a separate ticket/PR since they need to be done anyway and can be done out of sync with the PR1258 deployment (and done early if possible).
Major changes:
- Document that nearly every endpoint can return 401 and 403 responses
- Update the docs to provide the schema and examples for 401 and 403
- For consistency rename the `UnauthorizedError` response simply to `Unauthorized`
Minor …

docs: FORMS-1047 http 401 and 403 for most endpoints

---

app/src/db/migrations/20240312164557_remove-confirmationid-constraint.js

There’s a constraint in the database that a submission’s `confirmationId` has to be unique. We just had a collision in production, and someone’s submission failed because of the constraint. Need to double-check that this uniqueness is never relied on.
The `confirmationId` can’t be considered unique because the keyspace (16^8 = ~4 billion) is too small. The `id` is essentially unique, but the `confirmationId` should assume collisions, even within the same form.
A quick scan of the backend code didn't come up with any obvious places where unique `submissionId`s are needed. Thinking it's best to fix the problem so that submissions don't fail, and then if we do have problems with duplicates we at least have the data and can write tests and then fix the problems.
Bug fix (non-breaking change …

fix: FORMS-1048 remove submission id unique constraint

---

app/frontend/src/App.vue

Reverts bcgov/common-hosted-form-service#1302
Upon further discussion, some more work needs to be done so that these changes do not impact all the users.

Revert "feat: Expanding container width while viewing Forms and Submissions"

---

app/src/components/errorToProblem.js

The error logger is logging error information but isn’t including the full error and its stack trace. It’s more difficult to track down errors when the information is incomplete.

fix: FORMS-1065 include stack traces with error messages

---

app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/submission/NotesPanel.vue
app/frontend/src/plugins/vuetify.js

Moves the status panel and the notes panel to the top of the view when a submission reviewer is viewing a submission.

Forms 1039 view submission real estate

---

app/frontend/src/components/forms/PrintOptions.vue

The CDOGS template print has stopped working after the recent merge. This PR fixes it.

Hotfix: CDOGS Template Print Not Working

---

app/frontend/src/components/forms/submission/StatusPanel.vue
app/frontend/src/store/auth.js
app/frontend/src/store/identityProviders.js
app/frontend/tests/unit/fixtures/identityProviders.json
app/frontend/tests/unit/store/modules/auth.getters.spec.js

Status Panel - Assign to me not working after move to Standard Realm.
https://bcdevex.atlassian.net/browse/FORMS-1151
Update token parsing for current user idpUserId.
Also, for Agriculture BRMB, setting the `user.username` to be `idir_username` (ex. JASHERMA) as it was in the custom realm (BCeID will pull from a different value in the token but end result is username is same as in our custom realm).

Assign to Me - not working

---

app/package-lock.json
app/package.json

When we install the backend packages there are some warnings about packages that are no longer maintained. Update the backend devDependencies to use latest packages and their dependencies.
Note: just did `nodemon` as updating ESLint to latest involves a rewrite of the config file, and we should probably also switch to using one config instead of two or three (or four?).

fix: FORMS-1223 update nodemon dependency

---

app/frontend/src/components/base/BaseAuthButton.vue
app/frontend/src/router.js
app/frontend/tests/unit/components/base/BaseAuthButton.spec.js
app/frontend/tests/unit/views/form/Create.spec.js
app/frontend/tests/unit/views/form/Design.spec.js

login button was showing even though the user was authenticated. removed it and removed from the router all instances of hasLogin because it gets set in the router but never actually used anywhere except in BaseAuthButton. BaseAuthButton can already check if the user is authenticated by the store though.

Login button visible

---

app/frontend/src/components/base/BaseAuthButton.vue
app/frontend/src/router.js
app/frontend/tests/unit/components/base/BaseAuthButton.spec.js
app/frontend/tests/unit/views/form/Create.spec.js
app/frontend/tests/unit/views/form/Design.spec.js

Reverts bcgov/common-hosted-form-service#1350

Revert "Login button visible"

---

app/src/forms/auth/middleware/userAccess.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

Code Climate has a bunch of complaints about `userAccess.hasSubmissionPermissions`. Refactor it to clean up the code an improve the score.
Currently `userAccess` has a Maintainability rating of `F` (4 days) and Test Coverage of `B` (83%).
Refactor (non-breaking change to improve code quality)

refactor: FORMS-1241 clean up hasSubmissionPermissions

---

app/frontend/src/internationalization/trans/chefs/ar/ar.json
app/frontend/src/internationalization/trans/chefs/de/de.json
app/frontend/src/internationalization/trans/chefs/en/en.json
app/frontend/src/internationalization/trans/chefs/es/es.json
app/frontend/src/internationalization/trans/chefs/fa/fa.json
app/frontend/src/internationalization/trans/chefs/fr/fr.json
app/frontend/src/internationalization/trans/chefs/hi/hi.json
app/frontend/src/internationalization/trans/chefs/it/it.json
app/frontend/src/internationalization/trans/chefs/ja/ja.json
app/frontend/src/internationalization/trans/chefs/ko/ko.json
app/frontend/src/internationalization/trans/chefs/pa/pa.json
app/frontend/src/internationalization/trans/chefs/pt/pt.json
app/frontend/src/internationalization/trans/chefs/ru/ru.json
app/frontend/src/internationalization/trans/chefs/tl/tl.json
app/frontend/src/internationalization/trans/chefs/uk/uk.json
app/frontend/src/internationalization/trans/chefs/vi/vi.json
app/frontend/src/internationalization/trans/chefs/zh/zh.json
app/frontend/src/internationalization/trans/chefs/zhTW/zh-TW.json

The error message for the CDOGS template lists pdf as an accepted input type but its not. 

Fix: Update invalidFileMessage

---

app/src/forms/auth/middleware/userAccess.js

This is work to improve the Code Climate scores for this file:
- `_formHasPermissions` takes a `form` as a parameter and then only uses the `permissions` attribute of that object. It would be better if it took the `permissions` themselves
- `_formHasPermissions` returns false if there are no permissions to check. This allows shortcutting the existence of the form
- Change `_getForm` to not throw a Problem if the form is not found - this will allow it to be re-used in simplifying `hasSubmissionPermissions`.
Refactor (no change in functionality but improves code quality)
No tests - this should pass all existing tests as there is no change to the functionality.

refactor: FORMS-1245 simplify hasSubmissionPermissions

---

app/src/forms/auth/middleware/userAccess.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

Refactoring the user access middleware to reduce redundancy and improve readability.
- rename `_formHasPermissions` to `_hasAllPermissions`
- add new `_hasAnyPermission`
For `hasFormRoles`:
- get rid of the unused `hasAll` parameter
- wrap the function in `try`/`catch` to ensure that requests don't hang
- use `_getForm` instead of having duplicate code
- replace the for loop iterating through roles with a call to the new `_hasAnyPermission`
Refactor (no change in functionality, but improves code quality)
Includes a rewrite of the tests now that the function is wrapped in a try/catch block and forwards Problems instead of handling them.

refactor: FORMS-1245 simplify hasFormRoles

---

app/src/forms/auth/middleware/userAccess.js

In `userAccess.hasRolePermissions` Problems were being created in four different ways:
1. Create Problem and call `next` and end the request (code smell - early returns)
1. Create Problem and call `next` without ending the request (code smell - early returns)
1. Create Problem and return it  (code smell - early returns) (!!! Returning without calling `next` is a bug and the request will hang indefinitely)
1. Create Problem and throw it, which is caught and calls `next` with it
For consistency standardize on the last way of doing things. It's confusing when reading the code and there are four different ways - in a single function - of doing the same thing.
Also:
- make the Problem creation code consistent with detail always on its own line, even if it's short enough for the whole create to …

refactor: FORMS-1265 create new problems in a consistent way

---

app/src/forms/auth/middleware/userAccess.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

Updated the `userAccess.currentUser` tests to add some test cases that were missing, and remove some that are not needed.
Also noticed that now that we have a JWT service we should simplify this code. The first half is just error handling for bad/expired tokens, so maybe the service could have added `hasBearerToken` and `hasValidBearerToken` or similar.
Note: also alphabetized the code in `userAccess` so that file looks like a lot of changes but functionally it's the same.
Test (test code with no changes to functionality)

test: FORMS-1265 rewrite current user tests

---

app/src/forms/auth/middleware/userAccess.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

CodeClimate has a few complaints about the repetition of code within hasRolePermissions, as well as the length of the function. Ideally it should be split into two function (one for delete, one for put) but that can wait for now.
Refactor (no change in functionality, but improvements in code quality)

refactor: FORMS-1265 reduce hasRolePermissions code repetition

---

app/src/db/dataConnection.js
app/src/db/stamps.js
app/src/forms/common/middleware/dataErrors.js
app/tests/unit/forms/common/middleware/dataErrors.spec.js

We have UniqueViolationError exceptions being thrown in various places, and they are producing 500 responses. Instead we should be handling these in the error handler and returning a 422. 
See comments on the changes.

fix: FORMS-991 handle db unique violation errors

---

app/src/forms/auth/middleware/userAccess.js
app/src/forms/submission/routes.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js
app/tests/unit/routes/v1/submission.spec.js

Write tests to get complete coverage for the `userAccess.js` collection of middleware. Tried to do as little refactoring as possible, but to make the tests easier:
- Change `filterMultipleSubmissions` to not return middleware, it *is* middleware (no parameters)
- Use the well-used and -tested `_getForm` instead of doing it by hand
Refactor (no change in functionality, but improve code quality)
Test (expand or improve test suites)

refactor: FORMS-1265 filter multiple submissions

---

app/src/forms/auth/middleware/userAccess.js
app/tests/unit/components/idpService.spec.js
app/tests/unit/components/jwtService.spec.js
app/tests/unit/forms/admin/controller.spec.js
app/tests/unit/forms/auth/authService.spec.js
app/tests/unit/forms/auth/middleware/apiAccess.spec.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js
app/tests/unit/forms/bcgeoaddress/controller.spec.js
app/tests/unit/forms/bcgeoaddress/service.spec.js
app/tests/unit/forms/common/middleware/rateLimiter.spec.js
app/tests/unit/forms/email/emailService.spec.js
app/tests/unit/forms/file/middleware/filePermissions.spec.js
app/tests/unit/forms/form/controller.spec.js
app/tests/unit/forms/form/exportService.spec.js
app/tests/unit/forms/form/routes.spec.js
app/tests/unit/forms/form/service.spec.js
app/tests/unit/forms/rbac/controller.spec.js
app/tests/unit/forms/submission/routes.spec.js
app/tests/unit/forms/submission/service.spec.js
app/tests/unit/forms/user/service.spec.js
app/tests/unit/routes/v1/admin.spec.js
app/tests/unit/routes/v1/form.spec.js
app/tests/unit/routes/v1/submission.spec.js

Updated the backend unit tests to be more consistent:
- use `toBeCalled...` rather than `toHaveBeenCalled...`. They're the same thing but we were using both. Standardize on the shorter one
- add a TODO comment to `userAccess.js` for code that testing uncovered as being not possible (small change but not making it on my friday)
- fix descriptions and add a missing test in `userAccess.spec.js`
- update the `filePermissions.spec.js` tests to use the `@jest-mock/express` way of doing things, rather than custom code
- organize the test structure in `filePermissions.spec.js` to group things a little better
Test (non-breaking change that only involves the test suites)

test: FORMS-1265 improve test consistency and coverage

---

app/src/forms/form/service.js
app/tests/unit/forms/form/service.spec.js

Had some 500 responses in production because a custom API call to get submissions was requesting an SQL `ORDER BY` for a column that wasn't in the `SELECT`. Added a check that the `ORDER BY` is among the columns selected.
Did a little refactoring of similar code so that I didn't have to duplicate the check.

fix: FORMS-1038 handle sort by column not existing

---

openshift/app.cronjob.yaml

RedHat Advanced Cluster Security identified the cron job image as having vulnerabilities that have fixes available. Update the image to curl:8.8.0.

fix: FORMS-1284 update cronjob curl image

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
Dockerfile

RedHat Advanced Cluster Security (ACS) has identified fixable security vulnerabilities in the `node:18.18.2-alpine` image.
- Updating the app to use `node:18.20.3-alpine3.20` (was `alpine3.18`)
- Updating the devcontainer to the matching node version
- Updating the devcontainer to use the latest Debian `bookworm` (was `bullseye`)
After rebasing, VSCode should prompt for a container rebuild. The only change I noticed was that `npm` switched from v9 to v10.

fix: FORMS-1287 update node image

---

app/src/forms/common/middleware/dataErrors.js
app/tests/unit/forms/common/middleware/dataErrors.spec.js

Sending invalid JSON to the API produces a 500 response, even though Express produces the expected 400 error.
Added a new error handling clause that deals with non-Problem Errors that have a `status` or `statusCode`.

fix: FORMS-1139 handle express errors

---

app/package-lock.json
app/package.json

Update the API Problem package. This package is used to produce informative HTTP responses that include a `title`, `detail`, etc.
The major change from version 7 of `api-problem.js` to version 9 is that the `type` field will now reference a page on MDN rather than `httpstatuses.com`, which is now being used to serve ads.
Old v7 responses:
```json
{
"type": "https://httpstatuses.com/401",
"title": "Unauthorized",
"status": 401,
"detail": "You do not have access to this form."
}
```
New v9 responses:
```json
{
"type": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401",
"title": "Unauthorized",
"status": 401,
"detail": "You do not have access to this form."
}
```

fix: FORMS-1139 update api-problem

---

app/app.js
app/src/forms/common/middleware/errorHandler.js
app/src/forms/common/middleware/index.js
app/tests/unit/forms/common/middleware/errorHandler.spec.js

Do some final cleanup on the FORMS-1139 work: rename the `dataErrors` module to `errorHandler`, since it does more than just deal with data errors.
Refactor (non-breaking change that improves code quality)

refactor: FORMS-1139 rename dataErrors to errorHandler

---

app/src/forms/common/middleware/errorHandler.js
app/tests/unit/forms/common/middleware/errorHandler.spec.js

CodeClimate is complaining that the new error handler is too complex. Split the Objection error handling out into its own method, to separate it from the other errors.
Refactor (non-breaking change which improves code quality)

refactor: FORMS-1139 add db error handler

---

.github/pull_request_template.md

Update the PR template to include all the types included in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). Hopefully we'll eventually document the expected way of working for commits and PRs and such, but in the meantime this gets us a little closer to being able to automate our changelog.

docs: FORMS-1302 update pr template

---

app/frontend/src/components/forms/ExportSubmissions.vue

It was reported that exporting submissions containing Indigenous language characters is not working correctly for CSV exports. The export is fine for JSON, and the CSV when opened in Notepad contains the correct data. The problem is when loading the CSV export into Excel, then the data becomes garbled.
As an example:
- The text `Nəxʷsƛ̕ay̓əmúcən` appears in Excel as `NÉ™xÊ·sÆ›Ì•ayÌ"É™mÃºcÉ™n`
- The text `nk̓ iʔ snm̓am̓áyaʔtn iʔ k̓l sqilxʷtət` appears in Excel as `nkÌ" iÊ" snmÌ"amÌ"aÌyaÊ"tn iÊ" kÌ"l sqilxÊ·tÉ™t`
There is an excellent write-up on the problem, including proposed solutions, in: https://github.com/bcgov/inclusive-names-service/blob/main/docs/file_formats/csv_excel/csv.md
Solution: add a Byte Order Mark (BOM) to the exports.
Risk: this is a change to the CSV output, so there …

fix: FORMS-883 help Excel with BCSans CSVs

---

app/tests/unit/forms/file/routes.spec.js

Added new tests for `forms/file/routes.js`.

test: FORMS-1292 new file routes tests

---

app/tests/unit/forms/file/controller.spec.js

Added tests for the `form/file/controller.js` module. They're not super-exhaustive but they did uncover:
- a branch that shouldn't be possible
- a response code that isn't correct

test: FORMS-1292 new file controller tests

---

app/frontend/src/components/forms/submission/StatusPanel.vue

To add some input validation on a submission's 'Revising' status, input was limited to only the form reviewers, and typing an email was disabled. However, this prevents the 'Revising' status from being assigned to the form submitter.
This fix combines reverts the changes as some users are having issues with the new feature. Pushing this fix while the feature is completed. 

Fix: Revert Dropdown for Revising Status

---

app/app.js

The OWASP Zap Scan process has identified a **MEDIUM** risk level vulnerability:
> 1 proxy server(s) were detected or fingerprinted. This information helps a potential attacker to determine
> - A list of targets for an attack against the application.
> - Potential vulnerabilities on the proxy servers that service the application.
> - The presence or absence of any proxy-based components that might cause attacks against the application to be detected, prevented, or mitigated.
To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be remediated.
Solution: Configure all proxies, application servers, and web servers to prevent disclosure of the technology and version information in the 'Server' and …

fix: FORMS-1367 remove Express powered-by header

---

components/package-lock.json

Resolves the moderate vulnerability in the `semver` package. Updates the package to the latest non-vulnerable version, thus resolving the final dependabot vulnerability alert. 

Update: semver vulnerable to Regular Expression Denial of Service

---

.github/workflows/codeql-analysis.yaml

Update the CodeQL Actions versions as v2 will no longer be supported after December.

ci: FORMS-1228 update codeql version

---

.github/workflows/pr_deploy.yaml
.github/workflows/pr_undeploy.yaml

Rename the Actions:
- `Close pull request deployment` -> `PR Undeploy` (since the Action doesn't close the PR, it undeploys it)
- `Deploy PR` -> `PR Deploy` (so that the two PR Actions are located next to each other in the list)
Do a little cleanup too:
- No need to specify that the undeploy is in dev
- Add the PR number to the undeploy run name
- Try to get multiple deploys to write to the PR multiple times
- Remove a bunch of logic that we no longer need

ci: FORMS-1405 update un/deploy actions

---

.github/workflows/pr_deploy.yaml

Tried to improve the deployment message but I think there's a better way: instead of appending, mark the old one as outdated and create a new one. This way we have an updated timestamp.

ci: FORMS-1405 better deploy message

---

openshift/app.cronjob.yaml

The Red Hat Advanced Cluster Security (ACS) application has identified the image `curl` as having vulnerabilities that are fixable. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this image must be updated to resolve fixable vulnerabilities (or mitigated in some other way, if updating the image is not possible).

fix: FORMS-1406 update cronjob curl image

---

app/src/forms/common/middleware/validateParameter.js

Pre-work for the submission ID validation: put the functions and exports into alphabetical order.
Refactoring, so no tests needed - the test is that the existing tests still pass.

refactor: FORMS-1237 alphabetize functions

---

app/frontend/package-lock.json
app/frontend/package.json

Reverts bcgov/common-hosted-form-service#1458

Revert "Update formiojs"

---

app/tests/unit/forms/admin/routes.spec.js
app/tests/unit/forms/bcgeoaddress/routes.spec.js
app/tests/unit/forms/form/routes.spec.js
app/tests/unit/forms/user/routes.spec.js

Added unit tests for all the routes in `form/routes.js`. This is a first step before converting the existing routes tests (which test the controllers, not the routes) into controller tests.

test : FORMS-1444 update forms routes tests

---

app/tests/unit/forms/admin/routes.spec.js
app/tests/unit/forms/bcgeoaddress/routes.spec.js
app/tests/unit/forms/file/routes.spec.js
app/tests/unit/forms/form/externalApi/routes.spec.js
app/tests/unit/forms/form/routes.spec.js

Added unit tests for all the routes in `form/externalApi/routes.js`. Also:
- alphabetized the tests by HTTP verb
- added missing tests and noticed that some of the routes are overloaded and we should maybe separate them in the future
Also:
- for other tests standardized on having the controller mocks into the tests themselves, rather than having a huge bunch of them at the top
- for other tests standardized on having the test UUIDs in the describe clauses that need them

test: FORMS-1444 external api routes

---

app/src/forms/common/middleware/validateParameter.js
app/tests/unit/forms/common/middleware/validateParameter.spec.js

404 thrown when using admin screen to approve an external api. The underlying issue was the middleware validating the external api id was expecting a formId. This makes sense in most use cases as we want to ensure the external api belongs to a particular form for permissions. In Admin use, we just want to ensure the id is UUID and exists.
Fix made to allow verifying only the external api id with a new test added.
Fixes [FORMS-1740](https://bcdevex.atlassian.net/browse/FORMS-1470?atlOrigin=eyJpIjoiNjEyYzFlMGU5ODRiNDdmNWJhM2ExYTlhNzA4MGM4NDciLCJwIjoiaiJ9)

Adjust external api id middleware for admin routes

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/tests/unit/components/forms/SubmissionsTable.spec.js

fixed the issue with pagination and sort not working
- [x ] I have approval from the product owner for the contribution in this pull request

fixed SubmissionsTable

---

openshift/redash/redis.deploy.yaml

The Red Hat Advanced Cluster Security (ACS) application has identified the image redis as having vulnerabilities that are fixable. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this image must be updated to resolve fixable vulnerabilities (or mitigated in some other way, if updating the image is not possible).
> Old version: 7.2.5-alpine3.20
> New version: 7.4.0-alpine3.20

build: FORMS-1459 update redash redis to 7.4.0

---

app/frontend/package-lock.json
components/package-lock.json

Updates dependencies to resolve 3 dependabot vulnerabilities. 
Axios: https://github.com/bcgov/common-hosted-form-service/security/dependabot/176
Webpack: https://github.com/bcgov/common-hosted-form-service/security/dependabot/182
Micromaatch: https://github.com/bcgov/common-hosted-form-service/security/dependabot/181
https://bcdevex.atlassian.net/browse/FORMS-1460

Fix: Dependabot Vulnerabilities 

---

openshift/app.cronjob.yaml

The Red Hat Advanced Cluster Security (ACS) application has identified the image `curl` as having vulnerabilities that are fixable. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this image must be updated to resolve fixable vulnerabilities (or mitigated in some other way, if updating the image is not possible).
> Old version: 8.9.0
> New version: 8.10.0
- The image version is updated in the repo
- The image version is updated in the deploys

build: FORMS-1458 update curl to 8.10.0

---

app/frontend/src/components/forms/manage/ExternalAPIs.vue

Update the External API help link to the Tech Docs article.

FORMS-1325: Update Ext API Tech docs link

---

.github/actions/deploy-to-environment/action.yaml

The GitHub Actions runner "ubuntu-latest" has changed from 22.04 to 24.04. This later version does not include the "oc" command. Explicitly install this command.

fix: FORMS-1539 add oc to actions containers

---

app/frontend/src/store/form.js

Fix errors when fetching existing forms without metadata.
Related to #1509.
Issue only evident when using data that existed before the change.
Error when loading a form that exists without metadata. Need to initialize form.formMetadata on fetch so Update Settings will work.

FORMS-1412 - Update fetchForm in formStore.

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/tests/unit/components/designer/FormViewer.spec.js
app/src/forms/common/utils.js
app/tests/unit/forms/common/utils.spec.js

Forms are closing earlier than they should be when using the scheduling feature. This may be due to the difference between local time and UTC time on the server. The default message for when the submission is not available as the scheduled submission period has expired rather than the custom message is being shown.
This resolves: https://bcdevex.atlassian.net/browse/FORMS-1586
The biggest change is that we no longer format the date so we can keep it a moment object instead of a string. We also set the closing date to be the end of the date, since we're using a date and not a date time, it was assuming start of the day.

fix: FORMS-1586 scheduler errors

---

app/package-lock.json

The GitHub Dependabot process has created an alert for the cross-spawn dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/213
- Dependabot no longer complains about the vulnerability

fix: FORMS-1598 update cross-spawn to fix vulnerability

---

event-stream-service/charts/event-stream-service/templates/nats-nsp.yaml
event-stream-service/charts/event-stream-service/values-prod.yaml
event-stream-service/charts/event-stream-service/values-test.yaml
event-stream-service/charts/event-stream-service/values.yaml
openshift/app.dc.yaml

Add Network Policies for Event Stream Service deployments to allow CHEFS namespaces to use NATS protocol. Set policies to be as restrictive as possible and to only connect to the NATS pods.
We still need to support websocket connections as consumers will be anywhere.
This does not change CHEFS code or configuration (or network policies), there will be another PR to address that as there will be UX and configuration changes.
Old/redundant network policies will be removed manually.

FORMS-1495: Network Policies for NATS protocol

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/unit-tests.yaml
Dockerfile
app/frontend/tests/unit/components/designer/settings/FormEventStreamSettings.spec.js
app/frontend/vite.config.mjs

Node.js is how we run the JavaScript code that makes up the application. The version that we choose is in the “sweet spot” where it’s a long term support (LTS) version that is still maintained, but it isn’t be actively developed (fewer changes).
We use Node.js in three places:
1. The running CHEFS application, frontend and backend, in the deployed PRs, dev, test, and prod
1. The “devcontainers” used by developers to work on the application
1. The GitHub Actions that are the Continuous Integration / Continuous Deployment (CI/CD) pipeline used to automatically build, test, and deploy the application
> Note: in changing the Action the tests are not running in Node v18, but those are "branch protection" tests for main. Once this PR is merged, the rules should be updated to …

fix: FORMS-1588 update Node.js to v20

---

.devcontainer/Dockerfile

The Cypress tests cannot be run in the devcontainers due to missing packages in the Debian Bookworm container. These packages are described in https://docs.cypress.io/app/get-started/install-cypress#UbuntuDebian. We need to install these packages.
1. The Cypress tests run in the devcontainers
1. NOT REQUIRED: That the tests pass - future work will be needed for this, but if the tests are at least running then dependency updates can be checked to make sure that they don’t break anything.

test: FORMS-1682 install the Cypress pre-requisites

---

components/package-lock.json

The GitHub Dependabot process has created an alert for the `dompurify` dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/209
- We depend on `formiojs`, which has a `dompurify` dependency of ^2.3.4
- Our `package-lock.json` currently has v2.3.8 of `dompurify`
- The latest `dompurify` is v3.2.3 but to satisfy the `formiojs` dependency the latest v2 is v2.5.8
- There are no obvious changes of concerns in the changelog from v2.3.8 to v2.5.8
- The `dompurify` dependency no longer appears in …

build: FORMS-1688 dompurify vulnerability fix

---

app/frontend/package-lock.json
app/frontend/package.json

Vite has been identified as having security vulnerabilities. We're jumping to the next major version, so we also have to update to a newer version of @vitejs/plugin-vue.
The GitHub Dependabot process has created an alert for the `vite` dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/194
- the vulnerability no longer appears in dependabot’s list

build: FORMS-1695 fix frontend vite vulnerability

---

.github/workflows/unit-tests.yaml

After the GitHub Action runs the frontend and backend unit tests it uploads the test coverage results as artifacts. In the steps to upload the results, the retention-days is set to one day. This means that if a PR is created and it’s more than a day before the reviewer looks at it, then the code coverage reports are not available to the reviewer.
From the https://github.com/actions/upload-artifact documentation:
```sh
retention-days:
```
Suggest that we remove the setting in the Action and allow the uploader to use the default value of the repo, which is 90 days. If for some reason we are not happy with the default value in the repo, we should change it there rather than doing it in the code of the Action.
- GitHub Actions artifacts are available to reviewers when they review PRs
ci …

ci: FORMS-1698 increase actions artifact retention

---

app/frontend/src/components/admin/AdminAPIsTable.vue

Admin / External API Send API Key i18n key typo

FORMS-1701: resource key typo

---

.devcontainer/devcontainer.json
.sonarlint/connectedMode.json
README.md

FORMS-1633: SonarQube in devcontainer.
Add SonarQube to devcontainer, add SonarQube badge to main README. SonarQube is added as an extension and configured to connect to our projects SonarCloud so we work in [Connected Mode](https://docs.sonarsource.com/sonarqube-cloud/improving/sonarlint/).
When coding a file, SonarQube will analyze the file and place notifications in the Problem window. It will also give tooltips (lightbulbs, often with auto-fix). This is part of [clean as you code](https://docs.sonarsource.com/sonarqube-cloud/core-concepts/clean-as-you-code/introduction/?_gl=1*7nubrg*_gcl_au*MTY0NjgyNzQ5MS4xNzM3MzkxMDk0*_ga*MTU0MDg0Nzg4LjE3MzczOTEwOTU.*_ga_9JZ0GZ5TC6*MTczNzQ3OTkyNi41LjEuMTczNzQ5MDQ1My42MC4wLjA.)
Developers may have to tweak their container, and after a few do we should …

FORMS-1633: SonarQube in devcontainer.

---

openshift/app.cronjob.yaml

The Red Hat Advanced Cluster Security (ACS) application has identified the image `curl` as having vulnerabilities that are fixable. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this image must be updated to resolve fixable vulnerabilities (or mitigated in some other way, if updating the image is not possible).
- The `curl` image is updated and ACS is happy
> _Note: this version of the `curl` image moves us up to Alpine 3.21._

build: FORMS-1817 update curl image

---

app/frontend/package-lock.json

The GitHub Dependabot process has created an alert for the `rollup` dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/203
This is complicated by having multiple dependencies on `rollup` and those dependencies requiring different major versions. Version 4.x.x is not vulnerable and can be ignored. Version 2.x.x is vulnerable and needs to be updated to v2.79.2 or later.
- The `rollup` package no longer appears in dependabot’s list of security vulnerabilities
build (change in build system or …

build: FORMS-1705 update rollup

---

app/frontend/package-lock.json

The GitHub Dependabot process has created an alert for the `dompurify` dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/227
- The security vulnerabilities identified by dependabot are resolved  

build: FORMS-1925 update dompurify

---

app/frontend/package-lock.json
app/frontend/package.json
components/package-lock.json
components/package.json

We have dependencies on `formio.js` in both the frontend and the components projects. Ideally the version being used for both should be the same. However, the frontend is using 4.17.4 but the components is using 4.14.7. Although these two packages should be compatible, it would be best if they used the same package version.
> Note 1: the frontend has ^4.13.4 in its `package.json`, and it’s using 4.14.7. Update the `package.json` to use 4.14.7 and be strict about it (remove the semver minor version operator ^)
> Note 2: As a side effect of the components update, it will fix the security vulnerability https://github.com/bcgov/common-hosted-form-service/security/dependabot/226
- Update the frontend’s package.json to show the actual version of the package being used
- Update the component’s …

build: FORMS-1927 use consistent version of formio.js

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/store/auth.js
app/frontend/tests/unit/store/modules/auth.actions.spec.js
app/frontend/tests/unit/store/modules/auth.getters.spec.js

Update keycloak to the latest version. We are on v21, but the recent SSO update to RHBK-26 has broken logins. Update the library to v26
- the keycloak-js library is a current version
- SSO logins work correctly

build: FORMS-1960 update keycloak-js

---

components/src/components/Map/Component.ts
components/src/components/Map/services/BCGeocoderProvider.ts
components/src/components/Map/services/MapService.ts

Reverts bcgov/common-hosted-form-service#1619 (Reverting due to a bug Seen in the map ui

Revert "Forms 1676 unintended deletion bug"

---

app/frontend/src/components/designer/settings/FormEventStreamSettings.vue
app/frontend/tests/unit/components/designer/settings/FormEventStreamSettings.spec.js

Add tests for accountName/enabled.
Fix tests to ensure no hidden errors writing to stderr.
The messages to `stderr` are not errors, the tests pass, however it pollutes the test output and it indicates that something has not been setup or torn down correctly. In this case, not adding a dummy component and not mocking an api call that executes on all `mount()` calls.
Not super easy to review, so I suggest pulling it and launching vitest against the spec file and just verifying that there are no extra `stderr` messages. Or look through the github actions and look at the test output (lots of `stderr` but should not have any for FormEventStreamSettings).
See [JIRA FORMS-2083](https://citz-do.atlassian.net/browse/FORMS-2083)

Fix vitests for FormEventStreamSettings.

---

app/frontend/src/components/designer/settings/FormScheduleSettings.vue
app/frontend/src/utils/transformUtils.js
app/frontend/tests/unit/components/designer/settings/FormScheduleSettings.spec.js
app/frontend/tests/unit/utils/transformUtils.spec.js

This is  Sub task of FORMS-2171 
Identify all unused date calculation methods and any related test cases (frontend and backend)
FORMS-2213 and FORMS-2214
Removed the unused method from transformUtils.js and also removed the related tests too
and also moved the @function isDateValidForMailNotification from transformUtils.js to formSchedulesettings.vue as it is only used in one place.
So that everything related to Schedule is in one place.
This is the first PR there will be another PR to solve the main issue.

refactor: FORMS-2171 Removed Unused Date calculation Methods and tests

---

.github/workflows/clamav-image-build.yaml
clamav/README.md
clamav/charts/clamav/.gitignore
clamav/charts/clamav/.helmignore
clamav/charts/clamav/Chart.yaml
clamav/charts/clamav/README.md
clamav/charts/clamav/templates/_helpers.tpl
clamav/charts/clamav/templates/configmap.yaml
clamav/charts/clamav/templates/deployment.yaml
clamav/charts/clamav/templates/nsp.yaml
clamav/charts/clamav/templates/pdb.yaml
clamav/charts/clamav/templates/service.yaml
clamav/charts/clamav/values-dev.yaml
clamav/charts/clamav/values-test.yaml
clamav/charts/clamav/values.yaml

Add helm charts for deploying ClamAV for CHEFS namespaces.
Includes NSP limiting access to only CHEFS app pods.
For now, the charts will be run manually. Automation is not included in this Pull request.

FORMS-2260: Add Helm Charts for ClamAV

---

.github/workflows/clamav-image-build.yaml
clamav/charts/clamav/values.yaml

Rename image to prevent potential image collisions in GIthub Image Registry for BCGov. Fix image build metadata.

FORMS-2260: CHEFS ClamAV Image

---

app/frontend/src/utils/permissionUtils.js

FORMS-2295. When there was an error loading a form (for example, invalid form id), the translation key was being returned in the error notification, not the resolved translation value.
Fix the translation resolution in permissionUtils.
permissionUtils does not contain a <script> block like Vue components, so importing and leveraging the i18n is different. Also, note that consoleError also acts differently than the base notification text. consoleErrors with options require the key but the base text requires the resolved translation.

FORMS-2295 - fix translation generator

---

app/src/db/migrations/20250502163949_enable-bcsc-idp.js

BC Services Card has been enabled in PROD in SSO.
We need to enable the IDP in CHEFS so it appears as a login type/form access type.

FORMS-2316: Enable BC Services Card IDP

---

app/frontend/src/store/auth.js
app/frontend/tests/unit/store/modules/auth.getters.spec.js

When parsing the Auth. Store user object, re-use the backend logic, do not parse the token directly.
This came to light when using BC Services Card for user information in forms. The token is parsed and a user object (currentUser) created in the backend, but the frontend does its own parsing - BCSC token fields are different than IDIR token fields.
Changed the logic to call the backend for currentUser once token is verified and authenticated on the frontend.

FORMS-2322: Frontend User parsing fix

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/tests/unit/components/designer/FormViewer.spec.js
app/src/forms/file/middleware/virusScan.js
components/src/components/SimpleFile/Component.ts

Unexpected behaviour with the queue/deferred uploading, so rolling back and we'll take another crack at it later.

FORMS-2327: Revert File Upload Queuing

---

app/src/db/migrations/20250513152242_assigned_user_to_submissions_vw.js

The current submission views (submissions_vw and submissions_data_vw) only contain assignee name and email fields, but do not expose the assignee's user ID. This limitation prevents the application from properly tracking and querying submissions by the assigned user's ID.
submissions_vw has: formSubmissionAssignedToFullName and formSubmissionAssignedToEmail
submissions_data_vw has: assignee (name) and assigneeEmail
Missing: User ID reference for assignees
Migration file: 20250513152242_assigned_user_to_submissions_vw.js
Views updated: submissions_vw, submissions_data_vw
New columns: formSubmissionAssignedToUserId, assigneeUserId
This is a database-only change

feat: FORMS-2317 Add assigneeUserId to submission views

---

app/frontend/package-lock.json
app/frontend/package.json
app/package-lock.json
app/package.json

Dependabot found some high priority issues - multer and axios need to be updated.

FORMS-2348: update high priority dependabot issues

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/designer/FormViewer.vue

When viewing public forms in readonly mode (submission review), file download links should be disabled and greyed out, while non public forms maintain normal download functionality.
Acceptance Criteria:
- File downloads disabled (grey, non-clickable) for public forms in readonly mode i.e after submission they cannot download the file they uploaded
- File downloads remain functional for private forms in readonly mode
- 

fix: FORMS-2470 disable file downloads for public forms after submission

---

app/frontend/src/components/designer/settings/FormFunctionalitySettings.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/tests/unit/components/designer/settings/FormFunctionalitySettings.spec.js
app/src/forms/form/service.js
app/tests/unit/forms/form/service.spec.js

Removes the public form limitation for the assignee column visibility control feature, allowing form designers to enable the assignee column for **all form types** (including public forms).
- **FormFunctionalitySettings.vue**: Removed `&& form.userType !== ID_MODE.PUBLIC` condition
- **SubmissionsTable.vue**: Removed public form identity provider check in `showAssigneeColumn` computed property
- **service.js**: Updated `_setAssigneeInSubmissionsTable()` and `_shouldIncludeAssignee()` to remove public form validation
- **Tests**: Updated all test cases to reflect new behavior where public forms can use assignee features

feat: FORMS-2469 - Remove public form limitation for assignee column display

---

app/src/forms/admin/service.js

There was a small bug which prevented searching in the admin tables.

Forms 2510 Admin Table Search Fix

---

app/src/forms/file/middleware/upload.js
app/src/forms/file/storage/objectStorageService.js

File uploads with Unicode characters cause multiple issues:
1. **502 Storage Errors**: Files with Unicode filenames fail in submissions view with S3 signature errors
2. **S3 Metadata Issues**: Unicode characters in S3 metadata headers break HTTP header encoding
**Example failing cases:**
- Em dashes: `"DO NOT REPLY — Community Gaming Grants Decision enclosed.pdf"`
**Two separate but related issues:**
1. **Multer Layer**: Missing filename sanitization allows problematic Unicode to reach storage
2. **S3 Storage Layer**: Unicode characters in S3 metadata break HTTP header encoding and signature generation
- **Added Unicode-aware filename sanitization** in `multer.diskStorage` using proper Unicode normalization (NFD/NFC) and international character support
- **Fixed S3 metadata encoding** by …

fix: FORMS-2529-resolve file upload hanging with Unicode filenames

---

app/app.js
app/src/components/log.js

When we changed OIDC Realms, the token contents changed.
This PR addresses how we parse out username for logging (if available).

FORMS-1194: fix parsing username from token for logs

---

app/knexfile.js

In Production had a few clusters of Knex connection pool timeouts. Code does commit and rollback, so likely pool is just a little too small. POSTGRESQL_MAX_CONNECTIONS is 500, so raising the Knex pool to 20. Will have to keep an eye on CPU/Memory usage.

FORMS-2535: increase connection pool size.

---

app/frontend/src/components/forms/manage/ExternalAPIs.vue

THis is just an update of a techdoc link.

FORMS-2544: External API techdoc update

---

tests/functional/cypress/e2e/form-design-advancedfield.cy.js
tests/functional/cypress/e2e/form-draft-submission-management.cy.js
tests/functional/cypress/e2e/form-submission-assign-revise-status.cy.js
tests/functional/cypress/fixtures/test_submissions.json
tests/functional/cypress/support/login.js

Cypress test scripts for the functionality of multiple draft upload on submission page
- Enable multiple draft upload functionality on form settings page
- Verify multiple file upload functionality allows only json file to upload
- Verify upload successful message
- Verify uploaded file is present on submission page as draft

test: FORMS- 2539 Add multiple draft upload on submission page 

---

app/frontend/src/components/admin/AdminAPIsTable.vue
app/frontend/src/components/admin/AdminFormsTable.vue
app/frontend/src/components/admin/AdminUsersTable.vue
app/src/forms/admin/service.js

The Admin Panel has strange behaviour surrounding search, namely the search results bounce around as the various requests come in and update the table. I implemented debouncing on the search input so there are not seperate requests for each keypress in the search bar. It is these requests arriving out of order which would cause the results table to jump around.  Also the filter for only viewing deleted forms is fixed.

FORMS-2589: Admin panel fixes

---

.devcontainer/.dockerignore
.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/install-cypress.sh
.devcontainer/post-install.sh
.dockerignore
.gitignore
.vscode/tasks.json

Rebuilding and opening the devcontainer is slow, optimizing the Dockerfile for layering, adding checks to post-install, making cypress optional, adding tasks for cypress.
When changing branches and after a merge to dev, I Rebuild the Container and it takes far too long. This is to speed it up and give me back more time for development work.
The biggest change is moving cypress to an optional part of the install, once the container is built and open: Run Tasks -> Install Cypress or Install Cypress (Interactive).
The .devconainer/.dockerignore allows for a smaller image (faster to build, smaller layers).
Added a JRE to the image for SonarQube, so that should load faster after rebuilds and removes the prompt asking if it should download a JRE.

Devcontainer Performance Improvement

---

clamav/charts/clamav/values.yaml

ClamAV loads definititions into memory for speed. We always exceed the requested memory (small) so recommended that we just make the request large enough to hold the file.
To prevent Openshift from checking memory request and issuing warnings when we exceed, just set it because we know it will load the definitions into memory.
These helm charts are run manually, dev has already been deployed. 
perf (change to improve performance)

FORMS-2573: clamav just request the memory limit

---

components/src/components/SimpleNumber/Component.ts

Fix for reported rounding error.

Hotfix for rounding

---

app/frontend/src/components/designer/FormViewerActions.vue
app/frontend/src/components/forms/submission/ManageSubmissionUsers.vue

Instead of hiding the manage team button in the submission view, making the button disabled with a descriptive tooltip was seen as preferred. This is for users to better understand the functionality of sharing draft submisisons with other users and discover it themselves instead of being told about it specifically.

Manage Submission Users Button Enhancement
