app/frontend/src/components/designer/FormDesigner.vue

Remove onChange listener, allow FormBuilder component to autoset our bound instance variable.
Looks like all the work and variable set/reset in the onChange handler was causing event loop issues and weird behaviour.
Create complex forms with many layout controls, all seemed to save and render just fine.  
See [SHOWCASE-1567](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1567)

FormDesigner - Various stack errors

---

app/src/db/migrations/20200925103025_003-submission-users.js
app/src/forms/common/models/models.js
app/src/forms/common/models/utils.js
app/src/forms/form/service.js
app/src/forms/submission/controller.js
app/src/forms/submission/index.js
app/src/forms/submission/routes.js
app/src/forms/submission/service.js
app/src/routes/v1.js
app/tests/unit/routes/v1.spec.js

Make direct submission routes. GET /submissions/:id
Do more fine-grained permissions checks (user can have permissions on the submission itself).
New table and view for user permissions on a submission, allows us to have many users have access to the submission (ex. creator and a staff reviewer can have read/write access).
**NOTE**: the API result for read is an object that has {form, version, submission}, this allows the caller to create a complete view of the submission without calling for form metadata or version/schema data separately.
See [SHOWCASE-1554](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1554)
Once this is in place and being used for reading submission, we should remove the other routes/services for read and …

Submission Access

---

app/src/db/migrations/20201019100738_007-public-submission-data-vw.js

Public users do not get permissions to a submission, but their data needs to be included in export.
The underlying view used for exports would not include any of their data, so use left outer joins on the permissions table and account for nulls in fullName and username fields (as we do with their currentUser tokens).

Include public data in submission data (export) view

---

app/src/forms/common/models/models.js

If Form name is entered as a number, when knex reads from the DB, it auto converts to a number. We need it to be a string because of our virtual attribute: snake.

Make sure form.name is a string

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/store/modules/form.js
app/frontend/src/views/form/Create.vue
app/frontend/src/views/form/Design.vue

Fix so create page asks you if you want to leave again. This is for close tab/browser or refresh.
Add Vue route guards so that you get prompted if you use a nav, go back etc.
Add a dirty flag on change to trigger when to do either of these.
Changes to create new form and edit form.
No changes to Submit mode, since that opens a new instance of the form there's no navigating so keeping it simple as it is.

Fix and improve page leave warnings

---

app/tests/unit/routes/v1/admin.spec.js
app/tests/unit/routes/v1/form.spec.js
app/tests/unit/routes/v1/permission.spec.js
app/tests/unit/routes/v1/rbac.spec.js
app/tests/unit/routes/v1/role.spec.js
app/tests/unit/routes/v1/submission.spec.js

This is just to ensure proper response codes and routes exist.
This DOES NOT test middleware or keycloak protect, assume caller always has permissions to call the route.
This DOES NOT test the body of the response, or any data access layer code.
See [SHOWCASE-1650](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1650)

Route/Controller Basic Unit Tests

---

app/src/forms/email/assets/confirmation-number-email.html
app/src/forms/email/emailService.js
app/src/forms/form/controller.js
app/src/forms/submission/controller.js
app/src/forms/submission/routes.js
app/tests/unit/routes/v1/form.spec.js
app/tests/unit/routes/v1/submission.spec.js

Add email service to deliver emails for submission confirmation (submitter enters email and POSTS) and for submission received (emails go to configured staff).
Added new endpoint POST /submissions/ID/email body = {to: <email submitter fills out>}
Email service will throw errors, up to the caller how it is handled.
Expected that calling an email service, the permissions have already been checked, so this service will do no current user permission checking.
**IMPORTANT** since there is no persisted configuration for emails, I am using the request header referrer to determine the links in the email.  This does work on OpenShift and localhost, but using Postman you will need to set this header.

Email service for Submission notifications

---

app/frontend/src/components/base/BaseAuthButton.vue
app/frontend/src/components/base/BaseSecure.vue
app/frontend/src/components/designer/FormSettings.vue
app/frontend/src/router/index.js
app/frontend/src/store/modules/auth.js
app/frontend/src/utils/permissionUtils.js
app/frontend/src/utils/transformUtils.js
app/frontend/src/views/form/Submit.vue
app/frontend/src/views/form/Success.vue
app/frontend/tests/unit/utils/transformUtils.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1743
Allow creation of public forms
Add the auth determination into the views on a beforeRouteEnter nav gaurd.
Also put the idp hint for IDIR back in.
Adding a unit test for the permissionutils in a subsequent PR so we can test this out sooner.

Enable Public forms

---

app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/utils/permissionUtils.js
app/frontend/tests/unit/store/modules/form.getters.spec.js
app/frontend/tests/unit/utils/permissionUtils.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1768
Don't throw all the forms that you can only launch into the forms list. Those can be accessed by the share link.
We may revisit this in the future for a forms catalogue or a User forms screen.

Filter My Forms list to not show forms you can just launch

---

app/frontend/src/components/designer/FormSettings.vue

We set the default userType to blank in the store since it was used by Team Management as well. However, when creating a new form we still want the Team option checked by default, so specify in there when that component is created.

Default ID mode in the form settings

---

app/frontend/src/components/designer/FormDesigner.vue

Fix an issue where the Saved alert not showing for draft->draft save.

Alert wasn't showing for initial draft save

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/lib/components/SimpleFile/Component.js
components/src/components/SimpleFile/Component.ts

deployed here:
https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-127/
ticket [https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1838](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1838)
- force a re-render of the formBuilder component (with injected options) when the form userType (public, idir, team, etc) is changed.
- add file upload component to for builder in 'advanced' mode
It sounded like we will need to re-visit UX issues when switching between basic and advanced.

Hide / show 'file upload' component depending on form user type

---

.github/workflows/unit-tests.yaml

We want to prevent situations where the test-coverage step fails because the secret is not defined. It is more reliable to determine whether to execute based on the existence of the secret variable instead.

Skip coverage steps if CC test reporter is missing

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/forms/manage/ManageForm.vue
app/frontend/src/components/forms/manage/ManageVersions.vue
app/frontend/src/views/About.vue
app/frontend/src/views/form/Manage.vue

supports: [https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1881](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1881)
I'll add a few notes to the code here in github.
requirements:
* Call out: make it visually stand out (people are missing this)
** Add icon
* Version info under the form title when created
** User wants to see version information right away (not draft)
* Draft -> just next version (start from version 1, no draft)
* Edit, Export, delete (draft), button on the version history table
* Form Design title (on Manage Form page) & Team Management page
See screenshots in Jira ticket [https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1881](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1881)
it would be good if the 'last updated' date in the form design history table …

Make draft look like the next version

---

components/src/components/Common/Simple.edit.data.ts
components/src/components/SimpleContent/Component.form.ts
components/src/components/SimpleDateTime/Component.ts
components/src/components/SimpleDateTime/editForm/Component.edit.time.ts

Making the Time option disabled by default on the SimpleDateTime Custom FormIO Component. Added a checkbox field to enable it manually.
Allows a better user experience by not letting the Time option be enabled by default.

Time option disabled by default on the SimpleDateTime Custom FormIO Component

---

app/src/forms/form/exportService.js
app/tests/unit/forms/form/exportService.spec.js

[ticket 2114](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2114)
Order of JSON and CSV columns does not match the top-down order of the form
Submission fields in the export are ordered  as they exist in the database (key length and then alphabetical)
We can re-order the columns in the CSV export with the jsonexport 'headers' argument.
.. passing in the meta columns, followed by the fields as they appear in the form schema.
submission fields that arent in the most recent form schema are appended to columns on the end.
This can be done just for the CSV export.

re-order submission data headers in csv export to match form design

---

.github/workflows/unit-tests.yaml
app/src/forms/form/exportService.js

see: [ticket 2114](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2114)
This is an extra fix to my last PR to get submissions export to match the order of the fields as they appear in the form schema.
`_buildCsvHeaders` references the list of fields created in '_readSchemaFields' function.
we need to go recursively into each component in case that component contains nested components.
The way the form schema is structured makes this process not very reliable. this is a best effort.
because any fields in the submission data that arent defined in headers are appended to the export we should be safe here.. 
-Jujaga -> Fixed some of the nasty recursion and edge cases

order csv export columns

---

app/frontend/src/assets/scss/style.scss

Adding CSS to fix dropdowns from being cut off within a Component's Details Modal.
Made changes only in the main style.scss

Dropdown Height Style Fix

---

app/src/docs/v1.api-spec.yaml
app/src/forms/form/controller.js
app/src/forms/form/routes.js
app/src/forms/form/service.js
app/tests/unit/routes/v1/form.spec.js
components/package-lock.json

This PR introduces a /fields and /discover endpoint within the /form/version part of the API which allows users to laterally slice and query for certain subsets of information from their form submissions. This is needed in order to eventually allow for customizable submission columns on the frontend.
[SHOWCASE-2180](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2180)
Check the OpenAPI spec for latest details on endpoint changes. Unit tests coming up soon.
Full path endpoints being proposed:
- `GET {{hostname}}/app/api/v1/forms/:formId/versions/:versionId/fields`
- https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-220/api/v1/docs#operation/readVersionFields …

Implement version-scoped column field query discovery support

---

app/src/forms/form/controller.js
app/src/forms/submission/controller.js
app/src/forms/submission/service.js
app/tests/unit/routes/v1/form.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2188?
Was sending the notification email when a user saved a draft. Should only do on submit.

Don't send emails when saving draft

---

app/src/forms/form/service.js
app/tests/unit/forms/form/service.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2205
When there's a hidden file upload (conditional or anything) there was a 500 error occurring. Fix that, extract the logic where the bug was, and put unit tests to handle all cases.
Was adding an undefined element to the array returned by flatMap (if the file control was not in the schema but not the data). Tweak so the flatMap skips in that case
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap#for_adding_and_removing_items_during_a_map

Fix hidden file support

---

app/src/forms/form/service.js
app/tests/unit/forms/form/service.spec.js

the `readVersionFields()` function that is called when customizing columns doesn't find the fields for this form design:
https://chefs.nrs.gov.bc.ca/app/form/submissions?f=b6c5b8c8-0961-4347-b0fe-4153b3c67b31
It should look for components nested in the 'columns' component.
the unit tests i added were more of an afterthought.. 
A real form schema (fixtures to come in another pr) will be more useful.

find fields nested in columns in a form schema

---

app/frontend/src/assets/scss/style.scss

formio default shows asterisks next to required input in a data grid, as well as column headers.
Looks a bit extraneous. I'm hoping this is an unobtrusive fix without side-affects.

css change to remove asterisk after inputs in data-grid

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/main.js

My pr to add aria/required tags to inputs (pr 233) introduced some console statements saying 'x plugin not found' when you view a form.
I believe the way i was including the templates (in the main.js) was not waiting for the formio base templates and plugins to load.
i think this is a better way of doing it.

include custom form component templates a better way

---

app/frontend/src/components/designer/FormViewerActions.vue

Hiding the View All Submissions button on the Submitter view.
Adding a class to remove the button from print view

hiding view all submissions button on print

---

app/frontend/src/components/admin/AdministerForm.vue
app/frontend/src/services/adminService.js
app/frontend/src/store/modules/admin.js
app/frontend/tests/unit/services/adminService.spec.js
app/src/docs/v1.api-spec.yaml
app/src/forms/admin/controller.js
app/src/forms/admin/routes.js
app/src/forms/admin/service.js
app/tests/unit/routes/v1/admin.spec.js

Original copy paste of the form user endpoint used here was a lot more than needed for Admin FE. FormId wasn't being provided which on large data seemed to be causing DB issues (should only ever call with an ID anyways).
Refactor API service call to simplify it a bunch. Refactor path to match other admin service routes.
Change FE to supply formId in call.

Tailor form user admin endpoint to formId

---

app/frontend/src/components/forms/submission/StatusTable.vue

Updating the status history table to move the status updated by tool tip into its own column.
[Jira Ticket](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2300)

feat: move updated by to own column

---

app/frontend/src/components/forms/manage/AddTeamMember.vue
app/frontend/src/components/forms/submission/ManageSubmissionUsers.vue
app/frontend/src/components/forms/submission/StatusPanel.vue

Made changes to the v-autocomplete components to adhere to new Microsoft Edge browser permissions. This PR is removing the browser's autofill popups by default now.
Tested on FireFox, Chrome, Edge and Safari.
Changed all v-autocomplete components to add a property of `autocomplete="autocomplete_off"`. Edge requires that a random string is added as the value for the autocomplete property.

Autocomplete Issues on Edge

---

app/frontend/src/components/forms/submission/StatusPanel.vue

Changing the Update button based off of the status selected. Update button is disabled when nothing is selected.
REF: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2296
Making conditional changes to the Update button in the StatusPanel component.

Fixing Update button

---

app/frontend/src/components/designer/FormViewerActions.vue
app/src/forms/submission/service.js

Fixing bug where edit icon stays visible after setting submission from Draft -> Submitted.
1. Moved the query to set draft to false after the changeStatusState service call.
2. Added another check to make sure that the submission is a draft in the front end.

Fixing Permissions and Edit Icon on Submissions

---

app/src/db/dataConnection.js
app/src/forms/common/models/utils.js

Making the checkSchema function check for all tables instead of just the form table on whenever the node app starts up.
making new tableNames function to be called on startup.

Node startup checkSchema change

---

app/src/forms/email/emailService.js

Stopping the CHES call when there are no emails provided.
Made changes to the emailService so that it checks the contexts variable for any emails to send to.

Stopping CHES Call when no email provided on Submit

---

app/frontend/.eslintrc.js
app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/components/designer/FormDesigner.vue

When the form is mounted or when a form is fetched, we cache the original schema. When performing an action, we add that action to history of actions in the FormDesigner. These actions include importing a schema, adding, removing, moving, and updating a component. Added an undo button and redo button to the FormDesigner toolbar, both buttons have a counter displaying how many times the user can perform an undo or redo operation. When pressing undo,  we go back one action and generate a form schema from the original schema with all patches up until the previous action and set the form schema to the generated one. When pressing redo,  we go forward one action and generate a form schema from the original schema with all patches up until the next action and set the form schema to the …

Add history of actions in designer and ability to undo/redo actions

---

app/frontend/src/components/forms/SubmissionsTable.vue

Fixes https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2675
Refer to comments here https://github.com/bcgov/common-hosted-form-service/pull/274#pullrequestreview-878089635
The populate form part is actually synchronously dependent on the formFields list after the change from that PR, so it has to await on that. Might be a better way to lay that out than the 2 awaits but it works.
Also fix https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2699
If computing something to determine a truthy value to use in the template, need to make it a computed value or invoke the method response. Can't do `v-if="methodName"` or that's truthy always.

Can't populate submission table until form fields are known

---

app/frontend/src/components/forms/manage/ManageVersions.vue

This is caused by setting the draft version to be equal to the number of form versions + 1. This is resolved by setting the version to the number of form versions + the number of drafts - the number of drafts we've looked at.

Fix version draft duplication

---

app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/views/form/Design.vue

- Change the wording of the confirmation dialog. Also, change the two buttons' texts to "Yes" and "No," respectively
- added isButtonClick to Alert Component in FormDesigner.vue. This ensures that the saved message will only show when form designers click on the save button
- [*] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [*] I have checked that unit tests pass locally with my changes
- [*] I have run the npm script lint on the frontend and backend
- [*] I have added tests that prove my fix is effective or that my feature works
- [*] I have added necessary documentation (if appropriate)
- [*] I have approval from the product owner for the contribution in this pull request

improve confirmation dialog in Design.vue

---

app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/store/modules/form.js

This PR fixes a bug on the My Forms page.  Previously, a link appeared to the URL of the published form even if the form was marked unpublished.  Now, the link to the published URL is disabled for unpublished forms.
Bug fix (non-breaking change which fixes an issue) 
This change was generously supported by Government of Yukon

Disable link to unpublished form

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/components/forms/ColumnPreferences.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/src/forms/form/exportService.js

- fixed submission export start and end date. User cannot select beyond the current day for start date and end date start from the start date selected.
- fixed export csv file not to show columns that are not selected.
- fixed submission export start and end date. User cannot select beyond the current day for start date and end date start from the start date selected.
- fixed export csv file not to show columns that are not selected.
- 

Fixed submission export start and end date issue

---

app/frontend/src/components/forms/ColumnPreferences.vue

When users select all the fields' checkboxes, the "Select All" checkbox is checked. If the click cancel to close dialog box instead of the save button and the dialog box is re-opened, the Select All box is still checked but should not be checked.
When users select all the fields' checkboxes, the "Select All" checkbox is checked. If the click cancel to close dialog box instead of the save button and the dialog box is re-opened, the Select All box is still checked but should not be checked. 

fix Select all checkbox in ColumnPreferences.vue

---

app/package-lock.json
app/package.json

CSV is comma-separated values, so any comma in the form data will be read as a separate field. This fix is to ensure that CSV will see the data as a string and not break the data into different fields
CSV is comma-separated values, so any comma in the form data will be read as a separate field. This fix ensures that CSV will see the data as a string and not break the data into different fields.

Fix form data with comma breaking into separate fields

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/services/formService.js
app/frontend/src/store/modules/form.js
app/frontend/tests/unit/services/formService.spec.js
app/src/forms/auth/middleware/userAccess.js
app/src/forms/auth/service.js
app/src/forms/submission/routes.js
app/tests/unit/routes/v1/submission.spec.js

Users can delete submissions they don't have access to by injecting the submissionIds into the array passed to the multiple submission delete API. This PR fixes that by adding a check to the route.

 fix the loop hole in the multi-user

---

app/frontend/src/components/bcgov/BCGovAlertBanner.vue
app/frontend/src/components/designer/FormDesigner.vue
app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/FormSubmission.vue
app/frontend/src/components/forms/manage/ShareForm.vue
app/frontend/src/router/index.js
app/frontend/src/store/modules/auth.js
app/frontend/src/utils/permissionUtils.js
app/frontend/tests/unit/components/bcgov/BCGovAlertBanner.spec.js
app/frontend/tests/unit/router/index.spec.js
app/frontend/tests/unit/store/modules/notifications.actions.spec.js
app/frontend/tests/unit/utils/permissionUtils.spec.js

The current error messages don't provide enough detail to tell if CHEFS as a whole is down, or if there are problems specific to a single form. Improve the error messages for the scenarios:
- the form exists but there is no published version
- the form ID is correctly formatted but doesn't exist, or the form has been deleted
- the form ID is incorrectly formatted (and can't possibly exist)
Changes made:
- Added a new Vue Component BCGovAlertBanner that implements the [Design System spec](https://developer.gov.bc.ca/Design-System/Alert-Banners).
- Expanded error messages to give better feedback to the user.
- Changed error display for known situations to not display the "An error has occurred..." notification popup.
Also:
- Removed the import of NotificationTypes in FormDesigner.vue since …

feat: FORMS-655 improve error messages for unavailable forms

---

app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/filters/index.js
app/frontend/tests/unit/filters/index.spec.js

Change the timestamp format to have a shorter and consistent length in the tables. Using the format like "2023-02-13 09:02:01 a". This will not change the way that data from the forms is displayed, such as when adding those columns to the submissions table.

feat: FORMS-657 Change timestamp display format in dashboards

---

app/src/forms/form/exportService.js

Add optional chaining for getting latest schema to ovoid 500 if row is null

Hotfix: add optional chaining for geting latest schema

---

app/frontend/src/components/forms/manage/TeamManagement.vue

Team management page in case when team has a lot of members generates time out. We use individual user info API calls to in a loop, so if users count gets big, API call stack exceed 10 seconds. Need to refactor code to make 1 call to get all users information

FORMS-715: Team Management Timeout bug

---

openshift/patroni.dc.yaml

Background: the database is crashing due to CHEFS using `user_form_access_vw` (possibly only for a subset of users, those with large numbers of forms?). The database is offline for around 250ms, and since it drops all connections the CHEFS pods have to re-establish them. 
To improve performance, increase the default memory `request` and `limit` for the Patroni database pods. This will allow more of the data to be kept in memory, making for faster queries.
Performance

perf: FORMS-695 increase memory for patroni pods

---

.gitignore
.vscode/launch.json
.vscode/tasks.json

As a developer who is working on the CHEFS code, I want to be able to:
- Start the API and Frontend code using VSCode rather than the command line
- Run the API in debug mode so that I can set breakpoints and variable watches
- Easily run the test suites using VSCode rather than the command line
Chore (non-breaking change that has no effect on the CHEFS application)

chore: FORMS-726 add launchers and tasks to vscode

---

app/frontend/src/components/designer/FormViewer.vue

Fix a problem with datagrids on a form: if subcomponents have "Allow value propagation" unset, only the first row in the datagrid was being unset. The code needs to handle arrays of components.
We have no tests for this code - once the Vue 3 upgrade is done we need to add tests and refactor all this code (and move the code out of the component). I think I have covered the immediate use case that is having problems, but I don't know if nested datagrids will work or not.

bug: FORMS-793 fix datagrid submission copying

---

app/src/db/migrations/20230705190020_change_file_storage_constrains.js
app/src/forms/common/constants.js

`file_storage` table has a constrain for `storage` field to be `localStorage`, `uploads` or `objectStorage`. This PR is to add `exports` for big form export files

Change the constrain for file_storage to include exports types

---

app/src/db/migrations/20230517012755_32-add-update-col-alter-submissions-vw.js
app/src/docs/v1.api-spec.yaml
app/src/forms/common/models/views/submissionData.js
app/src/forms/form/exportService.js
app/tests/common/dbHelper.js
app/tests/fixtures/submission/kitchen_sink_submission_extract_field_csv_export.json
app/tests/unit/forms/form/exportService.spec.js

* Ticket 14703 - Enhance Export API in CHEFS to support filtering based on status and updates
* Modifications to Export API endpoint to limit user to use allowed columns only
* Ticket 14703 - Enhance Export API in CHEFS to support filtering based on status and updates
* Modifications to Export API endpoint to limit user to use allowed columns only
* Fix issue when single column supplied and fix migration
* Added Unit Tests
* Buggy Test _getSubmissions included
* unit test add for submissionData filterUpdatedAt filter
* Work in progress for unit tests-pending
* Added more unit tests for _getSubmissions function that covers with and without preferences
* Removed unwanted console statements
* Removed package file from root
* Test:Enhance Export API for ETL (#790)
* Ticket 14703 - Enhance …

Enhance export API endpoint (#840)

---

app/src/docs/v1.api-spec.yaml
app/src/forms/submission/routes.js

The GET /submissions/{formSubmissionId} endpoint currently does not allow basic auth using the form API key. Open this up for JEDI users for use with their new event subscription feature (and for other users and use cases too!)
Note: we don't have a good way of testing these kinds of changes. I have tested with Postman but that doesn't help in the future to identify regression problems. We should look at maybe a suite of Postman/newman tests for this sort of thing?

feat: FORMS-830 add basic auth for get submission

---

app/frontend/src/components/designer/FormViewer.vue

Fix a problem with datagrids on a form: if subcomponents have "Allow value propagation" unset, only the first row in the datagrid was being unset. The code needs to handle arrays of components.
We have no tests for this code - once the Vue 3 upgrade is done we need to add tests and refactor all this code (and move the code out of the component). I think I have covered the immediate use case that is having problems, but I don't know if nested datagrids will work or not.

bug: FORMS-827 fix datagrid submission copying

---

app/src/forms/form/service.js

This is a hotfix for Submission list API call 500 error reported by Health there they use `fields` url param as a string instead of array

Hotfix for api call with err: filter not a function

---

app/frontend/src/components/designer/FormViewerMultiUpload.vue
app/frontend/tests/unit/components/designer/MultiUpload.spec.js
app/src/forms/form/service.js
app/tests/unit/forms/form/service.spec.js

Using bulk submission BE accepts all the existing form submission information that leads to duplication of confirmation ID issue. To fix this issue we clean up Submission payload before saving into database means if a form submission sent to BE and having some preexist submission information like 'confirmationId','formName','version','createdAt','fullName','username','email','status','assignee','assigneeEmail' as a form object in it then we need to remove it. So that a clean fresh submission get submitted.

Duplicate confirmation ID issue-pop pre-exist submission info

---

app/src/forms/form/service.js

I had been testing to ensure that throwing a 401 did not break the code but somehow forgot to remove the test
This does not break prod as the call out has happened before throwing the exception which is then immediately caught.
This does cause confusion when reading app logs

Remove 401 error throw

---

app/src/forms/form/service.js

In the work to add event subscriptions, there had been testing to ensure that throwing a 401 did not break the code - but forgot to remove the test. This does not break the app as the call out has happened before throwing the exception, which is then immediately caught. This does cause confusion when reading app logs.

fix: remove 401 error throw in subscriptions

---

app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/utils/permissionUtils.js
app/frontend/tests/unit/utils/permissionUtils.spec.js

A user from NRM has asked if people with Reviewer status can also be able to select which columns appear in the submissions table. For example, an Owner has the following:
- Changed the permissions utilities to take the permissions array rather than having to know how the permissions exist within the form. This made it easier to use the permissions utilities on the submissions table.

feat: FORMS-805 reviewers can pick submission columns

---

app/frontend/src/components/designer/FormViewerActions.vue
app/frontend/src/internationalization/trans/chefs/ar/ar.json
app/frontend/src/internationalization/trans/chefs/de/de.json
app/frontend/src/internationalization/trans/chefs/en/en.json
app/frontend/src/internationalization/trans/chefs/es/es.json
app/frontend/src/internationalization/trans/chefs/fa/fa.json
app/frontend/src/internationalization/trans/chefs/fr/fr.json
app/frontend/src/internationalization/trans/chefs/hi/hi.json
app/frontend/src/internationalization/trans/chefs/it/it.json
app/frontend/src/internationalization/trans/chefs/ja/ja.json
app/frontend/src/internationalization/trans/chefs/ko/ko.json
app/frontend/src/internationalization/trans/chefs/pa/pa.json
app/frontend/src/internationalization/trans/chefs/pt/pt.json
app/frontend/src/internationalization/trans/chefs/ru/ru.json
app/frontend/src/internationalization/trans/chefs/tl/tl.json
app/frontend/src/internationalization/trans/chefs/uk/uk.json
app/frontend/src/internationalization/trans/chefs/vi/vi.json
app/frontend/src/internationalization/trans/chefs/zh/zh.json
app/frontend/src/internationalization/trans/chefs/zhTW/zh-TW.json

As a form submitter, I want an applicable button label for "View all Submissions" to understand what I can expect after selecting the same.
- [] I have added necessary documentation (if appropriate)

rename ViewAllSubmissions label in FormViewerAction.vue

---

app/frontend/src/components/forms/RequestReceipt.vue

When sending an email for submission confirmation the priority was not displaying correctly:
Looks like "text" was the default field displayed in v-select in vuetify v2, but in v3 it's "title":

fix: set default object field used for select

---

app/frontend/src/components/base/BaseStepper.vue
app/frontend/src/components/forms/manage/TeamManagement.vue

1. The list of components that can be added to a form should always be visible on a really long form. The changes to the names of Vuetify 3 CSS selectors broke this functionality.
Before:
After:
***
2. The Team Management table was missing the class that the CSS selectors use. Also updated the CSS to use `deep()` instead of the deprecated `>>>` notation
Before:
After:

fix: various vue3 css fixes

---

app/src/forms/form/exportService.js
app/tests/unit/forms/form/exportService.spec.js

We have a Fider request for the submission ID to be added to the JSON exports. We are already exporting the confirmation ID, which is 8 characters long and taken from the submission ID. The requested change is because the submission ID is essentially unique, but the confirmation ID is much more likely to have a collision. Users who are doing ETL with the exports would greatly prefer to have the more-unique key for the submission.
Since we’re adding the submission ID to the JSON export, it should also be added to the CSV export.
https://chefs-fider.apps.silver.devops.gov.bc.ca/posts/112/data-export-missing-formsubmissionid
Luckily this is already in the view, so it's just a matter of adding it to the columns pulled by the model.

feat: FORMS-882 add submissionId to exports

---

app/src/db/migrations/20231017192656_037-user-form-permissions.js

Very slow performance of the database indicates that the view `user_form_access_vw` is running very slowly. This view is composed of multiple other views, two of which combine every form versus every user. The EXPLAIN plan shows that the problem appears to be with the `role` table, which for some reason is taking up a lot of time. In this example it was 1.6s of the 1.8s query time (although when the problem is happening the queries are more like 30-60s):
1. Analysis of the view showed that in two sub-views, the `role` table is joined but the joins are not necessary.
2. The sub-views both also have EXISTS clauses where the SELECT has multiple columns - these columns are not needed, something simple like `SELECT 1 FROM...`  is good enough. …

fix: simplification of user form access view

---

app/src/db/migrations/20231017192656_037-user-form-permissions.js

Very slow performance of the database indicates that the view `user_form_access_vw` is running very slowly. This view is composed of multiple other views, two of which combine every form versus every user. There are a few things that can be done to improve the performance (and readability) of these views.
1. Remove the join of "role" in user_form_permissions_vw.
2. Remove the join of "role" in user_form_roles_vw.
3. Simplify the EXISTS SELECT in user_form_permissions_vw.
4. Simplify the EXISTS SELECT in user_form_roles_vw.
5. Remove the sorting in the user_form_access_vw.

fix: database view performance

---

app/frontend/src/services/interceptors.js
app/src/db/migrations/20231019153505_038-view-simplification.js

On 2023-10-13 the database started having performance problems. The frontend timeout was changed from 10s to 60s to keep CHEFS usable during the problem analysis. The problem analysis identified many places were improvements could be made.
1. Revert the frontend timeout from 60s to 10s.
2. Change the public_form_access_vw to remove the ORDER BY at the end. When this view is called by the API it is explicitly sorted, so the double sort is not needed.
3. Change the form_vw to remove the ORDER BY at the end. This view is only used by other views, so there is no need to sort it.

fix: FORMS-899 revert timeout and simplify views

---

tests/load/load-test/index.js
tests/load/load-test/package-lock.json
tests/load/load-test/package.json

The GitHub Dependabot process has created an alert for the semver dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/142
Also there is a bug in the tests such that they only work in the local environment and not against the deployments in OCP. This is due to the differences in the SSO configurations and is a very minor fix.
This one doesn't need a feature branch / deploy since it doesn't affect the actual application.

fix: FORMS-893 semver vuln and endpoint bug

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/designer/FormViewerActions.vue

This fix is regarding reported bug https://bcdevex.atlassian.net/wiki/spaces/CCP/pages/1218969620/Invalid+data+remains+in+the+component+without+any+error+message+after+saving+and+then+reopening+a+draft

FORMS-881 - Not allow to save drafts if form validation fails

---

app/src/forms/auth/service.js

Users are reporting that they are occasionally receiving errors with the app. I think it would be best to fix existing errors in the application so that we can rule them out as being the cause of the problem.
When a user (IDIR or BCeID) logs in for the first time, the app is trying to create the “User” object twice. The second create will fail with a database exception, and this seems to have a cascading effect on the connection pool that causes other requests to fail (?).
```
ERROR: duplicate key value violates unique constraint "user_keycloakid_unique"
DETAIL: Key ("keycloakId")=(aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa) already exists.
UniqueViolationError: insert into "user" ("createdAt", "email", "firstName", "fullName", "id", "idpCode", "idpUserId", "keycloakId", "username") values ($1, …
```

fix: FORMS-904 user insert race condition

---

app/app.js
app/config/default.json
app/package-lock.json
app/package.json
app/src/forms/common/middleware/rateLimiter.js
app/src/forms/file/routes.js
app/src/forms/form/routes.js

We had a runaway process that was using an API Key to call an endpoint over a hundred times a minute. This was enough to take down the application due to how intensively the API calls hit the database (which is a different problem to solve). We should have rate limiting in place. Requirements:
- Rate limit all API endpoints using a global rate limiter
- The rate limiter should only be for API Key (basic auth) calls
1. The window was previously 15 minutes, but this would mean a higher allowed rate and a runaway process could run for much longer before it hit the limit. Reduced the window to one minute
2. With discussion with JEDI the limit is 20 calls / minute, but we may need to increase to help them scale (or implement an allow-list of …

fix: FORMS-907 rate limiting for api key calls

---

app/app.js
app/config/default.json
app/package-lock.json
app/package.json
app/src/forms/common/middleware/rateLimiter.js
app/src/forms/file/routes.js
app/src/forms/form/routes.js

We had a runaway process that was using an API Key to call an endpoint over a hundred times a minute. This was enough to take down the application due to how intensively the API calls hit the database (which is a different problem to solve). We should have rate limiting in place. Requirements:
- Rate limit all API endpoints using a global rate limiter
- The rate limiter should only be for API Key (basic auth) calls
1. The window was previously 15 minutes, but this would mean a higher allowed rate and a runaway process could run for much longer before it hit the limit. Reduced the window to one minute
2. With discussion with JEDI the limit is 20 calls / minute, but we may need to increase to help them scale (or implement an allow-list of …

fix: FORMS-907 rate limit all api-key calls

---

app/app.js
app/config/default.json
app/src/forms/form/routes.js
app/src/forms/submission/routes.js
app/tests/unit/routes/v1/form.spec.js
app/tests/unit/routes/v1/submission.spec.js

JEDI is hitting the rate limit, so bump it up from 20 to 60.
Also, by moving the rate limiting to the app as a whole, it had two effects:
1. The static code analysis (CodeQL and GitHub Security) can’t detect that the rate limiting is being applied
2. The 429 errors are not logged - missed this in the testing, but it’s important
So moved it back to the routes from app.js
Bad news is that moving the rate limiting to the routes will cause the rate limiting to be used by the tests - this was breaking the tests once they started returning 429 instead of the expected response. Made the tests for endpoints that allow API Keys to only use Bearer tokens.
Good news - now I know how to test the rate limiting. No time for it now, but will do ASAP as …

fix: FORMS-429 increase rate limit and restore logging

---

app/src/docs/v1.api-spec.yaml
app/src/forms/submission/routes.js

API Key users have the ability to GET submissions but they cannot (logically) DELETE them. For forms that have backend systems that are pulling the submission with GET, it’s desirable to be able to DELETE the submissions when they have been processed.
1. Update the DELETE endpoint in `app/src/forms/submissions/routes.js:18`
2. Update `app/src/docs/v1.api-spec.yaml` documentation to show that BasicAuth is now a possibility for the DELETE endpoint
3. Update `app/src/docs/v1.api-spec.yaml` documentation to add rate limiting headers to both the 200 response and the 429
While I was in the openapi docs:
1. Standardized how the "admin" endpoints display their authorization information (Bearer token plus "admin" role)
2. Added rate …

fix: FORMS-911 allow Api Key to delete submissions

---

app/frontend/src/views/user/Submissions.vue

After the Vue 3 upgrade it was reported by a user that when logged in as a BCeID user, the “View My Drafts/Submissions” page is no longer working and producing an error “403: Forbidden This page requires [ “idir”, “bceid-business” ] authentication. 
Looks like `views/form/Submissions.vue` was duplicated to `views/user/Submissions.vue` and brought along a restriction to `idir` and `bceid-business` where there was none before.

fix: FORMS-920 allow bceid basic to view submissions

---

app/frontend/src/components/base/BaseNotificationBar.vue
app/frontend/src/components/forms/PrintOptions.vue

Addresses an issue with the CDOGS template upload when printing a submission. This feature was failing to generate a document after a template is uploaded on the submissions page.
This was due to `templateForms.files` being an array rather than a file. Using `files[0]` resolved the issue.
Currently, CHEFS users are unable to print a submission when uploading a CDOGS template.
https://bcdevex.atlassian.net/jira/software/c/projects/FORMS/boards/10/backlog?selectedIssue=FORMS-919

FORMS-919: fix CDOGS template print issue

---

app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue

vuetify can't seem to render anything that isn't a string or number so it throws an error and breaks functionality of the entire submissionstable and mysubmissionstable. this converts the data being placed in the table with a stringified version.

fixes the select columns breaking things

---

app/frontend/src/components/admin/AdminFormsTable.vue
app/frontend/tests/unit/components/admin/AdministerFormsTable.spec.js

The “Show Deleted” checkbox on the Admin page’s list of forms is not working. It’s being assigned a value of false but the results being displayed are for true. So then when it is checked, the results are for true again (but page looks like false) and then when it’s unchecked the results are for false (but page looks like true). So the first click nothing changes in the data, but after that the logic for it is backwards.
The actual fix was that the `@click` event was firing before the model was updated. We shouldn't really be doing two things when the state of the component changes - instead just set the data and put a watcher on that data.
The name of the field in the component is “activeOnly” while the text on the page for it is “Show …

fix: FORMS-927 admin show deleted forms checkbox

---

app/frontend/src/components/base/BaseNotificationBar.vue
app/frontend/src/components/forms/ExportSubmissions.vue
app/src/forms/form/controller.js
app/src/forms/form/exportService.js
app/tests/unit/forms/form/controller.spec.js

If a reviewer is trying to export submissions with no submissions, it gives an infinite spinner. This will return an error to the user indicating that there are no submissions if there are no submissions. A valid submission is a form that is not in the draft state or deleted state.
resolves: https://bcdevex.atlassian.net/browse/FORMS-857

prevents export with no submissions

---

app/src/forms/form/service.js

A user reported that the GET /files API does not retrieve files that are uploaded in containers. Upon further investigation, this was also the case for many other components such as data grids, columns, wells, panels, and tables. The error was in checking the form schema's components array, which does not contain all these elements.
The fix now uses the form data instead and handles the case for both arrays and objects to successfully retrieve files from within any component.

 Fix: GET /files API working for Objects and Arrays

---

app/frontend/src/components/forms/manage/AddTeamMember.vue

This PR fixes an issue relating to the 'add a new member' to a form functionality. The console was filled with errors and API calls were timing out when pasting a new team member into input - or sometimes even when just searching for a team member. Also implemented debounce to prevent excessive backend calls, which were previously triggered for each keystroke in the input.
More Info: https://bcdevex.atlassian.net/browse/FORMS-930

fix: FORMS-930-fixed team member search and added debounce

---

app/src/docs/v1.api-spec.yaml
app/src/forms/submission/routes.js

In the Teams channel (2023-12-01 at 16:28) someone is asking if we can allow Basic Auth use of the endpoint `app/api/v1/submissions/{formSubmissionId}/template/render`. This would be so that people who are using the CHEFS API can also use it for their document generation, rather than having to also sign up for CDOGS.
- Update the endpoint with the rate limiting and apiKey middleware
- Update the API documentation Authorizations, plus add the rate limiting info to the 200 response, and the 429 response
> Note: Can’t really add tests since we haven’t really determined how we want to test the route middleware

feat: FORMS-937 allow basicauth for template rendering

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/admin/AdminFormsTable.vue
app/frontend/src/components/base/BaseNotificationBar.vue
app/frontend/src/components/bcgov/BCGovAlertBanner.vue
app/frontend/src/components/designer/FormsTable.vue
app/frontend/src/components/forms/manage/TeamManagement.vue
app/frontend/src/internationalization/trans/chefs/ar/ar.json
app/frontend/src/views/Error.vue
app/frontend/src/views/form/Success.vue
app/frontend/tests/unit/components/admin/AdministerFormsTable.spec.js

The following PR aims to fix issues introduced in the Vue3 migration.
Fixed few translation issues
few alerts/error notifications not translating
form table headers not properly translating on language change
Fixed the logic in the active forms in the Admin Page - it would display the "deleted" header for active forms, but would not for the deleted forms.
More info can be found here: https://bcdevex.atlassian.net/browse/FORMS-925

fix: Fix forms 925 translations and other minor vue 3 frontend problems

---

app/src/forms/common/utils.js
app/src/forms/email/emailService.js
app/src/forms/email/reminderService.js
app/tests/unit/forms/common/utils.spec.js
app/tests/unit/forms/email/emailService.spec.js

If a form has “After Submission” team notification emails configured, they will fail if a submission is sent in via an API call. The `emailService._appUrl` method takes a `referer` parameter that is used to construct the protocol, domain name, and port portions of the URL to the resulting submission. When the request is an API call without the `referer`, it’s failing with an `Invalid URL` error. 
Since the API call will not be including a `referer`, another way must be found to construct the URLs. The fix should work for the various types of URLs that we have:
- http://localhost:5173/app/…
- https://chefs-dev.apps.silver.devops.gov.bc.ca/app/…
- https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-1111/…
- https://submit.digital.gov.bc.c.a/app/…
Bug fix (non-breaking change which fixes an …

fix: FORMS-926 added utils.getBaseUrl for notification urls

---

app/src/forms/common/utils.js
app/src/forms/email/emailService.js
app/src/forms/email/reminderService.js
app/tests/unit/forms/common/utils.spec.js
app/tests/unit/forms/email/emailService.spec.js

If a form has “After Submission” team notification emails configured, they will fail if a submission is sent in via an API call. The `emailService._appUrl` method takes a `referer` parameter that is used to construct the protocol, domain name, and port portions of the URL to the resulting submission. When the request is an API call without the `referer`, it’s failing with an `Invalid URL` error. 
Since the API call will not be including a `referer`, another way must be found to construct the URLs. The fix should work for the various types of URLs that we have:
- http://localhost:5173/app/…
- https://chefs-dev.apps.silver.devops.gov.bc.ca/app/…
- https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-1111/…
- https://submit.digital.gov.bc.c.a/app/…
Bug fix (non-breaking change which fixes an …

feat: FORMS-926 added utils.getBaseUrl for notification urls

---

app/app.js
app/src/forms/admin/index.js
app/src/forms/bcgeoaddress/index.js
app/src/forms/common/middleware/dataErrors.js
app/src/forms/common/utils.js
app/src/forms/file/index.js
app/src/forms/form/index.js
app/src/forms/permission/index.js
app/src/forms/public/index.js
app/src/forms/rbac/index.js
app/src/forms/role/index.js
app/src/forms/submission/index.js
app/src/forms/user/index.js
app/src/forms/utils/index.js
app/tests/unit/forms/common/middleware/dataErrors.spec.js

The function `common/utils/setupMount` is doing `app.use(dataErrors)` but this is a global `use` that should only ever be done once. Because `setupMount` is called from multiple `index.js` files, when an error is thrown the error handling function is being called repeatedly. Using `dataErrors` once will simplify the code and the runtime will be faster and less complicated.
(Ran into a problem when trying to modify `dataErrors` in that the changes needed to handle being run multiple times - not ideal!)
We need to set up some sort of integration tests (postman, etc) to regression test this sort of thing (unless someone can think of a way of unit testing it! I did add tests to cover `dataErrors`, but those don't test that its integrated - …

fix: FORMS-948 use dataErrors only one time

---

app/src/forms/submission/controller.js
app/tests/unit/forms/submission/controller.spec.js

A request has come in from the Teams channel (2023-11-16 11:24 a.m. - Jeremy K.) to be able to include the submission’s Confirmation ID in a CDOGS template. As this field is currently not available in the data sent to CDOGS, it cannot be used in the template.
A couple of catches!
- If we just add `confirmationId` and have it accessible in the CDOGS template as `d.confirmationId` there is the chance that someone could have a field on their form that is also called `confirmationId`. We have seen this problem in the exports. Maybe it would be less likely to have a problem if we were to use it on the form as `d.chefs.confirmationId`?
- If we make the Confirmation ID available, we should also make the Submission ID available. Follow whatever pattern is used for the Confirmation ID, such as …

feat: FORMS-916 add Confirmation ID and Submission ID to data available in CDOGS

---

app/frontend/src/components/designer/FormViewer.vue

The JEDI folks reported that file attachments are causing 403 errors. This was reproduced in dev using a new form containing a Data Grid containing a File Upload component. The form was saved and previewed, and a couple of dozen of attachments were added, and it worked fine. Waited 15 minutes and tried again and it failed with a 403. Probably has nothing to do with the Data Grid either, just the amount of time since the form was opened, and probably something about the SSO token timeout.
This should be viewed as a temporary fix. We need to sort out why the Pinia stores aren't reactive.

fix: FORMS-951 file upload workaround for auth store reactivity problem

---

app/src/forms/common/middleware/dataErrors.js
app/tests/unit/forms/common/middleware/dataErrors.spec.js

If a Problem is being created but not handled, it is eventually handled by the default express middleware error handler. This error handler will correctly return the response to the caller, but will also log the Problem as an ERROR. This is useful when there are unexpected errors in the API, but this logging is not wanted when the problems are due to things like malformed API Key calls. Logging as ERROR should only ever be done when something unexpected happens in the API and it needs to be investigated and fixed.

feat: FORMS-950 only use express error handling for 500s

---

app/app.js

The new custom Rate Limiter middleware for Express is causing the following error message on the first basic auth call to the API:
> ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
This could indicate that we are rate limiting based on a proxy IP address rather than the original IP address of the requester. Need to double-check that this is not the case.
Also look at the IP address being logged - these do not seem to be IP addresses of the requesters, but rather something in between. The problem is probably that we’re …

fix: FORMS-954 express proxy configuration

---

app/frontend/src/components/designer/FormViewerActions.vue

Resolves the issue where the print option would disappear if the submission was not a draft. Resolves the issue where confirmation id and submission id were not appearing in the cdogs print. This was simply because we weren't passing the submissionId to the PrintOptions. Also hid the print button when printing manually.
It does appear that the draft template render is meant to be used by CHEFS whereas the submission template render can be accessed by the API.
This resolves: https://bcdevex.atlassian.net/browse/FORMS-952

Added confirmation id and submission id to cdogs template

---

app/src/forms/auth/middleware/apiAccess.js
app/tests/unit/forms/auth/middleware/apiAccess.spec.js

We get a lot of API Key calls with invalid UUIDs in the path. If these are not valid UUIDs, return 400 and not 401.
The apiAccess code has also increased in code complexity and has duplication in getting the form ID from the submission ID. Refactor to clean this up.
Notes:
- Refactored the part where we figure out the Form ID given the various parameters (form id, submission id, or file id)
- Failed early when there are errors in the parameters, rather than do it in checkCredentials
- The tests are a substantial rewrite. Made them much stricter in checking the HTTP response code
- The tests have to check either the status of the response or the next value - this isn't ideal, but the basic auth library does it one way, and we do it a …

fix: FORMS-946 validate authorization uuids

---

app/src/forms/auth/middleware/userAccess.js
app/src/forms/submission/routes.js

Some apps are making repeated calls to `GET /api/v1/submissions/:submissionId`. This is by far the most commonly called route by API Key users, and is the best target for performance improvements.
The API is currently set up to perform two massive database queries for every call. For API Key calls, the results of these two queries are typically not needed. In particular, the GET submissions route does not need these calls.

fix: FORMS-956 improve get submission performance (#1232)

---

app/src/forms/auth/middleware/userAccess.js
app/src/forms/auth/service.js
app/src/forms/form/routes.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

The API is set up to load the active forms and deleted forms for all API calls. For example, to get a form the API will get the permissions for all active forms and all deleted forms, and then it will pull the one form out of active or deleted to check permissions. We cannot afford these expensive database queries on every API call.
Change the API so that it only fetches the one form that is required to check permissions. Only do the active if the deleted fail.
Since this is a big scary change, only do one set of endpoints at a time. There will need to be a lot of manual testing to check this out.
Going to start with the /forms endpoints and then move onto the others once it checks out.

fix: FORMS-959 optimize the /forms routes

---

app/src/forms/auth/middleware/userAccess.js
app/src/forms/submission/routes.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

The API is set up to load the active forms and deleted forms for all API calls. For example, to get a form the API will get the permissions for all active forms and all deleted forms, and then it will pull the one form out of active or deleted to check permissions. We cannot afford these expensive database queries on every API call.
Change the API so that it only fetches the one form that is required to check permissions. Only do the active if the deleted fail.
Since this is a big scary change, only do one set of endpoints at a time. There will need to be a lot of manual testing to check this out.
Next up is the /submissions endpoints.

fix: FORMS-959 optimize the /submissions routes

---

app/frontend/src/components/forms/ExportSubmissions.vue
app/frontend/tests/unit/components/bcgov/BCGovHeader.spec.js
app/package-lock.json
app/src/forms/form/controller.js
app/src/forms/form/exportService.js
app/tests/unit/forms/form/controller.spec.js

Sometimes formFields in the frontend are given a empty value which is causing it to throw an error and break exporting because it's trying to map an array that isn't an array.
Returned the export fields to always return the correct export type and not a json error message. This also means we won't get an error message on the front end.

Prevent export no subs

---

app/src/forms/auth/middleware/userAccess.js
app/src/forms/form/routes.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js
app/tests/unit/routes/v1/form.spec.js

James P from JEDI reported a problem when calling API routes that have both formId and formVersionId parameters. The data for the formVersionId will be returned even if the form version does not belong to the given formId. Whenever these two parameters exist on a route we need to check that form contains the form version, and return a 400 response if not.
While this is a potential security problem, the exploit would involve having the formVersionId for someone else’s form. The large key space of UUIDs protects us here, but the problem still needs to be fixed.

fix: FORMS-994 check version id in route params

---

app/src/forms/email/reminderService.js
app/tests/unit/forms/email/reminderService.spec.js

The backend is failing to send out submission reminders due to not handling inconsistent state in the database (FORMS-1036). As a first step fix the backend to be more resilient.
```
TypeError: Cannot read properties of undefined (reading 'length')
at Object._getReminders (/opt/app-root/src/app/src/forms/email/reminderService.js:153:29)
at Object._init (/opt/app-root/src/app/src/forms/email/reminderService.js:12:29)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.sendReminderToSubmitter (/opt/app-root/src/app/src/forms/public/service.js:4:12)
at async Object.sendReminderToSubmitter (/opt/app-root/src/app/src/forms/public/controller.js:5:24)
at async /opt/app-root/src/app/src/forms/public/routes.js:25:3
```
Bug fix (non-breaking change which …

fix: FORMS-1037 handle missing submission schedule

---

app/src/docs/v1.api-spec.yaml
app/src/forms/common/middleware/validateParameter.js
app/src/forms/submission/controller.js
app/src/forms/submission/routes.js
app/tests/unit/forms/common/middleware/validateParameter.spec.js
app/tests/unit/forms/submission/controller.spec.js
app/tests/unit/forms/submission/routes.spec.js
app/tests/unit/routes/v1/submission.spec.js

Now that the user can upload document templates for their forms, it would be nice if there was an endpoint that took just a submission id and a template id. This saves the frontend from getting the template and then posting it back to render it.
This won't work for draft submissions, so maybe we need another endpoint for that.

feat: FORMS-1042 new template rendering route

---

app/frontend/src/components/forms/submission/StatusPanel.vue

Status Panel - the assignment dropdown list was not populating the user's idp.
Update code to read the correct value coming from the view query (these are not transformed into user objects so need the name of the view column).

Status Panel dropdown assignment subtitle fix.

---

app/frontend/src/views/file/Download.vue

download view was having an issue with downloading. the link for downloading seems to just refresh the page in a watch function instead of actually downloading the file.

download issue fix

---

app/frontend/src/components/forms/manage/TeamManagement.vue

when generating the table data in team management, we used to already map the "user.idp.code" into an identityProvider variable in a user object. then we tried to map it again which would result in an undefined value. removed the previous map that we used to do, so that if we wanted in the future, we could change what is displayed in the identity provider column to be more human readable. i.e., using the display name IDIR or Basic BCeID vs idir or bceid-basic.

identity provider code fix

---

app/frontend/src/components/forms/manage/DocumentTemplate.vue

The `v-data-table-server` component does not require using the `raw` keyword to access its data items after the Vuetify upgrade. 

CDOGS Template Fix After Vuetify Upgrade

---

app/tests/unit/forms/auth/middleware/userAccess.spec.js
app/tests/unit/forms/file/middleware/filePermissions.spec.js

GitHub is complaining about hard-coded dummy token values in the unit tests. Replace the hard-coded strings with random values.
Refactor (non-breaking change to improve code quality)

refactor: FORMS-1227 remove hardcoded test jwts

---

app/src/forms/form/exportService.js
app/tests/unit/forms/form/exportService.spec.js

A user is making an API Key call with a custom export query and is encountering a bug. The request is:
> GET /app/api/v1/forms/**FORMID**/export?status=COMPLETED&type=submissions&format=csv&version=0
The problem is probably to do with the version being 0, since we start our versioning at 1. The fix should work for any invalid version, though.
Removing the `_readSchemaFieldsV2` method from the service because it isn't used.

fix: FORMS-1081 handle invalid form version in export

---

app/src/forms/auth/middleware/userAccess.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js

Rewriting the `userAccess.hasRolePermissions` tests so that we have nearly 100% coverage. Missing a test for the form ID not existing, but that probably is a bug that needs to be reworked eventually.
Test (changes only made to tests)
- This function should probably be split into two. It's very specific to a couple of endpoints, and maybe it doesn't need to be in the middleware? TBD.
- I'm not a fan of using the "detail" string in the tests, as it's fragile. It would be better to have API-specific error codes that could be used, but that's a much bigger issue. In the meantime using the "detail", otherwise there's a pile of 401 errors and you can't otherwise be sure the mocks are triggering the right one.

test: FORMS-1265 rewrite tests for hasRolePermissions

---

app/src/forms/auth/middleware/userAccess.js
app/src/forms/rbac/routes.js
app/tests/unit/forms/auth/middleware/userAccess.spec.js
app/tests/unit/routes/v1/rbac.spec.js

The `userAccess.hasRolePermissions(removingUsers=false)` function is being flagged by Code Climate as being too long and too complex. Since it is basically two separate functions, split it into two:
- `hasRoleDeletePermissions`: functionality of `hasRolePermissions(true)`
- `hasRoleModifyPermissions`: functionality of `hasRolePermissions(false)`
Refactor (no function code changes but improve the code quality)

refactor: FORMS-1265 split hasRolePermissions into two methods

---

app/src/forms/form/service.js
app/tests/unit/forms/form/service.spec.js

Fix a problem where a trailing comma in the fields parameters was causing the get submissions endpoint to produce a 500 error. Added an exclusion for any fields that are empty or all spaces.

fix: FORMS-993 handle trailing comma in get submissions

---

app/src/docs/v1.api-spec.yaml
app/src/forms/form/exportService.js
app/tests/unit/forms/form/exportService.spec.js

The export was producing 500 errors when the `preference` parameter was unparseable JSON. Added a new internal function to deal with the `preference` and put the JSON parsing in a try/catch block.

fix: FORMS-1113 handle bad json in export

---

app/src/forms/email/emailService.js
app/src/forms/form/controller.js
app/src/forms/form/exportService.js
app/tests/unit/forms/form/exportService.spec.js

Had some 500 errors when a custom API call was made with the parameters:
> /app/api/v1/forms/REMOVED/export?format=csv&template=multiRowEmptySpaceCSVExport&version=2&type=submissions
The problem is that `multiRowEmptySpaceCSVExport` isn't the export template, it's `multiRowEmptySpacesCSVExport`.
Did a bit of simplification of the code as well:
- removed the `referer` parameter from the export code. It was being passed around all over the place and was only ever used in the error log if there was an error sending the email, and even then was of debatable value
- in `emailService.submissionExportLink` removed the unused parameter `referer` to support the above 
- in `emailService.submissionExportLink` removed the unused parameter …

fix: FORMS-1274 invalid export template

---

app/src/docs/v1.api-spec.yaml
app/src/forms/submission/controller.js
app/tests/unit/forms/submission/controller.spec.js

We want to allow the user to select the output file type when they generate a document using CDOGS. The frontend is what is restricting the output file type - it always chooses PDF. The backend, as the frontend is right now, needs no changes. However, the new endpoint that takes a `submissionId` and a `documentTemplateId` is not being used by the frontend, and probably a good thing.
- fixed a bug where the file would never generate correctly
- added the `convertTo` query parameter.

feat: FORMS-1279 cdogs file output type

---

app/app.js

In PR 1139 I removed the setting of `extended: true` for `express.urlencoded`, as true is the default value. It turns out that Express complains if you do not set it to the default value:
```
body-parser deprecated undefined extended: provide extended option at app.js:27:17
```
Revert (non-breaking change that fixes an issue)

revert: FORMS-1139 urlencoded extended setting

---

.github/pull_request_template.md

Just trying to fix the "CONTRIBUTING" link, as it's going to https://github.com/bcgov/common-hosted-form-service/pull/CONTRIBUTING.md, which produces:

fix: FORMS-1302 contributing link correction

---

.github/pull_request_template.md

Another fix for the link - looks like GitHub templates don't do relative URLs the way other files do.

fix: FORMS-1302 PR template link

---

app/tests/unit/forms/file/middleware/upload.spec.js

Added a new file to test the file upload configuration. Uncovered some bugs:
1. Code doesn't handle invalid `maxFileSize`: `bytes.parse` returns `null` if it can't parse, it doesn't throw exceptions
2. Code doesn't properly handle `maxFileCount`: `parseInt` return `NaN` if it can't parse, it doesn't throw exceptions
3. 400 and 500 errors are being created with custom `message` values. We should stick to the stock `message` but provide custom a `detail`.

test: FORMS-1292 file upload

---

app/src/forms/file/middleware/upload.js
app/tests/unit/forms/file/middleware/upload.spec.js

Fix the bugs that were uncovered when writing the unit tests for the file upload:
1. Code doesn't handle invalid `maxFileSize`: `bytes.parse` returns `null` if it can't parse, it doesn't throw exceptions
1. Code doesn't properly handle `maxFileCount`: `parseInt` returns `NaN` if it can't parse, it doesn't throw exceptions
1. 400 and 500 errors are being created with custom `message` values. We should stick to the stock `message` but provide a custom `detail`.
Also converted the upload function to our usual middleware pattern of everything being in a `try` and throwing `Problem`s, and then handling all the `Problem`s in one place.
> Note: This is a breaking change if the caller is relying on the HTTP error response to have a specific `message` or `detail` value (this would …

fix: FORMS-1292 file upload configuration bugs

---

app/src/forms/proxy/controller.js
app/src/forms/proxy/error.js
app/src/forms/proxy/service.js
app/tests/unit/forms/proxy/controller.spec.js
docs/chefs-external-api-configuration.md

Calls to the CHEFS Proxy for External APIs are made during design of the form and configuration of the form components. Without full configuration (expected headers, a configure External API) the `/api/v1/proxy/external` will throw (and log errors). The log gets polluted with "false" negatives and are not truly indicative of the proxy or the external API failing.
This PR is intended to reduce the number of errors written to the log and enhance the return status codes so the form designer and the CHEFS support team can determine appropriate actions.
https://bcdevex.atlassian.net/browse/FORMS-1353
Changes are primarily to the proxy controller and service. The service will throw `ProxyServiceError` on known logic errors. This allows the controller to log those errors as warnings (ex. missing …

Enhanced error handling and warning logging for Proxy/External API.

---

.vscode/launch.json

Fix a problem where the address lookup components are not calling the backend. The URL for the backend route was missing from the environment variables, so added it into the devcontainers launcher.
> Note: This is not a complete fix to get the address components working in localhost, it's just enough to call the backend so that work on other bugs is unblocked. There is a bigger problem with CORS errors to be figured out in FORMS-1364.

fix: FORMS-1008 add address lookup url

---

.github/actions/build-push-container/action.yaml
.vscode/launch.json
components/src/components/BCAddress/Component.ts
components/src/components/SimpleBCAddress/Component.ts
openshift/app.dc.yaml

Refactoring to simplify the environment variables used for the BC Geo Address lookup.
Before refactoring:
- Two environment variables, `VITE_CHEFS_GEO_ADDRESS_APIURL` and `VITE_CHEFS_ADVANCE_GEO_ADDRESS_APIURL`
- The two form.io Components both use `VITE_CHEFS_ADVANCE_GEO_ADDRESS_APIURL`
- `VITE_CHEFS_GEO_ADDRESS_APIURL` is not used
- The environment variables in the deployed pods are not being used - the variables are only needed for the GitHub Actions build
After refactoring:
- Remove the unused `VITE_CHEFS_GEO_ADDRESS_APIURL` variable
- Rename `VITE_CHEFS_ADVANCE_GEO_ADDRESS_APIURL` to `VITE_CHEFS_GEO_ADDRESS_APIURL` because it doesn't really make sense to have an "advanced" if there is no non-advanced
- Remove the two environment variables from the DeploymentConfig, since the …

refactor: FORMS-1007 geo address env variables

---

app/src/components/errorToProblem.js
app/tests/unit/components/errorToProblem.spec.js

When the external BC Geo Address service was returning HTML instead of JSON we were having JSON parse failures and no indication what was in the HTML. Turns out that it was the error handling code assuming that all string responses are JSON.
- Made the error handler more lenient
- Added a missing test to bring the error handler coverage up to 100%
- Refactored the JSON conversion into its own method to hopefully resolve a code climate complaint

fix: FORMS-995 handle address responses

---

.github/workflows/.deploy.yaml
.github/workflows/on_push.yaml

The OWASP ZAP Scan stopped running when we changed the CI/CD pipeline away from the "feature branch" way of doing things. As part of our STRA SoAR we need to run the scan and handle any problems that are identified.
The scan was previously set up as a reusable workflow and is working for PR scans. This PR is to also scan dev after deployment, which is what we had for the old scans.
> Note: GitHub Actions are tricky to test, but this should work. Perhaps best to not merge it until I'm available to deal with problems?

fix: FORMS-1140 run zap on dev

---

app/src/forms/file/middleware/upload.js
app/src/forms/file/storage/objectStorageService.js
app/tests/unit/forms/file/middleware/upload.spec.js

CodeQL is complaining about how a file path is used in the file storage code. There is no way to exploit this, as we define the path and it cannot be changed by the user. However, will correct it just to be safe and to make the tooling happy.
https://github.com/bcgov/common-hosted-form-service/security/code-scanning/1 
Want to get this in quickly so it has time to get used. There are currently no tests for the storage, but will work on them as a followup PR.

fix: FORMS-1304 securely fetch local files

---

app/src/forms/auth/middleware/apiAccess.js
app/src/forms/file/controller.js
app/src/forms/file/middleware/filePermissions.js
app/src/forms/file/routes.js
app/tests/unit/forms/auth/middleware/apiAccess.spec.js
app/tests/unit/forms/file/controller.spec.js
app/tests/unit/forms/file/middleware/filePermissions.spec.js

The `GET /app/api/v1/files/XXX` had an error that the id was not a UUID. This is probably due to custom API calls, rather than bugs in the CHEFS frontend.
Pre-work before adding the validator:
- Rename the `id` parameter to `fileId` - `id` is too generic

fix/FORMS-1336 use fileId for the file id

---

.github/actions/build-push-container/action.yaml
.github/actions/deploy-to-environment/action.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/unit-tests.yaml

The Github actions pipeline needs to be updated: many of the external Actions that we use are still using Node 16, which has been deprecated by GitHub. We should update to the latest versions of the external Actions.

ci: FORMS-1228 update actions deps

---

app/src/forms/common/middleware/validateParameter.js
app/src/forms/file/routes.js
app/tests/unit/forms/common/middleware/validateParameter.spec.js
app/tests/unit/forms/file/routes.spec.js

The `GET /app/api/v1/files/XXX` had an error that the id was not a UUID. This is probably due to custom API calls, rather than bugs in the CHEFS frontend.
- Add a new `fileId` validator to the route(s) that use it

fix: FORMS-1336 validate fileId parameters

---

app/src/forms/auth/middleware/userAccess.js

During the writing of tests for `userAccess.hasRoleModifyPermissions` it was noticed that one condition could not be fully tested. This was because an `if` clause contained a test for something that was impossible given previous tests - so it could never be untrue. Remove the extra if clause so that we have complete code coverage with the unit tests.

refactor: FORMS-1408 remove unnecessary if

---

app/src/README.md
app/src/forms/common/middleware/validateParameter.js
app/src/forms/submission/routes.js
app/tests/unit/forms/auth/middleware/apiAccess.spec.js
app/tests/unit/forms/common/middleware/validateParameter.spec.js
app/tests/unit/forms/file/controller.spec.js
app/tests/unit/forms/file/routes.spec.js
app/tests/unit/forms/form/controller.spec.js
app/tests/unit/forms/form/exportService.spec.js
app/tests/unit/forms/form/externalApi/controller.spec.js
app/tests/unit/forms/form/externalApi/routes.spec.js
app/tests/unit/forms/form/externalApi/service.spec.js
app/tests/unit/forms/form/routes.spec.js
app/tests/unit/forms/form/service.spec.js
app/tests/unit/forms/proxy/service.spec.js
app/tests/unit/forms/submission/routes.spec.js
app/tests/unit/forms/submission/service.spec.js
app/tests/unit/routes/v1/form.spec.js
app/tests/unit/routes/v1/submission.spec.js

The `GET /app/api/v1/submissions/XXX` routes are good candidates for fixing invalid UUID problems. These errors are probably due to custom API calls, rather than bugs in the CHEFS frontend.
1. Add a new `formSubmissionId` validator to the routes that use it.
1. We currently have “route” tests that are actually only testing the controller - add proper route tests and later the other tests will be used as a basis for the controller tests.

fix: FORMS-1237 validate formSubmissionId parameters

---

app/frontend/src/services/formService.js
app/frontend/src/store/form.js
app/frontend/tests/unit/services/formService.spec.js
app/frontend/tests/unit/store/modules/form.actions.spec.js
app/src/forms/submission/controller.js
app/src/forms/submission/routes.js
app/src/forms/submission/service.js
app/tests/unit/forms/submission/controller.spec.js
app/tests/unit/forms/submission/routes.spec.js
app/tests/unit/forms/submission/service.spec.js
app/tests/unit/routes/v1/submission.spec.js

Some of the backend code has “Mutiple” where it is supposed to be “Multiple”. Most of these are in the tests, but they all should be updated to make it easier to search, and to have fewer surprises for anyone who reads / uses the code.

fix: FORMS-1409 fix "mutiple" typos

---

app/src/forms/form/controller.js
app/src/forms/form/externalApi/controller.js
app/src/forms/user/controller.js
app/tests/unit/forms/form/controller.spec.js
app/tests/unit/forms/form/externalApi/controller.spec.js

We sometimes return an HTTP response with a status code and no body, such as for a DELETE verb. There are two ways to do this:
```javascript
res.status(204).send();
```
and
```javascript
res.sendStatus(204);
```
We should always standardize the code to always do things in a single way. Since Express gives `sendStatus` to both set the status and send the response, standardize on using it.

refactor: FORMS-1348 consistently use sendStatus

---

app/frontend/src/components/base/BaseFilter.vue
app/frontend/tests/unit/components/base/BaseFilter.spec.js

BaseFilter was using the wrong default value, making it say the wrong text. This fixes it, added in a test for it as well.

BaseFilter translation fixed

---

app/src/forms/common/middleware/validateParameter.js
app/src/forms/user/routes.js
app/tests/unit/forms/common/middleware/validateParameter.spec.js
app/tests/unit/forms/user/routes.spec.js
app/tests/unit/routes/v1/user.spec.js

FORMS-1204 was tracking the most common database errors that we have due to bad requests. The `GET /app/api/v1/users/preferences/forms/XXX` endpoint is one place to fix the problem. This error is the most common and is probably due to CHEFS frontend bug(s) rather than third-party calls to the API. See FORMS-996.
- Add `formId` validation to the three routes that use it
- There is one route that takes a `userId` parameter - for the sake of completeness of the tests, while we’re in this file add this as a new validator
- The `/user` routes are very simple in terms of middleware use, so it won’t take too much effort to write unit tests for all the routes. Current coverage is high, but we have “route” tests that are actually only testing the controller.
- 92.59% Statements 25/27
- 100% …

fix: FORMS-1209 add user id validation

---

app/tests/unit/forms/admin/routes.spec.js
app/tests/unit/forms/bcgeoaddress/routes.spec.js

Added unit tests for all the routes in `admin/routes.js` and `bcgeoaddress/routes.js`. This is a first step before converting the existing routes tests (which test the controllers, not the routes) into controller tests.

test: FORMS-1444 admin and address routes

---

app/tests/unit/forms/admin/routes.spec.js
app/tests/unit/forms/bcgeoaddress/routes.spec.js
app/tests/unit/forms/file/routes.spec.js
app/tests/unit/forms/form/externalApi/routes.spec.js
app/tests/unit/forms/form/routes.spec.js
app/tests/unit/forms/proxy/routes.spec.js
app/tests/unit/forms/rbac/routes.spec.js
app/tests/unit/forms/submission/routes.spec.js
app/tests/unit/forms/user/routes.spec.js

Added unit tests for all the routes in `rbac/routes.js`. This is a first step before converting the existing routes tests (which test the controllers, not the routes) into controller tests.
Also did some more cleanup:
- for consistency alphabetize imports by module location / name
- for consistency alphabetize the per-file mocks
- for consistency alphabetize the expect clauses
- for consistency use `toBeCalledTimes` not `toHaveBeenCalledTimes`
- for consistency move controller mocks into their specific tests
- for consistency define uuids in their test groups

test: FORMS-1444 add rbac routes tests

---

app/tests/unit/README.md
app/tests/unit/forms/form/externalApi/routes.spec.js
app/tests/unit/forms/form/routes.spec.js
app/tests/unit/forms/proxy/routes.spec.js
app/tests/unit/forms/public/routes.spec.js
app/tests/unit/forms/user/routes.spec.js
app/tests/unit/forms/utils/routes.spec.js

Added unit tests for all the routes in `public/routes.js` and `utils/routes.js`. This is a first step before converting the existing routes tests (which test the controllers, not the routes) into controller tests.

test: FORMS-1444 add public and utils routes tests

---

app/tests/unit/README.md
app/tests/unit/forms/admin/routes.spec.js
app/tests/unit/forms/form/routes.spec.js
app/tests/unit/forms/permission/routes.spec.js
app/tests/unit/forms/proxy/routes.spec.js
app/tests/unit/forms/rbac/routes.spec.js
app/tests/unit/forms/role/routes.spec.js
app/tests/unit/forms/user/routes.spec.js

Enhanced and expanded the `jwtService.protect()` tests to be a little more strict about what is being tested.
> Note: this middleware is tricky to test. In some cases it is used at the file level, and in other cases it's used on a per-route basis. We can write some tests for these, but they're going to break if the routes change how they use the middleware. Also, due to the nature of middleware that is created with parameters, it's hard / impossible to robustly test those parameters.
This is the first of a few PRs for this task, but keeping them small and doing the tests first before refactoring.

test: FORMS-1448 expand jwt service tests

---

app/src/forms/admin/controller.js
app/src/forms/admin/routes.js
app/src/forms/common/middleware/validateParameter.js
app/tests/unit/forms/admin/routes.spec.js
app/tests/unit/routes/v1/admin.spec.js
app/tests/unit/routes/v1/form.spec.js

Now that we have good unit tests for the admin routes, did some additional work on the routes:
- changed the `:id` parameter to something more specific (`externalApiId`) and validate it with existing validator
- validated `componentId` (new validator needed), `formId`, `formVersionId`, and `userId`
- extended unit tests to ensure that validators are being called
- did a bit of comment clarification/formatting
- organized the imports
> Note: the `publishStatus` parameter is not being validated - not even sure what it is, possibly a boolean? Will leave it for now until it's better understood.

fix: FORMS-1448 validate admin route parameters

---

app/src/forms/public/middleware/apiAccess.js
app/src/forms/public/routes.js
app/tests/unit/forms/public/middleware/apiAccess.spec.js
app/tests/unit/forms/public/routes.spec.js

The public/reminder route was previously "fat" with a bunch of code running in the route file.
- move the api key checking into its own middleware
- move api key checking tests into their own file
- simplify the routes.js for public

refactor: FORMS-1488 new middleware for reminder route

---

openshift/README.md
openshift/redash/README.md

On 2024-05-10 version 2.9.0 of the BCDevOps backup-container was released. We should update all of our backup containers to use this latest version:
1. Redash backup; Redash verify
1. Fider backup; Fider verify
1. CHEFS Dev backup; CHEFS Dev verify
1. CHEFS Test backup; CHEFS Test verify
1. CHEFS Prod backup; CHEFS Prod verify

build: FORMS-887 update backup images

---

.codeclimate.yml
.github/workflows/unit-tests.yaml

The Vue (vitest) upgrade broke the code coverage for the frontend. The badge on the repo (65%) represents only the backend coverage.
- Update to use clover for both - may want to back this out and go with lcov for backend and clover for frontend. TBD, no way to test this :(
- Did a bit of alphabetizing in the config file to make things easier to find.

ci: FORMS-1449 code climate test coverage

---

.codeclimate.yml

Code Climate currently has a lot of reports about duplicate code in the form.io component. Since this isn't our code we want to be making as few changes as possible. By removing /components from Code Climate we will get a more accurate maintainability score.
No tests for this. Not even sure that it'll work.

ci: FORMS-1449 code climate exclude components

---

app/package-lock.json

The GitHub Dependabot process has created an alert for the micromatch dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/177 
- The package is updated and resolves the dependabot security warning

build: FORMS-1467 update micromatch version

---

app/src/db/migrations/20240904140843_047-extend-submitter-role.js
app/src/forms/common/constants.js
app/src/forms/form/routes.js

This fixes an incomplete functionality that prevented form submitters from accessing an uploaded document template for CDOGS print.
In the print options dialog, the GET /documentTemplate route is called which requires the `document_template_read` permission, previously only granted to form owners. The intended functionality is that form submitters can use the template while printing a form or a submission, so I have assigned that permission to the `form_submitter` role. 
Bug reported on Confluence:
https://bcdevex.atlassian.net/wiki/spaces/CCP/pages/1550909456/Permissions+on+CDOGS+Print+Template+feature
Jira ticket:
https://bcdevex.atlassian.net/browse/FORMS-1471

Fix: Extend Form Submitter permissions for GET /documentTemplates

---

.github/pull_request_template.md

This PR is for noodling around while writing some Confluence docs.

docs: FORMS-1450 update the PR template

---

app/package-lock.json
app/package.json
app/src/forms/file/storage/objectStorageService.js

On every deployment, and in the unit tests, we get the message:
> NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
> Please migrate your code to use AWS SDK for JavaScript (v3).
> For more information, check the migration guide at https://a.co/7PzMCcy
Upgrade from the v2 to v3 version of the AWS SDK since the v2 is no longer supported.
- We are running a supported version of the AWS SDK
- We no longer have warnings when the pods start up
We didn't have any tests for the S3 storage, and not really sure how we would test this. Leaving it as-is for now, but in the upcoming test writing will be sure to cover this.

build: FORMS-1301 update aws sdk to v3

---

app/package-lock.json
app/package.json

The GitHub Dependabot process has created an alert for the express dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/187

build: FORMS-1499 update express to 4.21.0

---

openshift/README.md
openshift/redash/README.md
openshift/redash/backup-cronjob-verify.yaml

In https://bcdevex.atlassian.net/browse/FORMS-887 most of the images were updated from 2.6.1 to 2.8.0. The production backup failed due to space issues, even though we have 7.8G of space for a 4G database that has 1.7G compressed backups.
- Backups succeed
- Backup verifications succeed
- All backups and verifications run the same container version
Going through the version history of the backup container:
- 2.6.1: where we started
- 2.7.0: changed from gzip to tar; stop ignoring errors
- 2.8.0: mongodb support
- 2.8.1: reverted the gzip to tar change in v2.7.0
- 2.9.0: postgresql 15 support
So the problem is that using tar took up too much space, but fixing it changed the way backups are stored and now that errors aren’t ignored the backup errors actually cause the verify to fail.
Will …

build: FORMS-1476 use backup container v2.9.0

---

.devcontainer/chefs_local/local.json.sample
app/config/default.json
app/package-lock.json
app/package.json
app/src/forms/common/middleware/rateLimiter.js
app/tests/unit/README.md
app/tests/unit/forms/common/middleware/rateLimiter.spec.js

The CodeQL security scan recommends having rate limiting on all routes that touch the database. This is to prevent denial of service attacks by calling these “resource heavy” routes repeatedly. We already have `common/middleware/rateLimiter.js` for the API Key callers, but we need one for all callers.
As a first step, remove the restriction that the rate limiting is only for API Key users. If there are no problems with the routes that are configured to use the rate limiting, future pull requests will extend the rate limiting to additional routes.
> This is a breaking change for people using the devcontainer. In the directory `.devcontainer/chefs_local` you must update your `local.json` to use the values changed in `local.json.sample`.
First of a few PRs for this change.

fix: FORMS-1303 api rate limiting for all users

---

app/src/forms/admin/routes.js
app/src/forms/permission/routes.js
app/src/forms/role/routes.js

The CodeQL security scan recommends having rate limiting on all routes that touch the database. This is to prevent denial of service attacks by calling these “resource heavy” routes repeatedly.
This work will be split into a few Pull Requests so that we can monitor behaviour. This PR will apply API rate limiting to the currently non-limited routes in /admin, /permission, and /role.
> Note: no tests for this. The end goal is to have the rate limiter applied in the root app.js, and removed from each of these route.js files. No point in writing tests for the route.js files only to turf them later.

fix: FORMS-1303 rate limit admin, permission, and role

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/components/forms/SubmissionsTable.vue
app/frontend/src/components/forms/submission/MySubmissionsTable.vue
app/frontend/src/store/form.js
app/frontend/tests/unit/components/forms/submission/MySubmissionsTable.spec.js

MySubmissionsTable now persists the column selection for the currently active form in local storage. This adds a new package called @vueuse/core. This allows us to store data in the local session storage. We've replaced filterData with mySubmissionPreferences which is in the form store. mySubmissionPreferences is stored to local storage using vueuse/core.
This was a requested feature. It allows for a similar user experience on the previous submissions page to the form submissions page.
This is a breaking change because ... We've introduced a new package called @vueuse/core. This may break things on the front end, but should not affect data on the backend.

feat: Added column persistence to MySubmissionsTable

---

app/app.js
app/src/forms/admin/routes.js
app/src/forms/file/routes.js
app/src/forms/form/routes.js
app/src/forms/permission/routes.js
app/src/forms/role/routes.js
app/src/forms/submission/routes.js
app/tests/unit/forms/file/routes.spec.js
app/tests/unit/forms/form/externalApi/routes.spec.js
app/tests/unit/forms/form/routes.spec.js
app/tests/unit/forms/proxy/routes.spec.js
app/tests/unit/forms/submission/routes.spec.js

The CodeQL security scan recommends having rate limiting on all routes that touch the database. This is to prevent denial of service attacks by calling these “resource heavy” routes repeatedly.
We already had `common/middleware/rateLimiter.js` for the API Key callers, but we need one for all callers. The existing limiter was extended to provide a different (higher) limit for the web application users. The final rate limiter solution is applied to all routes automatically and doesn’t need to be added on a route-by-route basis.
- All API routes must use IP-based rate limiting
- The rate limiting must never impact normal web app use
- The CodeQL rate limiting alerts should be automatically resolved as ‘fixed’
- It's unknown if this will fix the CodeQL warnings or not. If not, …

fix: FORMS-1303 move rate limiting to app.js

---

app/src/docs/v1.api-spec.yaml

The preference parameter in the API specification is currently formatted incorrectly as follows 
This format should be updated to a valid JSON format.
{"minDate":"2020-12-17T08:00:00Z","maxDate":"2020-12-18T08:00:00Z","updatedMinDate":"2020-12-17T08:00:00Z","updatedMaxDate":"2020-12-18T08:00:00Z"}

fix: FORMS-1661 - Update API Spec for Preferences Parameter Format

---

.github/workflows/pr_undeploy.yaml

GitHub has changed the `ubuntu-latest` image to no longer include the `oc` command. Add it as a separate step, similar to how the PR Deploy Action works.
> _Note: We unfortunately have to merge Actions before we can try them out. Fingers crossed._

fix: FORMS-1670 install oc for pr undeploy action.

---

app/frontend/src/components/designer/FormViewerActions.vue
app/frontend/src/components/forms/FormSubmission.vue
app/frontend/tests/unit/components/designer/FormViewerActions.spec.js
app/frontend/tests/unit/components/forms/FormSubmission.spec.js

FORMS-1642 - As a form designer, I want the option to have the form to default to Wide Layout mode when submitters land on the form, so they do not need the additional step to turn it on/off

fix: FORMS-1642 - Wide Layout Mode as default when users land on form

---

app/package-lock.json
app/package.json

The GitHub Dependabot process has created an alert for the `path-to-regexp` dependency. To path-to-regexp the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/218
- The dependency is updated to a version that does not have the vulnerability

fix: update express for path-to-regexp vuln

---

.github/workflows/on_push.yaml

The on_push Action displays the URL of the deployed environment for dev, test, and production. However, we use the vanity URL [submit.digital.gov.bc.ca](http://submit.digital.gov.bc.ca/), which is not what is displayed in the Action:
- The URL in the production deployment is the proper URL of the app.

ci: FORMS-1681 fix production url in push action

---

components/package-lock.json
components/package.json

It’s a best practice to have as few dependencies as possible. The “components” project that houses the form.io components has many packages in its dependencies that don’t appear to be used. Remove whatever is not needed.
> Note: while we can search the code for package use, it’s entirely possible that some packages are needed but not in an obvious way. After this change the app should be monitored for errors.
- Unused dependencies are removed
- The app continues to function as before
Including the dev dependencies this reduces the package count from 656 to 461. A side effect is that it will probably get rid of some security vulnerabilities picked up by dependabot.

build: FORMS-1679 remove unused components dependencies

---

.github/workflows/reusable-owasp-zap.yaml

GitHub has announced that after January 30th, 2025, their Action `upload-artifact` v3 will no longer run. This v3 has been deprecated for some time, but the Action we use to run the OWASP ZAP Scan did not get updated to v4 until November 21st, 2024. We are using v0.10.0, update to v0.12.0 to fix the problem.
- There are no deprecation warnings or failures from upload-artifact when the OWASP ZAP Scan runs

ci: FORMS-1597 update owasp zap scan action

---

tests/functional/package-lock.json

The GitHub Dependabot process has created an alert for the `cross-spawn` dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/217
- cross-spawn no longer appears in the list of dependabot security vulnerabilities
- the tests continue to function correctly
The `cypress` package includes `execa`, which includes `cross-spawn`. Although we're a few minor versions behind the latest Cypress, the latest does not include the fix yet. As a temporary fix …

test: FORMS-1683 update cross-spawn for security fix

---

.devcontainer/chefs_local/docker-compose.yml

When building the devcontainer a docker compose file is used. Running this file creates the following warning:
> docker compose -f /workspaces/common-hosted-form-service/.devcontainer/chefs_local/docker-compose.yml down
> 
> WARN[0000] /workspaces/common-hosted-form-service/.devcontainer/chefs_local/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
- The warning no longer appears when the container is built

fix: FORMS-1685 remove obsolete version attribute

---

components/package-lock.json

The GitHub Dependabot process has created an alert for the `nanoid` dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/219
- Our `package-lock.json` is using `nanoid` v3.3.7
- The `nanoid` fix version, and latest version, is v3.3.8
- `nanoid` is a dependency of `postcss` (^3.3.7)
- Our `package-lock.json` is using `postcss` v8.4.49, which is the latest version
- `postcss` is a dependency of `css-loader` (^8.4.33)
- Our `package.json` is using `css-loader` v7.1.2, which is the latest version …

build: FORMS-1687 nanoid vulnerability fix

---

app/frontend/src/components/admin/Developer.vue
app/frontend/src/services/rbacService.js
app/frontend/src/store/form.js
app/frontend/tests/unit/components/admin/Developer.spec.js
app/frontend/tests/unit/services/rbacService.spec.js
app/src/docs/v1.api-spec.yaml
app/src/forms/rbac/controller.js
app/src/forms/rbac/routes.js
app/src/forms/rbac/service.js
app/tests/unit/forms/rbac/controller.spec.js
app/tests/unit/forms/rbac/routes.spec.js
app/tests/unit/forms/rbac/service.spec.js

Get Current User always returns form data even when not used. Make the fetch of user form data explicit by adding new API to fetch the current user forms.
See JIRA tickets: [FORMS-1000](https://bcdevex.atlassian.net/browse/FORMS-1000) and [FORMS-1677](https://bcdevex.atlassian.net/browse/FORMS-1677).
We want to eliminate fetching and returning the current user's forms on each call to `getCurrentUser`. The forms are not always needed and the list can be pretty large (when having access to IDIR forms, for instance).
Where we need the forms, we make an explicit call to a new endpoint. Note that the current user form list is different than other form list APIs. This new endpoint is to return the exact same data in the exact same structure as it appeared previously.
perf …

FORMS-1707: decouple forms from current user, optimize performance

---

app/frontend/package-lock.json

The GitHub Dependabot process has created an alert for the `cross-spawn` dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/216
- `cross-spawn` is a dependency of `eslint`
- Our `eslint` is v8.40.0, but latest is v9.18.0
- Updating `eslint` to v9 would force updates of its dependencies, such as `prettier`
- For this vulnerability fix we’ll just update `cross-spawn` and deal with `eslint` and `prettier` later
- `cross-spawn` is no longer in dependabot’s list of vulnerabilities
build (change in …

build: FORMS-1758 update the cross-spawn dependency

---

.devcontainer/devcontainer.json

In the devcontainers we now have seven ports, but they are not labeled and it’s not obvious what they’re used for.
It would be better if we labeled these ports so that it was obvious what they were used for. It also appears that the 8081 port isn’t being used.
An example of these labels can be found in portsAttributes settings of this repo:
[queue-management/.devcontainer/devcontainer.json at main · bcgov/queue-management](https://github.com/bcgov/queue-management/blob/main/.devcontainer/devcontainer.json) 
Acceptance Criteria
All of the ports have labels that make it obvious what they are used for.

fix: FORMS-1703 Added Tags to port numbers, removed unused port number

---

app/src/docs/v1.api-spec.yaml
app/src/forms/permission/controller.js
app/src/forms/permission/routes.js
app/src/forms/permission/service.js
app/src/forms/role/controller.js
app/src/forms/role/routes.js
app/src/forms/role/service.js
app/tests/unit/forms/permission/routes.spec.js
app/tests/unit/forms/role/routes.spec.js
app/tests/unit/routes/v1/permission.spec.js
app/tests/unit/routes/v1/role.spec.js

We have API endpoints that allow the creation and updating of roles and permissions. We do not use these endpoints to change the roles and permissions, though, as those actions are done through the Knex migrations (to maintain consistency between environments).
We should remove these API endpoints so that we no longer need to maintain the code.
Acceptance Criteria
- The `POST` and `PUT` endpoints for permissions and roles are removed
- The corresponding controller, service, and ORM functions are also removed
- The OpenAPI documentation is removed
The acceptance criteria listed removing the ORM part of these routes, but it turns out that the database logic is actually in the service.

fix: FORMS-1776 remove role and permission routes

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
Dockerfile

The Red Hat Advanced Cluster Security (ACS) application has identified the image `node` as having vulnerabilities that are fixable. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this image must be updated to resolve fixable vulnerabilities (or mitigated in some other way, if updating the image is not possible).
- We are using the most recent version of Node
- Node is updated both for the devcontainer and the deployed runtime
- Removed setting the VARIANT value so that we have fewer places to update
- Addressed a Sonar complaint about packages not being in alphabetical order
- Addressed a Sonar complaint about `apt-get clean` not being run
- Addressed a Sonar …

build: FORMS-1799 node update for security fixes

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/tests/unit/components/forms/manage/DocumentTemplate.spec.js
app/frontend/tests/unit/composables/documentTemplate.spec.js
app/frontend/vite.config.mjs

The GitHub Dependabot process has created an alert for the `happy-dom` dependency. To satisfy the requirements outlined in the Security Threat and Risk Assessment's (STRA) Statement of Acceptable Risks (SoAR), this vulnerability must be handled by updating the package version (or mitigated in some other way, if updating the package is not possible).
https://github.com/bcgov/common-hosted-form-service/security/dependabot/211 
Note: also fixed a warning that the test config file format is using a deprecated element structure.

build: FORMS-1768 update happy-dom to fix vulnerability

---

app/src/components/idpService.js
app/tests/unit/components/idpService.spec.js

Fix logic and hole in unit tests, user search failing for required=2 when passing the first param (works when passing the second).
Seeing errors in log for user search...
```
{"component":"app","level":"error","message":"Could not retrieve BCeID users. Invalid options provided.","stack":"Error: Could not retrieve BCeID users. Invalid options provided.\n    at IdpService.userSearch (/opt/app-root/src/app/src/components/idpService.js:190:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.list (/opt/app-root/src/app/src/forms/user/controller.js:9:24)\n    at async /opt/app-root/src/app/src/forms/user/routes.js:45:3","timestamp":"2025-02-24T17:55:42.013Z"}
```
For BCeID user searches, one of: `username` or `email` is required. The unit …

FORMS-1920: BCeID User search fails

---

app/frontend/src/components/designer/FormViewer.vue
app/frontend/src/components/forms/submission/ManageSubmissionUsers.vue
app/frontend/tests/unit/components/base/BaseInternationalization.spec.js
app/frontend/tests/unit/components/designer/FormViewer.spec.js
app/frontend/tests/unit/components/forms/ExportSubmissions.spec.js
app/frontend/tests/unit/components/forms/manage/DocumentTemplate.spec.js
app/frontend/tests/unit/components/forms/manage/ManageVersions.spec.js
app/frontend/tests/unit/components/forms/manage/TeamManagement.spec.js
app/frontend/tests/unit/components/forms/submission/AuditHistory.spec.js
app/frontend/tests/unit/components/forms/submission/ManageSubmissionUsers.spec.js
app/frontend/tests/unit/utils/permissionUtils.spec.js
app/frontend/tests/unit/views/form/Create.spec.js

FORMS 2091 - a lot of vitests were printing to stderr, a lot of pollution in the logs and this sometimes gave fails when run on openshift. Clean up the `ECONNREFUSED` errs and invalid components. Basically initialize the tested components better and mock implement all api calls in the component. I also removed `console.error` code put in place solely for test conditions. Just test the result.
There is still one I couldn't fix `MultiUpload.spec.js`. `[Vue warn]: onMounted is called when there is no active component instance to be associated with`. This is a weird component that I don't think was updated form Options to Composition API. I think the component itself needs updating, then worry about the test.
There is also a `window.scrollTo` error when running on Openshift. I don't see it …

FORMS 2091 vitest stderr fixes

---

app/frontend/src/store/form.js
app/frontend/tests/unit/components/forms/manage/TeamManagement.spec.js

This is the most common type of form, so makes sense to make this the default. They still must choose the providers.

Set the form default access to login

---

app/src/docs/v1.api-spec.yaml
app/src/forms/submission/routes.js
app/tests/unit/forms/submission/routes.spec.js

The GET /:formSubmissionId/notes route now requires apiAccess middleware in addition to submission review permissions. Updated the OpenAPI spec to reflect new security requirements and adjusted unit tests to expect the apiAccess check.
Reference:
https://citz-do.atlassian.net/browse/FORMS-2667
https://chefs-fider.apps.silver.devops.gov.bc.ca/posts/228/enable-basic-auth-support-for-notes-api-submissions-formsubmissionid-notes

feat: Add API access check to submission notes route
